In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import os
import gc
import json
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import cv2
import nibabel as nib

import tensorflow as tf

from scipy.ndimage import binary_fill_holes
from scipy.spatial.distance import cdist

print("TensorFlow:", tf.__version__)

gpus = tf.config.list_physical_devices("GPU")
print("GPU(s):", gpus)

if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("✓ GPU memory growth enabled")
    except RuntimeError as e:
        print("GPU memory-growth warning:", e)

TensorFlow: 2.20.0
GPU(s): [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
✓ GPU memory growth enabled

In [ ]:
SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

try:
    tf.config.experimental.enable_op_determinism()
    print("✓ TensorFlow deterministic operations enabled")
except Exception as e:
    print("Determinism note:", e)

print("Seed:", SEED)

✓ TensorFlow deterministic operations enabled
Seed: 42

In [ ]:
PROJECT_DIR = Path("/content/drive/MyDrive/CAMUS_FINAL")

PHASE1_DIR = PROJECT_DIR / "phase1_segmentation"

# Previous completed experiment
P1A_DIR = PHASE1_DIR / "phase1A_resolution"
P1A_CONFIG_DIR = P1A_DIR / "configs"
P1A_TABLE_DIR = P1A_DIR / "tables"
P1A_MODEL_DIR = P1A_DIR / "models"

# New Phase 1B
P1B_DIR = PHASE1_DIR / "phase1B_hyperparameters"

P1B_CONFIG_DIR = P1B_DIR / "configs"
P1B_MODEL_DIR = P1B_DIR / "models"
P1B_HISTORY_DIR = P1B_DIR / "histories"
P1B_TABLE_DIR = P1B_DIR / "tables"
P1B_PLOT_DIR = P1B_DIR / "plots"

for folder in [
    P1B_DIR,
    P1B_CONFIG_DIR,
    P1B_MODEL_DIR,
    P1B_HISTORY_DIR,
    P1B_TABLE_DIR,
    P1B_PLOT_DIR
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project:", PROJECT_DIR)
print("Phase 1A:", P1A_DIR)
print("Phase 1B:", P1B_DIR)
print("\n✓ Phase 1B folder structure ready.")

Project: /content/drive/MyDrive/CAMUS_FINAL
Phase 1A: /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1A_resolution
Phase 1B: /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters

✓ Phase 1B folder structure ready.

In [ ]:
P1A_DECISION_PATH = (
    P1A_CONFIG_DIR
    / "phase1A_final_resolution_decision.json"
)

assert P1A_DECISION_PATH.exists(), (
    f"Phase 1A decision file not found:\n{P1A_DECISION_PATH}"
)

with open(P1A_DECISION_PATH, "r") as f:
    phase1a_decision = json.load(f)

SELECTED_RESOLUTION = int(
    phase1a_decision["selected_resolution"]
)

assert SELECTED_RESOLUTION == 256, (
    "Phase 1B expected the Phase 1A selected resolution to be 256."
)

print("Phase 1A status:",
      phase1a_decision["status"])

print(
    "Selected resolution:",
    f"{SELECTED_RESOLUTION}×{SELECTED_RESOLUTION}"
)

print(
    "Phase 1A parameter count:",
    phase1a_decision["parameter_count"]
)

print("\n✓ Phase 1A decision successfully loaded.")
print("✓ Resolution locked at 256×256 for Phase 1B.")

Phase 1A status: COMPLETED
Selected resolution: 256×256
Phase 1A parameter count: 1940817

✓ Phase 1A decision successfully loaded.
✓ Resolution locked at 256×256 for Phase 1B.

In [ ]:
DATASET_PATH = Path(
    "/content/camus_data_final/database_nifti"
)

if DATASET_PATH.exists():
    print("✓ CAMUS dataset already extracted.")
    print("Dataset:", DATASET_PATH)

else:
    print("CAMUS dataset is not currently extracted.")
    print("The archive will need to be extracted again.")

CAMUS dataset is not currently extracted.
The archive will need to be extracted again.

In [ ]:
import zipfile
import shutil

OUTER_ZIP_PATH = Path(
    "/content/drive/MyDrive/download.zip"
)

OUTER_EXTRACT_DIR = Path(
    "/content/camus_data"
)

INNER_ARCHIVE_PATH = (
    OUTER_EXTRACT_DIR / "download"
)

INNER_EXTRACT_DIR = Path(
    "/content/camus_data_final"
)

DATASET_PATH = (
    INNER_EXTRACT_DIR / "database_nifti"
)


if DATASET_PATH.exists():

    print("✓ Dataset already available.")
    print(DATASET_PATH)

else:

    assert OUTER_ZIP_PATH.exists(), (
        f"Outer archive not found:\n{OUTER_ZIP_PATH}"
    )

    # ------------------------------------------------------------
    # Extract outer archive
    # ------------------------------------------------------------

    if not INNER_ARCHIVE_PATH.exists():

        print("Extracting outer archive...")

        OUTER_EXTRACT_DIR.mkdir(
            parents=True,
            exist_ok=True
        )

        with zipfile.ZipFile(
            OUTER_ZIP_PATH,
            "r"
        ) as outer_zip:

            outer_zip.extractall(
                OUTER_EXTRACT_DIR
            )

        print("✓ Outer archive extracted.")

    else:

        print("✓ Inner archive already available.")


    # ------------------------------------------------------------
    # Extract inner archive
    # ------------------------------------------------------------

    if not DATASET_PATH.exists():

        print("Extracting inner CAMUS archive...")

        INNER_EXTRACT_DIR.mkdir(
            parents=True,
            exist_ok=True
        )

        with zipfile.ZipFile(
            INNER_ARCHIVE_PATH,
            "r"
        ) as inner_zip:

            inner_zip.extractall(
                INNER_EXTRACT_DIR
            )

        print("✓ Inner archive extracted.")


assert DATASET_PATH.exists(), (
    "CAMUS database_nifti folder was not found "
    "after extraction."
)

print("\n✓ CAMUS dataset ready:")
print(DATASET_PATH)

Extracting outer archive...
✓ Outer archive extracted.
Extracting inner CAMUS archive...
✓ Inner archive extracted.

✓ CAMUS dataset ready:
/content/camus_data_final/database_nifti

In [ ]:
split_candidates = list(
    PROJECT_DIR.rglob("patient_split_seed42.json")
)

print("Split files found:")

for path in split_candidates:
    print(" -", path)

assert len(split_candidates) >= 1, (
    "Could not find patient_split_seed42.json "
    "inside CAMUS_FINAL."
)

SPLIT_PATH = split_candidates[0]

with open(SPLIT_PATH, "r") as f:
    patient_split = json.load(f)


# Support the naming used by the saved split
train_ids = patient_split.get(
    "train_ids",
    patient_split.get("train")
)

val_ids = patient_split.get(
    "val_ids",
    patient_split.get("validation",
    patient_split.get("val"))
)

test_ids = patient_split.get(
    "test_ids",
    patient_split.get("test")
)


assert train_ids is not None
assert val_ids is not None
assert test_ids is not None

assert len(train_ids) == 400
assert len(val_ids) == 50
assert len(test_ids) == 50

assert len(
    set(train_ids) &
    set(val_ids)
) == 0

assert len(
    set(train_ids) &
    set(test_ids)
) == 0

assert len(
    set(val_ids) &
    set(test_ids)
) == 0


print("\nSplit file:")
print(SPLIT_PATH)

print("\nTrain patients:", len(train_ids))
print("Validation patients:", len(val_ids))
print("Test patients:", len(test_ids))

print("\nIMPORTANT:")
print("Test patients will NOT be used in Phase 1B.")

print("\n✓ Original patient-level split verified.")

Split files found:
 - /content/drive/MyDrive/CAMUS_FINAL/splits/patient_split_seed42.json

Split file:
/content/drive/MyDrive/CAMUS_FINAL/splits/patient_split_seed42.json

Train patients: 400
Validation patients: 50
Test patients: 50

IMPORTANT:
Test patients will NOT be used in Phase 1B.

✓ Original patient-level split verified.

In [ ]:
baseline_256_path = (
    P1A_MODEL_DIR
    / "baseline_unet_256.keras"
)

assert baseline_256_path.exists(), (
    f"Phase 1A 256 model not found:\n{baseline_256_path}"
)

patient_folders = sorted([
    p.name
    for p in DATASET_PATH.iterdir()
    if p.is_dir()
    and p.name.startswith("patient")
])

assert len(patient_folders) == 500, (
    f"Expected 500 CAMUS patients, "
    f"found {len(patient_folders)}."
)


print("=" * 70)
print("PHASE 1B — PRE-EXPERIMENT VERIFICATION")
print("=" * 70)

print(
    "\nLocked resolution:",
    f"{SELECTED_RESOLUTION}×{SELECTED_RESOLUTION}"
)

print(
    "Baseline architecture parameters:",
    phase1a_decision["parameter_count"]
)

print("Train patients:", len(train_ids))
print("Validation patients:", len(val_ids))
print("Test patients:", len(test_ids))

print(
    "\nPhase 1A baseline checkpoint:"
)
print(baseline_256_path)

print(
    "\nDataset patients verified:",
    len(patient_folders)
)

print("\nPHASE 1B ORDER:")
print("1B-1  Learning rate")
print("1B-2  Optimizer")
print("1B-3  Batch size")
print("1B-4  Augmentation")

print("\nNOT being changed yet:")
print("• Resolution")
print("• U-Net capacity")
print("• Loss function")
print("• Threshold")

print("\nTest set used for model selection: NO")

print("\n✓ Ready to begin Phase 1B-1.")

======================================================================
PHASE 1B — PRE-EXPERIMENT VERIFICATION
======================================================================

Locked resolution: 256×256
Baseline architecture parameters: 1940817
Train patients: 400
Validation patients: 50
Test patients: 50

Phase 1A baseline checkpoint:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1A_resolution/models/baseline_unet_256.keras

Dataset patients verified: 500

PHASE 1B ORDER:
1B-1  Learning rate
1B-2  Optimizer
1B-3  Batch size
1B-4  Augmentation

NOT being changed yet:
• Resolution
• U-Net capacity
• Loss function
• Threshold

Test set used for model selection: NO

✓ Ready to begin Phase 1B-1.

In [ ]:
# ================================================================
# PHASE 1B — CELL 9
# CAMUS FRAME LOADING + PREPROCESSING
# ================================================================

def load_nifti_2d(file_path):
    nii = nib.load(str(file_path))
    data = np.asarray(nii.get_fdata(), dtype=np.float32)

    if data.ndim == 3 and data.shape[-1] == 1:
        data = data[:, :, 0]

    if data.ndim != 2:
        raise ValueError(
            f"Expected 2D image at {file_path}, got {data.shape}"
        )

    return data


def load_camus_frame(patient_id, phase):

    patient_dir = DATASET_PATH / patient_id

    image_path = (
        patient_dir /
        f"{patient_id}_4CH_{phase}.nii.gz"
    )

    mask_path = (
        patient_dir /
        f"{patient_id}_4CH_{phase}_gt.nii.gz"
    )

    image = load_nifti_2d(image_path)
    full_mask = load_nifti_2d(mask_path)

    # CAMUS label 1 = LV cavity
    lv_mask = (full_mask == 1).astype(np.float32)

    return image, lv_mask


def preprocess_frame(image, mask, resolution=SELECTED_RESOLUTION):

    image_resized = cv2.resize(
        image,
        (resolution, resolution),
        interpolation=cv2.INTER_LINEAR
    )

    mask_resized = cv2.resize(
        mask,
        (resolution, resolution),
        interpolation=cv2.INTER_NEAREST
    )

    # Per-image min-max normalization
    minimum = float(image_resized.min())
    maximum = float(image_resized.max())

    if maximum > minimum:
        image_resized = (
            (image_resized - minimum) /
            (maximum - minimum)
        )
    else:
        image_resized = np.zeros_like(
            image_resized,
            dtype=np.float32
        )

    image_resized = image_resized.astype(np.float32)
    mask_resized = (mask_resized > 0.5).astype(np.float32)

    return (
        image_resized[..., None],
        mask_resized[..., None]
    )


print("✓ CAMUS loading and preprocessing functions ready.")

✓ CAMUS loading and preprocessing functions ready.

In [ ]:
# ================================================================
# PHASE 1B — CELL 10
# MEMORY-FRIENDLY DATA GENERATOR
# ================================================================

def frame_generator(patient_ids, shuffle=True, seed=SEED):

    frame_list = [
        (pid, phase)
        for pid in patient_ids
        for phase in ["ED", "ES"]
    ]

    rng = np.random.default_rng(seed)

    while True:

        indices = np.arange(len(frame_list))

        if shuffle:
            rng.shuffle(indices)

        for index in indices:

            pid, phase = frame_list[index]

            image, mask = load_camus_frame(
                pid,
                phase
            )

            x, y = preprocess_frame(
                image,
                mask,
                SELECTED_RESOLUTION
            )

            yield x, y

            del image, mask, x, y

In [ ]:
# ================================================================
# PHASE 1B — CELL 11
# TF.DATA DATASET CREATION
# ================================================================

BATCH_SIZE = 4

TRAIN_FRAMES = len(train_ids) * 2
VAL_FRAMES = len(val_ids) * 2

TRAIN_STEPS = TRAIN_FRAMES // BATCH_SIZE
VAL_STEPS = VAL_FRAMES // BATCH_SIZE


output_signature = (
    tf.TensorSpec(
        shape=(
            SELECTED_RESOLUTION,
            SELECTED_RESOLUTION,
            1
        ),
        dtype=tf.float32
    ),
    tf.TensorSpec(
        shape=(
            SELECTED_RESOLUTION,
            SELECTED_RESOLUTION,
            1
        ),
        dtype=tf.float32
    )
)


train_dataset = tf.data.Dataset.from_generator(
    lambda: frame_generator(
        train_ids,
        shuffle=True,
        seed=SEED
    ),
    output_signature=output_signature
).batch(
    BATCH_SIZE,
    drop_remainder=True
).prefetch(1)


val_dataset = tf.data.Dataset.from_generator(
    lambda: frame_generator(
        val_ids,
        shuffle=False,
        seed=SEED
    ),
    output_signature=output_signature
).batch(
    BATCH_SIZE,
    drop_remainder=False
).prefetch(1)


print("Training frames:", TRAIN_FRAMES)
print("Validation frames:", VAL_FRAMES)

print("Batch size:", BATCH_SIZE)
print("Training steps:", TRAIN_STEPS)
print("Validation steps:", VAL_STEPS)

print("\n✓ Memory-friendly datasets ready.")

Training frames: 800
Validation frames: 100
Batch size: 4
Training steps: 200
Validation steps: 25

✓ Memory-friendly datasets ready.

In [ ]:
# ================================================================
# PHASE 1B — CELL 12
# LOSS + TRAINING METRICS
# ================================================================

SMOOTH = 1e-6


def dice_coefficient(y_true, y_pred):

    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred, tf.float32)

    intersection = tf.reduce_sum(
        y_true * y_pred,
        axis=[1, 2, 3]
    )

    denominator = (
        tf.reduce_sum(
            y_true,
            axis=[1, 2, 3]
        )
        +
        tf.reduce_sum(
            y_pred,
            axis=[1, 2, 3]
        )
    )

    dice = (
        (2.0 * intersection + SMOOTH)
        /
        (denominator + SMOOTH)
    )

    return tf.reduce_mean(dice)


def iou_metric(y_true, y_pred):

    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred, tf.float32)

    intersection = tf.reduce_sum(
        y_true * y_pred,
        axis=[1, 2, 3]
    )

    union = (
        tf.reduce_sum(
            y_true,
            axis=[1, 2, 3]
        )
        +
        tf.reduce_sum(
            y_pred,
            axis=[1, 2, 3]
        )
        -
        intersection
    )

    iou = (
        (intersection + SMOOTH)
        /
        (union + SMOOTH)
    )

    return tf.reduce_mean(iou)


def dice_loss(y_true, y_pred):

    return 1.0 - dice_coefficient(
        y_true,
        y_pred
    )


def bce_dice_loss(y_true, y_pred):

    bce = tf.keras.losses.binary_crossentropy(
        y_true,
        y_pred
    )

    bce = tf.reduce_mean(bce)

    return bce + dice_loss(
        y_true,
        y_pred
    )


print("✓ BCE + Dice loss ready.")
print("✓ Dice and IoU metrics ready.")

✓ BCE + Dice loss ready.
✓ Dice and IoU metrics ready.

In [ ]:
# ================================================================
# PHASE 1B — CELL 13
# FIXED BASELINE U-NET
# ================================================================

def conv_block(x, filters):

    x = tf.keras.layers.Conv2D(
        filters,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = tf.keras.layers.Conv2D(
        filters,
        3,
        activation="relu",
        padding="same"
    )(x)

    return x


def build_baseline_unet(
    input_shape=(256, 256, 1)
):

    inputs = tf.keras.Input(
        shape=input_shape
    )

    # Encoder
    c1 = conv_block(inputs, 16)
    p1 = tf.keras.layers.MaxPooling2D()(c1)

    c2 = conv_block(p1, 32)
    p2 = tf.keras.layers.MaxPooling2D()(c2)

    c3 = conv_block(p2, 64)
    p3 = tf.keras.layers.MaxPooling2D()(c3)

    c4 = conv_block(p3, 128)
    p4 = tf.keras.layers.MaxPooling2D()(c4)

    # Bottleneck
    c5 = conv_block(p4, 256)

    # Decoder
    u6 = tf.keras.layers.Conv2DTranspose(
        128, 2, strides=2, padding="same"
    )(c5)

    u6 = tf.keras.layers.Concatenate()(
        [u6, c4]
    )

    c6 = conv_block(u6, 128)

    u7 = tf.keras.layers.Conv2DTranspose(
        64, 2, strides=2, padding="same"
    )(c6)

    u7 = tf.keras.layers.Concatenate()(
        [u7, c3]
    )

    c7 = conv_block(u7, 64)

    u8 = tf.keras.layers.Conv2DTranspose(
        32, 2, strides=2, padding="same"
    )(c7)

    u8 = tf.keras.layers.Concatenate()(
        [u8, c2]
    )

    c8 = conv_block(u8, 32)

    u9 = tf.keras.layers.Conv2DTranspose(
        16, 2, strides=2, padding="same"
    )(c8)

    u9 = tf.keras.layers.Concatenate()(
        [u9, c1]
    )

    c9 = conv_block(u9, 16)

    outputs = tf.keras.layers.Conv2D(
        1,
        1,
        activation="sigmoid"
    )(c9)

    segmentation_model = tf.keras.Model(
        inputs,
        outputs,
        name="Baseline_UNet"
    )

    return segmentation_model

In [ ]:
# ================================================================
# PHASE 1B — CELL 14
# ARCHITECTURE VERIFICATION
# ================================================================

tf.keras.backend.clear_session()
gc.collect()

architecture_check_model = build_baseline_unet(
    input_shape=(
        SELECTED_RESOLUTION,
        SELECTED_RESOLUTION,
        1
    )
)

BASELINE_PARAMETER_COUNT = (
    architecture_check_model.count_params()
)

print(
    "Baseline U-Net parameters:",
    BASELINE_PARAMETER_COUNT
)

assert BASELINE_PARAMETER_COUNT == 1940817, (
    "Architecture does not match Phase 1A!"
)

print("✓ Architecture exactly matches Phase 1A.")

del architecture_check_model
tf.keras.backend.clear_session()
gc.collect()

Baseline U-Net parameters: 1940817
✓ Architecture exactly matches Phase 1A.

0

In [ ]:
# ================================================================
# PHASE 1B — CELL 15
# CREATE IDENTICAL INITIAL WEIGHTS
# ================================================================

INITIAL_WEIGHTS_PATH = (
    P1B_CONFIG_DIR
    / "baseline_initial_weights.weights.h5"
)

tf.keras.backend.clear_session()
gc.collect()

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

initialization_model = build_baseline_unet(
    input_shape=(
        SELECTED_RESOLUTION,
        SELECTED_RESOLUTION,
        1
    )
)

initialization_model.save_weights(
    INITIAL_WEIGHTS_PATH
)

print("Initial weights saved:")
print(INITIAL_WEIGHTS_PATH)

print(
    "\nParameters:",
    initialization_model.count_params()
)

del initialization_model

tf.keras.backend.clear_session()
gc.collect()

print("\n✓ One common initialization created for all LR runs.")

Initial weights saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/configs/baseline_initial_weights.weights.h5

Parameters: 1940817

✓ One common initialization created for all LR runs.

In [ ]:
# ================================================================
# PHASE 1B — CELL 16
# SAVE LEARNING-RATE EXPERIMENT PROTOCOL
# ================================================================

LEARNING_RATES = [
    1e-3,
    1e-4,
    1e-5
]

MAX_EPOCHS = 30


lr_protocol = {

    "experiment":
        "Phase 1B-1 — Learning Rate",

    "objective":
        "Compare learning rates while keeping all other "
        "training and model settings fixed.",

    "resolution":
        SELECTED_RESOLUTION,

    "architecture":
        "Baseline U-Net",

    "parameters":
        BASELINE_PARAMETER_COUNT,

    "learning_rates":
        LEARNING_RATES,

    "optimizer":
        "Adam",

    "batch_size":
        BATCH_SIZE,

    "loss":
        "BCE + Dice",

    "augmentation":
        False,

    "maximum_epochs":
        MAX_EPOCHS,

    "checkpoint_monitor":
        "val_dice_coefficient",

    "checkpoint_mode":
        "max",

    "threshold":
        0.50,

    "seed":
        SEED,

    "train_patients":
        len(train_ids),

    "validation_patients":
        len(val_ids),

    "test_used":
        False,

    "common_initialization":
        str(INITIAL_WEIGHTS_PATH)
}


LR_PROTOCOL_PATH = (
    P1B_CONFIG_DIR
    / "learning_rate_experiment_protocol.json"
)


with open(
    LR_PROTOCOL_PATH,
    "w"
) as f:

    json.dump(
        lr_protocol,
        f,
        indent=2
    )


print("✓ LR protocol saved:")
print(LR_PROTOCOL_PATH)

✓ LR protocol saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/configs/learning_rate_experiment_protocol.json

In [ ]:
# ================================================================
# PHASE 1B — CELL 17
# LEARNING-RATE TRAINING FUNCTION
# ================================================================

def lr_name(learning_rate):

    mapping = {
        1e-3: "1e-3",
        1e-4: "1e-4",
        1e-5: "1e-5"
    }

    return mapping[learning_rate]


def train_learning_rate_experiment(
    learning_rate
):

    run_name = lr_name(
        learning_rate
    )

    print("\n" + "=" * 70)
    print(
        f"TRAINING LEARNING RATE = {run_name}"
    )
    print("=" * 70)

    # ------------------------------------------------------------
    # Clean previous model from GPU/RAM
    # ------------------------------------------------------------

    tf.keras.backend.clear_session()
    gc.collect()

    # ------------------------------------------------------------
    # Re-establish reproducibility
    # ------------------------------------------------------------

    random.seed(SEED)
    np.random.seed(SEED)
    tf.random.set_seed(SEED)

    # ------------------------------------------------------------
    # Build fresh model
    # ------------------------------------------------------------

    segmentation_model = build_baseline_unet(
        input_shape=(
            SELECTED_RESOLUTION,
            SELECTED_RESOLUTION,
            1
        )
    )

    # ------------------------------------------------------------
    # Load IDENTICAL initial weights
    # ------------------------------------------------------------

    segmentation_model.load_weights(
        INITIAL_WEIGHTS_PATH
    )

    # ------------------------------------------------------------
    # Compile
    # ------------------------------------------------------------

    segmentation_model.compile(

        optimizer=tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        ),

        loss=bce_dice_loss,

        metrics=[
            dice_coefficient,
            iou_metric
        ]
    )

    # ------------------------------------------------------------
    # Output paths
    # ------------------------------------------------------------

    model_path = (
        P1B_MODEL_DIR
        / f"lr_{run_name}_best.keras"
    )

    history_path = (
        P1B_HISTORY_DIR
        / f"lr_{run_name}_history.csv"
    )

    # ------------------------------------------------------------
    # Best validation-Dice checkpoint
    # ------------------------------------------------------------

    checkpoint = tf.keras.callbacks.ModelCheckpoint(

        filepath=str(model_path),

        monitor="val_dice_coefficient",

        mode="max",

        save_best_only=True,

        verbose=1
    )

    # ------------------------------------------------------------
    # Train
    # ------------------------------------------------------------

    start_time = time.time()

    history = segmentation_model.fit(

        train_dataset,

        validation_data=val_dataset,

        epochs=MAX_EPOCHS,

        steps_per_epoch=TRAIN_STEPS,

        validation_steps=VAL_STEPS,

        callbacks=[
            checkpoint
        ],

        verbose=1
    )

    training_minutes = (
        time.time() - start_time
    ) / 60.0

    # ------------------------------------------------------------
    # Save history
    # ------------------------------------------------------------

    history_df = pd.DataFrame(
        history.history
    )

    history_df.index = (
        np.arange(len(history_df)) + 1
    )

    history_df.index.name = "epoch"

    history_df.to_csv(
        history_path
    )

    # ------------------------------------------------------------
    # Determine best epoch
    # ------------------------------------------------------------

    val_dice_values = np.asarray(
        history.history[
            "val_dice_coefficient"
        ],
        dtype=float
    )

    best_index = int(
        np.argmax(val_dice_values)
    )

    best_epoch = best_index + 1

    best_val_dice = float(
        val_dice_values[best_index]
    )

    best_val_iou = float(
        history.history[
            "val_iou_metric"
        ][best_index]
    )

    result = {

        "learning_rate":
            learning_rate,

        "learning_rate_name":
            run_name,

        "parameters":
            int(
                segmentation_model.count_params()
            ),

        "epochs_completed":
            len(history.history["loss"]),

        "best_epoch":
            best_epoch,

        "best_val_dice_training":
            best_val_dice,

        "val_iou_at_best_dice_epoch":
            best_val_iou,

        "training_minutes":
            training_minutes,

        "model_path":
            str(model_path),

        "history_path":
            str(history_path)
    }

    print("\n" + "-" * 70)

    print(
        f"LR {run_name} COMPLETE"
    )

    print(
        "Best epoch:",
        best_epoch
    )

    print(
        "Best validation Dice:",
        round(best_val_dice, 6)
    )

    print(
        "Validation IoU at best epoch:",
        round(best_val_iou, 6)
    )

    print(
        "Training time:",
        round(training_minutes, 2),
        "minutes"
    )

    print(
        "Best model:",
        model_path
    )

    print("-" * 70)

    # ------------------------------------------------------------
    # Clean GPU memory
    # ------------------------------------------------------------

    del segmentation_model
    del history

    tf.keras.backend.clear_session()
    gc.collect()

    return result

In [ ]:
# ================================================================
# PHASE 1B — CELL 18
# RUN 1: LEARNING RATE = 1e-3
# ================================================================

lr_result_1e3 = train_learning_rate_experiment(
    1e-3
)

lr_result_1e3

======================================================================
TRAINING LEARNING RATE = 1e-3
======================================================================
Epoch 1/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.3728 - iou_metric: 0.2557 - loss: 0.9362
Epoch 1: val_dice_coefficient improved from None to 0.74080, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 1: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 111ms/step - dice_coefficient: 0.5399 - iou_metric: 0.3956 - loss: 0.6667 - val_dice_coefficient: 0.7408 - val_iou_metric: 0.5930 - val_loss: 0.3541
Epoch 2/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.7624 - iou_metric: 0.6263 - loss: 0.3487
Epoch 2: val_dice_coefficient improved from 0.74080 to 0.84366, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 2: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.7971 - iou_metric: 0.6731 - loss: 0.2990 - val_dice_coefficient: 0.8437 - val_iou_metric: 0.7335 - val_loss: 0.2129
Epoch 3/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.8557 - iou_metric: 0.7546 - loss: 0.2125
Epoch 3: val_dice_coefficient improved from 0.84366 to 0.87794, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 3: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.8613 - iou_metric: 0.7628 - loss: 0.2040 - val_dice_coefficient: 0.8779 - val_iou_metric: 0.7855 - val_loss: 0.1714
Epoch 4/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.8774 - iou_metric: 0.7870 - loss: 0.1768
Epoch 4: val_dice_coefficient improved from 0.87794 to 0.88119, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 4: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.8782 - iou_metric: 0.7884 - loss: 0.1775 - val_dice_coefficient: 0.8812 - val_iou_metric: 0.7921 - val_loss: 0.1779
Epoch 5/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8850 - iou_metric: 0.7985 - loss: 0.1676
Epoch 5: val_dice_coefficient did not improve from 0.88119
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - dice_coefficient: 0.8866 - iou_metric: 0.8009 - loss: 0.1661 - val_dice_coefficient: 0.8746 - val_iou_metric: 0.7827 - val_loss: 0.1966
Epoch 6/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.8961 - iou_metric: 0.8150 - loss: 0.1520
Epoch 6: val_dice_coefficient improved from 0.88119 to 0.89921, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 6: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.8954 - iou_metric: 0.8140 - loss: 0.1521 - val_dice_coefficient: 0.8992 - val_iou_metric: 0.8203 - val_loss: 0.1518
Epoch 7/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9039 - iou_metric: 0.8271 - loss: 0.1408
Epoch 7: val_dice_coefficient improved from 0.89921 to 0.90297, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 7: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9039 - iou_metric: 0.8272 - loss: 0.1403 - val_dice_coefficient: 0.9030 - val_iou_metric: 0.8265 - val_loss: 0.1398
Epoch 8/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9110 - iou_metric: 0.8387 - loss: 0.1291
Epoch 8: val_dice_coefficient improved from 0.90297 to 0.90417, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 8: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - dice_coefficient: 0.9085 - iou_metric: 0.8348 - loss: 0.1335 - val_dice_coefficient: 0.9042 - val_iou_metric: 0.8285 - val_loss: 0.1490
Epoch 9/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.9103 - iou_metric: 0.8375 - loss: 0.1301
Epoch 9: val_dice_coefficient did not improve from 0.90417
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.9122 - iou_metric: 0.8408 - loss: 0.1274 - val_dice_coefficient: 0.9022 - val_iou_metric: 0.8245 - val_loss: 0.1358
Epoch 10/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - dice_coefficient: 0.9180 - iou_metric: 0.8501 - loss: 0.1184
Epoch 10: val_dice_coefficient improved from 0.90417 to 0.91156, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 10: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.9168 - iou_metric: 0.8483 - loss: 0.1204 - val_dice_coefficient: 0.9116 - val_iou_metric: 0.8404 - val_loss: 0.1283
Epoch 11/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9224 - iou_metric: 0.8577 - loss: 0.1123
Epoch 11: val_dice_coefficient did not improve from 0.91156
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9182 - iou_metric: 0.8507 - loss: 0.1183 - val_dice_coefficient: 0.9101 - val_iou_metric: 0.8378 - val_loss: 0.1340
Epoch 12/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9063 - iou_metric: 0.8330 - loss: 0.1366
Epoch 12: val_dice_coefficient did not improve from 0.91156
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.9087 - iou_metric: 0.8361 - loss: 0.1329 - val_dice_coefficient: 0.9046 - val_iou_metric: 0.8289 - val_loss: 0.1377
Epoch 13/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - dice_coefficient: 0.9196 - iou_metric: 0.8531 - loss: 0.1168
Epoch 13: val_dice_coefficient did not improve from 0.91156
200/200 ━━━━━━━━━━━━━━━━━━━━ 19s 97ms/step - dice_coefficient: 0.9232 - iou_metric: 0.8591 - loss: 0.1117 - val_dice_coefficient: 0.9076 - val_iou_metric: 0.8347 - val_loss: 0.1390
Epoch 14/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.9243 - iou_metric: 0.8610 - loss: 0.1126
Epoch 14: val_dice_coefficient did not improve from 0.91156
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 103ms/step - dice_coefficient: 0.9226 - iou_metric: 0.8580 - loss: 0.1136 - val_dice_coefficient: 0.9075 - val_iou_metric: 0.8340 - val_loss: 0.1352
Epoch 15/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - dice_coefficient: 0.9270 - iou_metric: 0.8656 - loss: 0.1046
Epoch 15: val_dice_coefficient improved from 0.91156 to 0.91934, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 15: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.9282 - iou_metric: 0.8674 - loss: 0.1038 - val_dice_coefficient: 0.9193 - val_iou_metric: 0.8533 - val_loss: 0.1226
Epoch 16/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9330 - iou_metric: 0.8756 - loss: 0.0968
Epoch 16: val_dice_coefficient did not improve from 0.91934
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - dice_coefficient: 0.9319 - iou_metric: 0.8738 - loss: 0.0987 - val_dice_coefficient: 0.9128 - val_iou_metric: 0.8417 - val_loss: 0.1309
Epoch 17/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9347 - iou_metric: 0.8785 - loss: 0.0947
Epoch 17: val_dice_coefficient improved from 0.91934 to 0.91939, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 17: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9355 - iou_metric: 0.8799 - loss: 0.0932 - val_dice_coefficient: 0.9194 - val_iou_metric: 0.8531 - val_loss: 0.1199
Epoch 18/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9404 - iou_metric: 0.8884 - loss: 0.0859
Epoch 18: val_dice_coefficient did not improve from 0.91939
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.9387 - iou_metric: 0.8855 - loss: 0.0888 - val_dice_coefficient: 0.9191 - val_iou_metric: 0.8531 - val_loss: 0.1232
Epoch 19/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.9420 - iou_metric: 0.8912 - loss: 0.0843
Epoch 19: val_dice_coefficient did not improve from 0.91939
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.9400 - iou_metric: 0.8877 - loss: 0.0872 - val_dice_coefficient: 0.9193 - val_iou_metric: 0.8534 - val_loss: 0.1237
Epoch 20/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9408 - iou_metric: 0.8892 - loss: 0.0863
Epoch 20: val_dice_coefficient did not improve from 0.91939
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.9394 - iou_metric: 0.8867 - loss: 0.0882 - val_dice_coefficient: 0.9083 - val_iou_metric: 0.8365 - val_loss: 0.1516
Epoch 21/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9395 - iou_metric: 0.8868 - loss: 0.0887
Epoch 21: val_dice_coefficient improved from 0.91939 to 0.92093, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 21: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.9412 - iou_metric: 0.8897 - loss: 0.0857 - val_dice_coefficient: 0.9209 - val_iou_metric: 0.8562 - val_loss: 0.1201
Epoch 22/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9473 - iou_metric: 0.9004 - loss: 0.0764
Epoch 22: val_dice_coefficient improved from 0.92093 to 0.92498, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 22: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.9491 - iou_metric: 0.9037 - loss: 0.0740 - val_dice_coefficient: 0.9250 - val_iou_metric: 0.8625 - val_loss: 0.1190
Epoch 23/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9531 - iou_metric: 0.9109 - loss: 0.0678
Epoch 23: val_dice_coefficient did not improve from 0.92498
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.9512 - iou_metric: 0.9076 - loss: 0.0707 - val_dice_coefficient: 0.9208 - val_iou_metric: 0.8561 - val_loss: 0.1217
Epoch 24/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9421 - iou_metric: 0.8918 - loss: 0.0868
Epoch 24: val_dice_coefficient did not improve from 0.92498
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.9394 - iou_metric: 0.8871 - loss: 0.0900 - val_dice_coefficient: 0.9190 - val_iou_metric: 0.8524 - val_loss: 0.1270
Epoch 25/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9503 - iou_metric: 0.9060 - loss: 0.0720
Epoch 25: val_dice_coefficient did not improve from 0.92498
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.9526 - iou_metric: 0.9100 - loss: 0.0689 - val_dice_coefficient: 0.9244 - val_iou_metric: 0.8618 - val_loss: 0.1252
Epoch 26/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9588 - iou_metric: 0.9212 - loss: 0.0599
Epoch 26: val_dice_coefficient did not improve from 0.92498
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9574 - iou_metric: 0.9186 - loss: 0.0616 - val_dice_coefficient: 0.9239 - val_iou_metric: 0.8608 - val_loss: 0.1257
Epoch 27/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.9567 - iou_metric: 0.9181 - loss: 0.0627
Epoch 27: val_dice_coefficient improved from 0.92498 to 0.92519, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 27: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.9532 - iou_metric: 0.9118 - loss: 0.0681 - val_dice_coefficient: 0.9252 - val_iou_metric: 0.8631 - val_loss: 0.1198
Epoch 28/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.9604 - iou_metric: 0.9241 - loss: 0.0570
Epoch 28: val_dice_coefficient did not improve from 0.92519
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9614 - iou_metric: 0.9259 - loss: 0.0560 - val_dice_coefficient: 0.9232 - val_iou_metric: 0.8603 - val_loss: 0.1296
Epoch 29/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9645 - iou_metric: 0.9316 - loss: 0.0514
Epoch 29: val_dice_coefficient did not improve from 0.92519
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.9645 - iou_metric: 0.9317 - loss: 0.0514 - val_dice_coefficient: 0.9231 - val_iou_metric: 0.8599 - val_loss: 0.1333
Epoch 30/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - dice_coefficient: 0.9649 - iou_metric: 0.9325 - loss: 0.0502
Epoch 30: val_dice_coefficient improved from 0.92519 to 0.92601, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras

Epoch 30: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.9653 - iou_metric: 0.9332 - loss: 0.0501 - val_dice_coefficient: 0.9260 - val_iou_metric: 0.8650 - val_loss: 0.1327

----------------------------------------------------------------------
LR 1e-3 COMPLETE
Best epoch: 30
Best validation Dice: 0.926008
Validation IoU at best epoch: 0.865032
Training time: 10.24 minutes
Best model: /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras
----------------------------------------------------------------------

{'learning_rate': 0.001,
 'learning_rate_name': '1e-3',
 'parameters': 1940817,
 'epochs_completed': 30,
 'best_epoch': 30,
 'best_val_dice_training': 0.9260080456733704,
 'val_iou_at_best_dice_epoch': 0.8650317192077637,
 'training_minutes': 10.241162570317586,
 'model_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-3_best.keras',
 'history_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/histories/lr_1e-3_history.csv'}

In [ ]:
# ================================================================
# PHASE 1B — CELL 19
# RUN 2: LEARNING RATE = 1e-4
# ================================================================

lr_result_1e4 = train_learning_rate_experiment(
    1e-4
)

lr_result_1e4

======================================================================
TRAINING LEARNING RATE = 1e-4
======================================================================
Epoch 1/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.1832 - iou_metric: 0.1053 - loss: 1.3305
Epoch 1: val_dice_coefficient improved from None to 0.43977, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 1: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 105ms/step - dice_coefficient: 0.2759 - iou_metric: 0.1687 - loss: 1.0598 - val_dice_coefficient: 0.4398 - val_iou_metric: 0.2837 - val_loss: 0.7019
Epoch 2/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.5634 - iou_metric: 0.4030 - loss: 0.6001
Epoch 2: val_dice_coefficient improved from 0.43977 to 0.72617, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 2: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.6321 - iou_metric: 0.4741 - loss: 0.5241 - val_dice_coefficient: 0.7262 - val_iou_metric: 0.5789 - val_loss: 0.3848
Epoch 3/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.7678 - iou_metric: 0.6327 - loss: 0.3399
Epoch 3: val_dice_coefficient improved from 0.72617 to 0.82808, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 3: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.7872 - iou_metric: 0.6583 - loss: 0.3127 - val_dice_coefficient: 0.8281 - val_iou_metric: 0.7120 - val_loss: 0.2496
Epoch 4/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.8277 - iou_metric: 0.7150 - loss: 0.2513
Epoch 4: val_dice_coefficient improved from 0.82808 to 0.85718, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 4: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.8385 - iou_metric: 0.7298 - loss: 0.2369 - val_dice_coefficient: 0.8572 - val_iou_metric: 0.7540 - val_loss: 0.2109
Epoch 5/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8538 - iou_metric: 0.7517 - loss: 0.2142
Epoch 5: val_dice_coefficient did not improve from 0.85718
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.8580 - iou_metric: 0.7582 - loss: 0.2073 - val_dice_coefficient: 0.8531 - val_iou_metric: 0.7501 - val_loss: 0.2182
Epoch 6/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8737 - iou_metric: 0.7806 - loss: 0.1857
Epoch 6: val_dice_coefficient improved from 0.85718 to 0.87612, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 6: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.8739 - iou_metric: 0.7810 - loss: 0.1841 - val_dice_coefficient: 0.8761 - val_iou_metric: 0.7840 - val_loss: 0.1831
Epoch 7/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8827 - iou_metric: 0.7949 - loss: 0.1713
Epoch 7: val_dice_coefficient improved from 0.87612 to 0.88566, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 7: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.8834 - iou_metric: 0.7957 - loss: 0.1706 - val_dice_coefficient: 0.8857 - val_iou_metric: 0.7980 - val_loss: 0.1608
Epoch 8/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - dice_coefficient: 0.8889 - iou_metric: 0.8038 - loss: 0.1603
Epoch 8: val_dice_coefficient improved from 0.88566 to 0.88737, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 8: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 22s 108ms/step - dice_coefficient: 0.8882 - iou_metric: 0.8028 - loss: 0.1626 - val_dice_coefficient: 0.8874 - val_iou_metric: 0.8020 - val_loss: 0.1654
Epoch 9/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - dice_coefficient: 0.8954 - iou_metric: 0.8141 - loss: 0.1512
Epoch 9: val_dice_coefficient improved from 0.88737 to 0.89346, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 9: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 107ms/step - dice_coefficient: 0.8960 - iou_metric: 0.8150 - loss: 0.1511 - val_dice_coefficient: 0.8935 - val_iou_metric: 0.8106 - val_loss: 0.1524
Epoch 10/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.9004 - iou_metric: 0.8217 - loss: 0.1445
Epoch 10: val_dice_coefficient improved from 0.89346 to 0.89723, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 10: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 107ms/step - dice_coefficient: 0.8978 - iou_metric: 0.8179 - loss: 0.1484 - val_dice_coefficient: 0.8972 - val_iou_metric: 0.8171 - val_loss: 0.1512
Epoch 11/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9048 - iou_metric: 0.8287 - loss: 0.1384
Epoch 11: val_dice_coefficient improved from 0.89723 to 0.90108, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 11: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.9031 - iou_metric: 0.8260 - loss: 0.1403 - val_dice_coefficient: 0.9011 - val_iou_metric: 0.8231 - val_loss: 0.1409
Epoch 12/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9100 - iou_metric: 0.8373 - loss: 0.1304
Epoch 12: val_dice_coefficient improved from 0.90108 to 0.90431, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 12: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 206ms/step - dice_coefficient: 0.9070 - iou_metric: 0.8322 - loss: 0.1350 - val_dice_coefficient: 0.9043 - val_iou_metric: 0.8286 - val_loss: 0.1366
Epoch 13/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.9030 - iou_metric: 0.8260 - loss: 0.1399
Epoch 13: val_dice_coefficient did not improve from 0.90431
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 204ms/step - dice_coefficient: 0.9074 - iou_metric: 0.8329 - loss: 0.1343 - val_dice_coefficient: 0.9013 - val_iou_metric: 0.8242 - val_loss: 0.1428
Epoch 14/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9146 - iou_metric: 0.8447 - loss: 0.1244
Epoch 14: val_dice_coefficient improved from 0.90431 to 0.90989, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 14: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 206ms/step - dice_coefficient: 0.9130 - iou_metric: 0.8421 - loss: 0.1259 - val_dice_coefficient: 0.9099 - val_iou_metric: 0.8377 - val_loss: 0.1302
Epoch 15/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.9146 - iou_metric: 0.8448 - loss: 0.1226
Epoch 15: val_dice_coefficient improved from 0.90989 to 0.91237, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 15: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 205ms/step - dice_coefficient: 0.9155 - iou_metric: 0.8462 - loss: 0.1217 - val_dice_coefficient: 0.9124 - val_iou_metric: 0.8417 - val_loss: 0.1272
Epoch 16/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - dice_coefficient: 0.9185 - iou_metric: 0.8510 - loss: 0.1181
Epoch 16: val_dice_coefficient did not improve from 0.91237
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 204ms/step - dice_coefficient: 0.9177 - iou_metric: 0.8498 - loss: 0.1192 - val_dice_coefficient: 0.9044 - val_iou_metric: 0.8280 - val_loss: 0.1374
Epoch 17/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9196 - iou_metric: 0.8529 - loss: 0.1159
Epoch 17: val_dice_coefficient improved from 0.91237 to 0.91342, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 17: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 106ms/step - dice_coefficient: 0.9189 - iou_metric: 0.8518 - loss: 0.1172 - val_dice_coefficient: 0.9134 - val_iou_metric: 0.8431 - val_loss: 0.1261
Epoch 18/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.9251 - iou_metric: 0.8618 - loss: 0.1078
Epoch 18: val_dice_coefficient improved from 0.91342 to 0.91450, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 18: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.9240 - iou_metric: 0.8603 - loss: 0.1098 - val_dice_coefficient: 0.9145 - val_iou_metric: 0.8450 - val_loss: 0.1253
Epoch 19/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9261 - iou_metric: 0.8637 - loss: 0.1069
Epoch 19: val_dice_coefficient improved from 0.91450 to 0.91774, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 19: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.9252 - iou_metric: 0.8622 - loss: 0.1077 - val_dice_coefficient: 0.9177 - val_iou_metric: 0.8504 - val_loss: 0.1210
Epoch 20/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9299 - iou_metric: 0.8702 - loss: 0.1012
Epoch 20: val_dice_coefficient did not improve from 0.91774
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9271 - iou_metric: 0.8656 - loss: 0.1052 - val_dice_coefficient: 0.9080 - val_iou_metric: 0.8352 - val_loss: 0.1394
Epoch 21/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9286 - iou_metric: 0.8681 - loss: 0.1038
Epoch 21: val_dice_coefficient improved from 0.91774 to 0.91926, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 21: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.9296 - iou_metric: 0.8699 - loss: 0.1017 - val_dice_coefficient: 0.9193 - val_iou_metric: 0.8531 - val_loss: 0.1189
Epoch 22/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - dice_coefficient: 0.9303 - iou_metric: 0.8708 - loss: 0.1002
Epoch 22: val_dice_coefficient improved from 0.91926 to 0.92236, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 22: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 106ms/step - dice_coefficient: 0.9320 - iou_metric: 0.8738 - loss: 0.0985 - val_dice_coefficient: 0.9224 - val_iou_metric: 0.8582 - val_loss: 0.1160
Epoch 23/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.9370 - iou_metric: 0.8826 - loss: 0.0910
Epoch 23: val_dice_coefficient did not improve from 0.92236
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.9338 - iou_metric: 0.8772 - loss: 0.0958 - val_dice_coefficient: 0.9202 - val_iou_metric: 0.8542 - val_loss: 0.1161
Epoch 24/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.9382 - iou_metric: 0.8844 - loss: 0.0899
Epoch 24: val_dice_coefficient did not improve from 0.92236
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.9369 - iou_metric: 0.8823 - loss: 0.0912 - val_dice_coefficient: 0.9209 - val_iou_metric: 0.8557 - val_loss: 0.1187
Epoch 25/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9372 - iou_metric: 0.8829 - loss: 0.0909
Epoch 25: val_dice_coefficient did not improve from 0.92236
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.9378 - iou_metric: 0.8839 - loss: 0.0901 - val_dice_coefficient: 0.9148 - val_iou_metric: 0.8452 - val_loss: 0.1278
Epoch 26/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.9403 - iou_metric: 0.8881 - loss: 0.0870
Epoch 26: val_dice_coefficient improved from 0.92236 to 0.92336, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 26: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.9404 - iou_metric: 0.8884 - loss: 0.0861 - val_dice_coefficient: 0.9234 - val_iou_metric: 0.8599 - val_loss: 0.1138
Epoch 27/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.9429 - iou_metric: 0.8928 - loss: 0.0824
Epoch 27: val_dice_coefficient did not improve from 0.92336
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.9418 - iou_metric: 0.8908 - loss: 0.0842 - val_dice_coefficient: 0.9229 - val_iou_metric: 0.8593 - val_loss: 0.1158
Epoch 28/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.9447 - iou_metric: 0.8962 - loss: 0.0790
Epoch 28: val_dice_coefficient improved from 0.92336 to 0.92404, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 28: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.9456 - iou_metric: 0.8974 - loss: 0.0786 - val_dice_coefficient: 0.9240 - val_iou_metric: 0.8610 - val_loss: 0.1145
Epoch 29/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - dice_coefficient: 0.9466 - iou_metric: 0.8994 - loss: 0.0776
Epoch 29: val_dice_coefficient improved from 0.92404 to 0.92497, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 29: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 22s 108ms/step - dice_coefficient: 0.9474 - iou_metric: 0.9007 - loss: 0.0761 - val_dice_coefficient: 0.9250 - val_iou_metric: 0.8632 - val_loss: 0.1172
Epoch 30/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.9500 - iou_metric: 0.9053 - loss: 0.0716
Epoch 30: val_dice_coefficient improved from 0.92497 to 0.92550, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras

Epoch 30: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.9507 - iou_metric: 0.9065 - loss: 0.0713 - val_dice_coefficient: 0.9255 - val_iou_metric: 0.8636 - val_loss: 0.1171

----------------------------------------------------------------------
LR 1e-4 COMPLETE
Best epoch: 30
Best validation Dice: 0.925496
Validation IoU at best epoch: 0.863591
Training time: 12.2 minutes
Best model: /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras
----------------------------------------------------------------------

{'learning_rate': 0.0001,
 'learning_rate_name': '1e-4',
 'parameters': 1940817,
 'epochs_completed': 30,
 'best_epoch': 30,
 'best_val_dice_training': 0.9254956245422363,
 'val_iou_at_best_dice_epoch': 0.8635912537574768,
 'training_minutes': 12.20138973792394,
 'model_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-4_best.keras',
 'history_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/histories/lr_1e-4_history.csv'}

In [ ]:
# ================================================================
# PHASE 1B — CELL 20
# RUN 3: LEARNING RATE = 1e-5
# ================================================================

lr_result_1e5 = train_learning_rate_experiment(
    1e-5
)

lr_result_1e5

======================================================================
TRAINING LEARNING RATE = 1e-5
======================================================================
Epoch 1/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.1527 - iou_metric: 0.0836 - loss: 1.5333
Epoch 1: val_dice_coefficient improved from None to 0.14411, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 1: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 29s 104ms/step - dice_coefficient: 0.1520 - iou_metric: 0.0832 - loss: 1.5304 - val_dice_coefficient: 0.1441 - val_iou_metric: 0.0784 - val_loss: 1.5262
Epoch 2/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.1200 - iou_metric: 0.0646 - loss: 1.4339
Epoch 2: val_dice_coefficient did not improve from 0.14411
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.1053 - iou_metric: 0.0561 - loss: 1.3584 - val_dice_coefficient: 0.1311 - val_iou_metric: 0.0706 - val_loss: 1.1617
Epoch 3/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - dice_coefficient: 0.2452 - iou_metric: 0.1436 - loss: 0.9833
Epoch 3: val_dice_coefficient improved from 0.14411 to 0.39532, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 3: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 98ms/step - dice_coefficient: 0.3184 - iou_metric: 0.1940 - loss: 0.8791 - val_dice_coefficient: 0.3953 - val_iou_metric: 0.2487 - val_loss: 0.7672
Epoch 4/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.4055 - iou_metric: 0.2571 - loss: 0.7665
Epoch 4: val_dice_coefficient improved from 0.39532 to 0.42586, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 4: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 206ms/step - dice_coefficient: 0.4122 - iou_metric: 0.2620 - loss: 0.7589 - val_dice_coefficient: 0.4259 - val_iou_metric: 0.2725 - val_loss: 0.7262
Epoch 5/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.4244 - iou_metric: 0.2717 - loss: 0.7391
Epoch 5: val_dice_coefficient improved from 0.42586 to 0.45702, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 5: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.4365 - iou_metric: 0.2816 - loss: 0.7214 - val_dice_coefficient: 0.4570 - val_iou_metric: 0.2987 - val_loss: 0.6791
Epoch 6/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - dice_coefficient: 0.4658 - iou_metric: 0.3061 - loss: 0.6846
Epoch 6: val_dice_coefficient improved from 0.45702 to 0.57024, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 6: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 102ms/step - dice_coefficient: 0.4817 - iou_metric: 0.3201 - loss: 0.6610 - val_dice_coefficient: 0.5702 - val_iou_metric: 0.4005 - val_loss: 0.5517
Epoch 7/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.6401 - iou_metric: 0.4819 - loss: 0.4922
Epoch 7: val_dice_coefficient improved from 0.57024 to 0.76094, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 7: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.6996 - iou_metric: 0.5486 - loss: 0.4251 - val_dice_coefficient: 0.7609 - val_iou_metric: 0.6199 - val_loss: 0.3374
Epoch 8/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.7460 - iou_metric: 0.6048 - loss: 0.3678
Epoch 8: val_dice_coefficient improved from 0.76094 to 0.78507, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 8: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.7542 - iou_metric: 0.6148 - loss: 0.3580 - val_dice_coefficient: 0.7851 - val_iou_metric: 0.6515 - val_loss: 0.3053
Epoch 9/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.7658 - iou_metric: 0.6301 - loss: 0.3401
Epoch 9: val_dice_coefficient improved from 0.78507 to 0.80336, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 9: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.7736 - iou_metric: 0.6393 - loss: 0.3320 - val_dice_coefficient: 0.8034 - val_iou_metric: 0.6756 - val_loss: 0.2808
Epoch 10/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - dice_coefficient: 0.7804 - iou_metric: 0.6480 - loss: 0.3212
Epoch 10: val_dice_coefficient did not improve from 0.80336
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.7827 - iou_metric: 0.6514 - loss: 0.3196 - val_dice_coefficient: 0.7954 - val_iou_metric: 0.6672 - val_loss: 0.2974
Epoch 11/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.7972 - iou_metric: 0.6701 - loss: 0.2992
Epoch 11: val_dice_coefficient improved from 0.80336 to 0.81277, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 11: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.7928 - iou_metric: 0.6650 - loss: 0.3049 - val_dice_coefficient: 0.8128 - val_iou_metric: 0.6904 - val_loss: 0.2729
Epoch 12/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.7966 - iou_metric: 0.6704 - loss: 0.3003
Epoch 12: val_dice_coefficient improved from 0.81277 to 0.82250, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 12: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 206ms/step - dice_coefficient: 0.7959 - iou_metric: 0.6692 - loss: 0.3015 - val_dice_coefficient: 0.8225 - val_iou_metric: 0.7027 - val_loss: 0.2544
Epoch 13/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.7969 - iou_metric: 0.6706 - loss: 0.2981
Epoch 13: val_dice_coefficient did not improve from 0.82250
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 106ms/step - dice_coefficient: 0.8016 - iou_metric: 0.6772 - loss: 0.2922 - val_dice_coefficient: 0.8100 - val_iou_metric: 0.6867 - val_loss: 0.2757
Epoch 14/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.8072 - iou_metric: 0.6835 - loss: 0.2886
Epoch 14: val_dice_coefficient improved from 0.82250 to 0.83266, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 14: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.8068 - iou_metric: 0.6843 - loss: 0.2838 - val_dice_coefficient: 0.8327 - val_iou_metric: 0.7173 - val_loss: 0.2434
Epoch 15/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8150 - iou_metric: 0.6966 - loss: 0.2711
Epoch 15: val_dice_coefficient did not improve from 0.83266
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.8156 - iou_metric: 0.6966 - loss: 0.2717 - val_dice_coefficient: 0.8309 - val_iou_metric: 0.7144 - val_loss: 0.2443
Epoch 16/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.8167 - iou_metric: 0.6982 - loss: 0.2689
Epoch 16: val_dice_coefficient did not improve from 0.83266
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.8186 - iou_metric: 0.7011 - loss: 0.2671 - val_dice_coefficient: 0.8159 - val_iou_metric: 0.6936 - val_loss: 0.2711
Epoch 17/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - dice_coefficient: 0.8193 - iou_metric: 0.7016 - loss: 0.2656
Epoch 17: val_dice_coefficient improved from 0.83266 to 0.84416, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 17: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.8219 - iou_metric: 0.7054 - loss: 0.2623 - val_dice_coefficient: 0.8442 - val_iou_metric: 0.7343 - val_loss: 0.2254
Epoch 18/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - dice_coefficient: 0.8299 - iou_metric: 0.7160 - loss: 0.2486
Epoch 18: val_dice_coefficient did not improve from 0.84416
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 106ms/step - dice_coefficient: 0.8294 - iou_metric: 0.7160 - loss: 0.2514 - val_dice_coefficient: 0.8366 - val_iou_metric: 0.7249 - val_loss: 0.2402
Epoch 19/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8303 - iou_metric: 0.7178 - loss: 0.2511
Epoch 19: val_dice_coefficient did not improve from 0.84416
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - dice_coefficient: 0.8256 - iou_metric: 0.7116 - loss: 0.2576 - val_dice_coefficient: 0.8428 - val_iou_metric: 0.7319 - val_loss: 0.2282
Epoch 20/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - dice_coefficient: 0.8380 - iou_metric: 0.7275 - loss: 0.2380
Epoch 20: val_dice_coefficient did not improve from 0.84416
200/200 ━━━━━━━━━━━━━━━━━━━━ 41s 207ms/step - dice_coefficient: 0.8357 - iou_metric: 0.7250 - loss: 0.2417 - val_dice_coefficient: 0.8353 - val_iou_metric: 0.7234 - val_loss: 0.2460
Epoch 21/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - dice_coefficient: 0.8306 - iou_metric: 0.7176 - loss: 0.2523
Epoch 21: val_dice_coefficient improved from 0.84416 to 0.84939, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 21: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.8357 - iou_metric: 0.7254 - loss: 0.2422 - val_dice_coefficient: 0.8494 - val_iou_metric: 0.7428 - val_loss: 0.2198
Epoch 22/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.8433 - iou_metric: 0.7350 - loss: 0.2288
Epoch 22: val_dice_coefficient improved from 0.84939 to 0.85530, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 22: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 103ms/step - dice_coefficient: 0.8446 - iou_metric: 0.7379 - loss: 0.2282 - val_dice_coefficient: 0.8553 - val_iou_metric: 0.7517 - val_loss: 0.2130
Epoch 23/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.8447 - iou_metric: 0.7386 - loss: 0.2300
Epoch 23: val_dice_coefficient did not improve from 0.85530
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - dice_coefficient: 0.8459 - iou_metric: 0.7400 - loss: 0.2269 - val_dice_coefficient: 0.8545 - val_iou_metric: 0.7504 - val_loss: 0.2141
Epoch 24/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - dice_coefficient: 0.8521 - iou_metric: 0.7486 - loss: 0.2184
Epoch 24: val_dice_coefficient improved from 0.85530 to 0.85800, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 24: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.8493 - iou_metric: 0.7449 - loss: 0.2218 - val_dice_coefficient: 0.8580 - val_iou_metric: 0.7561 - val_loss: 0.2106
Epoch 25/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.8438 - iou_metric: 0.7368 - loss: 0.2321
Epoch 25: val_dice_coefficient did not improve from 0.85800
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - dice_coefficient: 0.8467 - iou_metric: 0.7410 - loss: 0.2263 - val_dice_coefficient: 0.8473 - val_iou_metric: 0.7391 - val_loss: 0.2261
Epoch 26/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - dice_coefficient: 0.8515 - iou_metric: 0.7474 - loss: 0.2217
Epoch 26: val_dice_coefficient did not improve from 0.85800
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.8538 - iou_metric: 0.7514 - loss: 0.2150 - val_dice_coefficient: 0.8537 - val_iou_metric: 0.7489 - val_loss: 0.2150
Epoch 27/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.8519 - iou_metric: 0.7490 - loss: 0.2177
Epoch 27: val_dice_coefficient did not improve from 0.85800
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 99ms/step - dice_coefficient: 0.8539 - iou_metric: 0.7516 - loss: 0.2149 - val_dice_coefficient: 0.8491 - val_iou_metric: 0.7428 - val_loss: 0.2240
Epoch 28/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.8509 - iou_metric: 0.7478 - loss: 0.2175
Epoch 28: val_dice_coefficient improved from 0.85800 to 0.86239, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 28: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 20s 101ms/step - dice_coefficient: 0.8543 - iou_metric: 0.7523 - loss: 0.2139 - val_dice_coefficient: 0.8624 - val_iou_metric: 0.7617 - val_loss: 0.2004
Epoch 29/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - dice_coefficient: 0.8555 - iou_metric: 0.7537 - loss: 0.2137
Epoch 29: val_dice_coefficient did not improve from 0.86239
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 105ms/step - dice_coefficient: 0.8542 - iou_metric: 0.7521 - loss: 0.2147 - val_dice_coefficient: 0.8595 - val_iou_metric: 0.7584 - val_loss: 0.2086
Epoch 30/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - dice_coefficient: 0.8563 - iou_metric: 0.7545 - loss: 0.2115
Epoch 30: val_dice_coefficient improved from 0.86239 to 0.86884, saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras

Epoch 30: finished saving model to /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
200/200 ━━━━━━━━━━━━━━━━━━━━ 21s 104ms/step - dice_coefficient: 0.8600 - iou_metric: 0.7605 - loss: 0.2049 - val_dice_coefficient: 0.8688 - val_iou_metric: 0.7718 - val_loss: 0.1934

----------------------------------------------------------------------
LR 1e-5 COMPLETE
Best epoch: 30
Best validation Dice: 0.868841
Validation IoU at best epoch: 0.771786
Training time: 11.43 minutes
Best model: /content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras
----------------------------------------------------------------------

{'learning_rate': 1e-05,
 'learning_rate_name': '1e-5',
 'parameters': 1940817,
 'epochs_completed': 30,
 'best_epoch': 30,
 'best_val_dice_training': 0.8688406348228455,
 'val_iou_at_best_dice_epoch': 0.7717862725257874,
 'training_minutes': 11.432759237289428,
 'model_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/models/lr_1e-5_best.keras',
 'history_path': '/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/histories/lr_1e-5_history.csv'}

In [ ]:
# ================================================================
# PHASE 1B — CELL 21
# SAVE LEARNING-RATE TRAINING SUMMARY
# ================================================================

lr_training_summary = pd.DataFrame([
    lr_result_1e3,
    lr_result_1e4,
    lr_result_1e5
])

LR_TRAINING_SUMMARY_PATH = (
    P1B_TABLE_DIR
    / "learning_rate_training_summary.csv"
)

lr_training_summary.to_csv(
    LR_TRAINING_SUMMARY_PATH,
    index=False
)

display(
    lr_training_summary[
        [
            "learning_rate_name",
            "parameters",
            "best_epoch",
            "best_val_dice_training",
            "val_iou_at_best_dice_epoch",
            "training_minutes"
        ]
    ]
)

print("\n✓ Training summary saved:")
print(LR_TRAINING_SUMMARY_PATH)

,learning_rate_name,parameters,best_epoch,best_val_dice_training,val_iou_at_best_dice_epoch,training_minutes
0,1e-3,1940817,30,0.926008,0.865032,10.241163
1,1e-4,1940817,30,0.925496,0.863591,12.201390
2,1e-5,1940817,30,0.868841,0.771786,11.432759

✓ Training summary saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/tables/learning_rate_training_summary.csv

In [ ]:
# ================================================================
# PHASE 1B — CELL 22
# POSTPROCESSING + VALIDATION METRICS
# ================================================================

from scipy.ndimage import binary_fill_holes
from scipy.spatial.distance import cdist


def keep_largest_component(mask):

    mask = np.asarray(mask).astype(np.uint8)

    if mask.sum() == 0:
        return np.zeros_like(mask, dtype=bool)

    n_labels, labels, stats, _ = (
        cv2.connectedComponentsWithStats(
            mask,
            connectivity=8
        )
    )

    if n_labels <= 1:
        return np.zeros_like(mask, dtype=bool)

    largest_label = (
        1 +
        np.argmax(
            stats[1:, cv2.CC_STAT_AREA]
        )
    )

    return labels == largest_label


def postprocess_prediction(mask):

    largest = keep_largest_component(mask)

    filled = binary_fill_holes(
        largest
    )

    return np.asarray(
        filled,
        dtype=bool
    )


def binary_dice(gt, pred):

    gt = np.asarray(gt).astype(bool)
    pred = np.asarray(pred).astype(bool)

    intersection = np.logical_and(
        gt, pred
    ).sum()

    denominator = gt.sum() + pred.sum()

    if denominator == 0:
        return 1.0

    return (
        2.0 * intersection
        / denominator
    )


def binary_iou(gt, pred):

    gt = np.asarray(gt).astype(bool)
    pred = np.asarray(pred).astype(bool)

    intersection = np.logical_and(
        gt, pred
    ).sum()

    union = np.logical_or(
        gt, pred
    ).sum()

    if union == 0:
        return 1.0

    return intersection / union


def binary_precision(gt, pred):

    gt = np.asarray(gt).astype(bool)
    pred = np.asarray(pred).astype(bool)

    tp = np.logical_and(gt, pred).sum()
    fp = np.logical_and(~gt, pred).sum()

    if (tp + fp) == 0:
        return 1.0 if gt.sum() == 0 else 0.0

    return tp / (tp + fp)


def binary_recall(gt, pred):

    gt = np.asarray(gt).astype(bool)
    pred = np.asarray(pred).astype(bool)

    tp = np.logical_and(gt, pred).sum()
    fn = np.logical_and(gt, ~pred).sum()

    if (tp + fn) == 0:
        return 1.0

    return tp / (tp + fn)


def boundary_points(mask):

    mask = np.asarray(mask).astype(np.uint8)

    kernel = np.ones(
        (3, 3),
        dtype=np.uint8
    )

    eroded = cv2.erode(
        mask,
        kernel,
        iterations=1
    )

    boundary = (
        mask.astype(bool)
        &
        ~eroded.astype(bool)
    )

    return np.column_stack(
        np.where(boundary)
    )


def hd95_pixels(gt, pred):

    gt_points = boundary_points(gt)
    pred_points = boundary_points(pred)

    if (
        len(gt_points) == 0
        or len(pred_points) == 0
    ):
        return np.nan

    distances = cdist(
        gt_points,
        pred_points
    )

    gt_to_pred = distances.min(axis=1)
    pred_to_gt = distances.min(axis=0)

    all_distances = np.concatenate([
        gt_to_pred,
        pred_to_gt
    ])

    return float(
        np.percentile(
            all_distances,
            95
        )
    )


print("✓ Postprocessing and evaluation metrics ready.")

✓ Postprocessing and evaluation metrics ready.

In [ ]:
# ================================================================
# PHASE 1B — CELL 23
# CHECKPOINT EVALUATION FUNCTION
# ================================================================

THRESHOLD = 0.50


def evaluate_lr_checkpoint(
    learning_rate
):

    run_name = lr_name(
        learning_rate
    )

    model_path = (
        P1B_MODEL_DIR
        / f"lr_{run_name}_best.keras"
    )

    assert model_path.exists(), (
        f"Checkpoint missing: {model_path}"
    )

    print("\n" + "=" * 70)
    print(
        f"EVALUATING LR = {run_name}"
    )
    print("=" * 70)

    tf.keras.backend.clear_session()
    gc.collect()

    evaluation_model = tf.keras.models.load_model(
        model_path,
        custom_objects={
            "bce_dice_loss": bce_dice_loss,
            "dice_coefficient": dice_coefficient,
            "iou_metric": iou_metric
        }
    )

    records = []

    for patient_number, pid in enumerate(
        val_ids,
        start=1
    ):

        for phase in ["ED", "ES"]:

            image, gt_mask = load_camus_frame(
                pid,
                phase
            )

            x, gt_resized = preprocess_frame(
                image,
                gt_mask,
                SELECTED_RESOLUTION
            )

            probability = evaluation_model(
                x[None, ...],
                training=False
            ).numpy()[0, :, :, 0]

            pred_raw = (
                probability >= THRESHOLD
            )

            pred_mask = postprocess_prediction(
                pred_raw
            )

            gt_binary = (
                gt_resized[:, :, 0] > 0.5
            )

            gt_area = int(
                gt_binary.sum()
            )

            pred_area = int(
                pred_mask.sum()
            )

            if gt_area > 0:

                signed_area_error_pct = (
                    (pred_area - gt_area)
                    / gt_area
                    * 100.0
                )

                abs_area_error_pct = abs(
                    signed_area_error_pct
                )

            else:

                signed_area_error_pct = np.nan
                abs_area_error_pct = np.nan

            hd95 = hd95_pixels(
                gt_binary,
                pred_mask
            )

            records.append({

                "patient_id":
                    pid,

                "phase":
                    phase,

                "learning_rate":
                    learning_rate,

                "learning_rate_name":
                    run_name,

                "dice":
                    binary_dice(
                        gt_binary,
                        pred_mask
                    ),

                "iou":
                    binary_iou(
                        gt_binary,
                        pred_mask
                    ),

                "precision":
                    binary_precision(
                        gt_binary,
                        pred_mask
                    ),

                "recall":
                    binary_recall(
                        gt_binary,
                        pred_mask
                    ),

                "hd95_pixels":
                    hd95,

                "normalized_hd95":
                    (
                        hd95
                        / SELECTED_RESOLUTION
                        if np.isfinite(hd95)
                        else np.nan
                    ),

                "gt_area_pixels":
                    gt_area,

                "pred_area_pixels":
                    pred_area,

                "signed_area_error_pct":
                    signed_area_error_pct,

                "abs_area_error_pct":
                    abs_area_error_pct
            })

            del (
                image,
                gt_mask,
                x,
                gt_resized,
                probability,
                pred_raw,
                pred_mask,
                gt_binary
            )

        if patient_number % 10 == 0:
            print(
                f"Evaluated "
                f"{patient_number}/{len(val_ids)} "
                f"patients"
            )

    results_df = pd.DataFrame(
        records
    )

    output_path = (
        P1B_TABLE_DIR
        / f"lr_{run_name}_validation_metrics.csv"
    )

    results_df.to_csv(
        output_path,
        index=False
    )

    print("\nFrames evaluated:",
          len(results_df))

    print("Saved:")
    print(output_path)

    del evaluation_model

    tf.keras.backend.clear_session()
    gc.collect()

    return results_df

In [ ]:
# ================================================================
# PHASE 1B — CELL 24
# EVALUATE ALL LEARNING RATES
# ================================================================

lr_eval_1e3 = evaluate_lr_checkpoint(
    1e-3
)

lr_eval_1e4 = evaluate_lr_checkpoint(
    1e-4
)

lr_eval_1e5 = evaluate_lr_checkpoint(
    1e-5
)

print("\n✓ All LR checkpoints evaluated.")

======================================================================
EVALUATING LR = 1e-3
======================================================================
Evaluated 10/50 patients
Evaluated 20/50 patients
Evaluated 30/50 patients
Evaluated 40/50 patients
Evaluated 50/50 patients

Frames evaluated: 100
Saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/tables/lr_1e-3_validation_metrics.csv

======================================================================
EVALUATING LR = 1e-4
======================================================================
Evaluated 10/50 patients
Evaluated 20/50 patients
Evaluated 30/50 patients
Evaluated 40/50 patients
Evaluated 50/50 patients

Frames evaluated: 100
Saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/tables/lr_1e-4_validation_metrics.csv

======================================================================
EVALUATING LR = 1e-5
======================================================================
Evaluated 10/50 patients
Evaluated 20/50 patients
Evaluated 30/50 patients
Evaluated 40/50 patients
Evaluated 50/50 patients

Frames evaluated: 100
Saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/tables/lr_1e-5_validation_metrics.csv

✓ All LR checkpoints evaluated.

In [ ]:
# ================================================================
# PHASE 1B — CELL 25
# LEARNING-RATE VALIDATION COMPARISON
# ================================================================

def summarize_lr_results(
    evaluation_df,
    training_result
):

    ed = evaluation_df[
        evaluation_df["phase"] == "ED"
    ]

    es = evaluation_df[
        evaluation_df["phase"] == "ES"
    ]

    return {

        "learning_rate_name":
            training_result[
                "learning_rate_name"
            ],

        "learning_rate":
            training_result[
                "learning_rate"
            ],

        "parameters":
            training_result[
                "parameters"
            ],

        "best_epoch":
            training_result[
                "best_epoch"
            ],

        "training_minutes":
            training_result[
                "training_minutes"
            ],

        "overall_dice":
            evaluation_df["dice"].mean(),

        "ED_dice":
            ed["dice"].mean(),

        "ES_dice":
            es["dice"].mean(),

        "overall_iou":
            evaluation_df["iou"].mean(),

        "precision":
            evaluation_df[
                "precision"
            ].mean(),

        "recall":
            evaluation_df[
                "recall"
            ].mean(),

        "normalized_hd95":
            evaluation_df[
                "normalized_hd95"
            ].mean(),

        "ED_area_MAE_pct":
            ed[
                "abs_area_error_pct"
            ].mean(),

        "ES_area_MAE_pct":
            es[
                "abs_area_error_pct"
            ].mean(),

        "overall_area_MAE_pct":
            evaluation_df[
                "abs_area_error_pct"
            ].mean()
    }


lr_comparison = pd.DataFrame([

    summarize_lr_results(
        lr_eval_1e3,
        lr_result_1e3
    ),

    summarize_lr_results(
        lr_eval_1e4,
        lr_result_1e4
    ),

    summarize_lr_results(
        lr_eval_1e5,
        lr_result_1e5
    )

])


LR_COMPARISON_PATH = (
    P1B_TABLE_DIR
    / "learning_rate_validation_comparison.csv"
)

lr_comparison.to_csv(
    LR_COMPARISON_PATH,
    index=False
)


display(
    lr_comparison.round(4)
)

print("\n✓ Final LR comparison saved:")
print(LR_COMPARISON_PATH)

,learning_rate_name,learning_rate,parameters,best_epoch,training_minutes,overall_dice,ED_dice,ES_dice,overall_iou,precision,recall,normalized_hd95,ED_area_MAE_pct,ES_area_MAE_pct,overall_area_MAE_pct
0,1e-3,0.0010,1940817,30,10.2412,0.9280,0.9374,0.9186,0.8685,0.9253,0.9372,0.0244,7.5395,10.6126,9.0761
1,1e-4,0.0001,1940817,30,12.2014,0.9295,0.9401,0.9188,0.8705,0.9312,0.9334,0.0234,6.4293,10.0577,8.2435
2,1e-5,0.0000,1940817,30,11.4328,0.8828,0.8978,0.8678,0.7943,0.8819,0.8997,0.0397,11.3755,20.3970,15.8862

✓ Final LR comparison saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/tables/learning_rate_validation_comparison.csv

In [ ]:
# ================================================================
# PHASE 1B — CELL 26
# FINALIZE LEARNING-RATE SELECTION
# ================================================================

SELECTED_LEARNING_RATE = 1e-4

selected_row = lr_comparison[
    lr_comparison["learning_rate"] == SELECTED_LEARNING_RATE
].iloc[0]


lr_decision = {

    "experiment":
        "Phase 1B-1 — Controlled Learning Rate Experiment",

    "status":
        "COMPLETED",

    "selected_learning_rate":
        SELECTED_LEARNING_RATE,

    "learning_rates_compared":
        [1e-3, 1e-4, 1e-5],

    "fixed_resolution":
        SELECTED_RESOLUTION,

    "fixed_architecture":
        "Baseline U-Net",

    "parameter_count":
        BASELINE_PARAMETER_COUNT,

    "fixed_optimizer":
        "Adam",

    "fixed_batch_size":
        BATCH_SIZE,

    "fixed_loss":
        "BCE + Dice",

    "augmentation":
        False,

    "epochs":
        MAX_EPOCHS,

    "threshold":
        THRESHOLD,

    "selection_dataset":
        "Validation set only",

    "test_set_used":
        False,

    "selected_validation_results": {

        "overall_dice":
            float(selected_row["overall_dice"]),

        "ED_dice":
            float(selected_row["ED_dice"]),

        "ES_dice":
            float(selected_row["ES_dice"]),

        "overall_iou":
            float(selected_row["overall_iou"]),

        "precision":
            float(selected_row["precision"]),

        "recall":
            float(selected_row["recall"]),

        "normalized_hd95":
            float(selected_row["normalized_hd95"]),

        "ED_area_MAE_pct":
            float(selected_row["ED_area_MAE_pct"]),

        "ES_area_MAE_pct":
            float(selected_row["ES_area_MAE_pct"]),

        "overall_area_MAE_pct":
            float(selected_row["overall_area_MAE_pct"])
    },

    "selection_reason": (
        "Among the tested learning rates, 1e-4 provided the strongest "
        "overall validation performance. It achieved higher overall Dice "
        "and IoU than 1e-3 and 1e-5, while also producing the lowest "
        "normalized HD95 and the lowest ED, ES, and overall LV area MAE. "
        "Because downstream quantitative LV analysis depends on both "
        "segmentation overlap and geometric fidelity, 1e-4 was selected "
        "for subsequent controlled experiments."
    ),

    "next_experiment":
        "Phase 1B-2 — Optimizer Comparison"
}


LR_DECISION_PATH = (
    P1B_CONFIG_DIR
    / "phase1B1_learning_rate_decision.json"
)


with open(
    LR_DECISION_PATH,
    "w"
) as f:

    json.dump(
        lr_decision,
        f,
        indent=2
    )


print("=" * 70)
print("PHASE 1B-1 COMPLETED")
print("=" * 70)

print("\nSelected learning rate:")
print(SELECTED_LEARNING_RATE)

print("\nLocked settings:")
print(f"Resolution     : {SELECTED_RESOLUTION}×{SELECTED_RESOLUTION}")
print(f"Learning rate  : {SELECTED_LEARNING_RATE}")

print("\nSelected validation performance:")
print(
    f"Overall Dice   : {selected_row['overall_dice']:.4f}"
)
print(
    f"ED Dice        : {selected_row['ED_dice']:.4f}"
)
print(
    f"ES Dice        : {selected_row['ES_dice']:.4f}"
)
print(
    f"Overall IoU    : {selected_row['overall_iou']:.4f}"
)
print(
    f"ED Area MAE    : {selected_row['ED_area_MAE_pct']:.2f}%"
)
print(
    f"ES Area MAE    : {selected_row['ES_area_MAE_pct']:.2f}%"
)
print(
    f"Overall Area MAE: {selected_row['overall_area_MAE_pct']:.2f}%"
)

print("\nTest set used: NO")

print("\nNext:")
print("Phase 1B-2 — Optimizer Comparison")

print("\nDecision saved:")
print(LR_DECISION_PATH)

print("\n✓ Learning rate officially locked at 1e-4.")

======================================================================
PHASE 1B-1 COMPLETED
======================================================================

Selected learning rate:
0.0001

Locked settings:
Resolution     : 256×256
Learning rate  : 0.0001

Selected validation performance:
Overall Dice   : 0.9295
ED Dice        : 0.9401
ES Dice        : 0.9188
Overall IoU    : 0.8705
ED Area MAE    : 6.43%
ES Area MAE    : 10.06%
Overall Area MAE: 8.24%

Test set used: NO

Next:
Phase 1B-2 — Optimizer Comparison

Decision saved:
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1B_hyperparameters/configs/phase1B1_learning_rate_decision.json

✓ Learning rate officially locked at 1e-4.