In [ ]:
# ================================================================
# PHASE 5B — CELL 1
# ENVIRONMENT SETUP AND DIRECTORY INITIALIZATION
# ================================================================

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import json
import hashlib
import pickle

import numpy as np
import pandas as pd


# ---------------------------------------------------------------
# PROJECT ROOT
# ---------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/CAMUS_FINAL"
)


# ---------------------------------------------------------------
# PHASE 5B DIRECTORIES
# ---------------------------------------------------------------

PHASE5_DIR = (
    PROJECT_ROOT
    / "phase5_application"
)

PHASE5B_DIR = (
    PHASE5_DIR
    / "phase5B_integrated_pipeline"
)

PHASE5B_CONFIGS_DIR = (
    PHASE5B_DIR
    / "configs"
)

PHASE5B_VERIFICATION_DIR = (
    PHASE5B_DIR
    / "verification"
)

PHASE5B_TABLES_DIR = (
    PHASE5B_DIR
    / "tables"
)


for directory in [
    PHASE5B_DIR,
    PHASE5B_CONFIGS_DIR,
    PHASE5B_VERIFICATION_DIR,
    PHASE5B_TABLES_DIR
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )


assert PROJECT_ROOT.exists()


print("=" * 80)
print("PHASE 5B — INTEGRATED FROZEN INFERENCE PIPELINE")
print("=" * 80)

print("\nPhase 5B directory:")
print(PHASE5B_DIR)

print("\n✓ Phase 5B environment initialized.")

Mounted at /content/drive
================================================================================
PHASE 5B — INTEGRATED FROZEN INFERENCE PIPELINE
================================================================================

Phase 5B directory:
/content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline

✓ Phase 5B environment initialized.

In [ ]:
# ================================================================
# PHASE 5B — CELL 2
# VERIFY PHASE 5A SPECIFICATION FREEZE
# ================================================================

PHASE5A_DIR = (
    PHASE5_DIR
    / "phase5A_system_specification"
)

PHASE5A_COMPLETE_PATH = (
    PHASE5A_DIR
    / "PHASE5A_COMPLETE.json"
)

PHASE5A_FINAL_SPEC_PATH = (
    PHASE5A_DIR
    / "configs"
    / "phase5A_final_system_specification.json"
)


assert PHASE5A_COMPLETE_PATH.exists(), (
    "Phase 5A completion record not found."
)

assert PHASE5A_FINAL_SPEC_PATH.exists(), (
    "Phase 5A final specification not found."
)


with open(
    PHASE5A_COMPLETE_PATH,
    "r"
) as file:

    phase5A_completion = json.load(file)


assert (
    phase5A_completion.get("status")
    == "COMPLETE_AND_FROZEN"
), "Phase 5A is not marked COMPLETE_AND_FROZEN."


print("=" * 80)
print("PHASE 5A SPECIFICATION CHECK")
print("=" * 80)

print(
    "\nStatus:",
    phase5A_completion["status"]
)

print(
    "Specification frozen:",
    phase5A_completion.get(
        "specification_frozen"
    )
)

print(
    "\n✓ Phase 5A specification verified."
)

print(
    "✓ Phase 5B implementation may begin."
)

================================================================================
PHASE 5A SPECIFICATION CHECK
================================================================================

Status: COMPLETE_AND_FROZEN
Specification frozen: True

✓ Phase 5A specification verified.
✓ Phase 5B implementation may begin.

In [ ]:
# ================================================================
# PHASE 5B — CELL 3
# FROZEN UPSTREAM ARTIFACT PATHS
# ================================================================

# ---------------------------------------------------------------
# PHASE 1
# ---------------------------------------------------------------

FROZEN_SEGMENTATION_MODEL_PATH = (
    PROJECT_ROOT
    / "phase1_segmentation"
    / "phase1F_final_model"
    / "models"
    / "final_lv_segmentation_model.keras"
)


# ---------------------------------------------------------------
# PHASE 2
# ---------------------------------------------------------------

PHASE2_FINAL_RECORD_PATH = (
    PROJECT_ROOT
    / "phase2_quantitative"
    / "PHASE2_FINAL_RECORD.json"
)


# ---------------------------------------------------------------
# PHASE 3
# ---------------------------------------------------------------

PHASE3_FINAL_PREDICTIONS_PATH = (
    PROJECT_ROOT
    / "phase3_classification"
    / "phase3D_final_evaluation"
    / "tables"
    / "phase3D_final_patient_predictions.csv"
)


# ---------------------------------------------------------------
# VERIFY
# ---------------------------------------------------------------

frozen_artifacts = {

    "Segmentation model":
        FROZEN_SEGMENTATION_MODEL_PATH,

    "Phase 2 final record":
        PHASE2_FINAL_RECORD_PATH,

    "Phase 3 frozen predictions":
        PHASE3_FINAL_PREDICTIONS_PATH
}


print("=" * 80)
print("FROZEN UPSTREAM ARTIFACT CHECK")
print("=" * 80)


for name, path in frozen_artifacts.items():

    assert path.exists(), (
        f"Missing frozen artifact: {path}"
    )

    print(
        f"\n✓ {name}"
    )

    print(path)


print(
    "\n✓ Required frozen upstream artifacts verified."
)

================================================================================
FROZEN UPSTREAM ARTIFACT CHECK
================================================================================

✓ Segmentation model
/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras

✓ Phase 2 final record
/content/drive/MyDrive/CAMUS_FINAL/phase2_quantitative/PHASE2_FINAL_RECORD.json

✓ Phase 3 frozen predictions
/content/drive/MyDrive/CAMUS_FINAL/phase3_classification/phase3D_final_evaluation/tables/phase3D_final_patient_predictions.csv

✓ Required frozen upstream artifacts verified.

In [ ]:
# ================================================================
# PHASE 5B — CELL 4
# VERIFY FROZEN SEGMENTATION MODEL IDENTITY
# ================================================================

EXPECTED_SEGMENTATION_MODEL_SHA256 = (
    "65ec53959831c6b7c08747a5d94de656"
    "3580ce9ec052aa7b9afa614bee5705d3"
)


def calculate_sha256(file_path):

    sha256_hash = hashlib.sha256()

    with open(file_path, "rb") as file:

        for block in iter(
            lambda: file.read(1024 * 1024),
            b""
        ):
            sha256_hash.update(block)

    return sha256_hash.hexdigest()


actual_segmentation_model_sha256 = (
    calculate_sha256(
        FROZEN_SEGMENTATION_MODEL_PATH
    )
)


print("=" * 80)
print("FROZEN SEGMENTATION MODEL IDENTITY")
print("=" * 80)

print(
    "\nExpected SHA256:"
)

print(
    EXPECTED_SEGMENTATION_MODEL_SHA256
)

print(
    "\nActual SHA256:"
)

print(
    actual_segmentation_model_sha256
)


assert (
    actual_segmentation_model_sha256
    == EXPECTED_SEGMENTATION_MODEL_SHA256
), (
    "Segmentation model SHA256 mismatch. "
    "Do not continue."
)


print(
    "\n✓ Exact frozen Phase 1 segmentation model verified."
)

================================================================================
FROZEN SEGMENTATION MODEL IDENTITY
================================================================================

Expected SHA256:
65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3

Actual SHA256:
65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3

✓ Exact frozen Phase 1 segmentation model verified.

In [ ]:
# ================================================================
# PHASE 5B — CELL 5
# INSPECT FROZEN PHASE 2 QUANTITATIVE RECORD
# ================================================================

with open(
    PHASE2_FINAL_RECORD_PATH,
    "r"
) as file:

    phase2_final_record = json.load(file)


print("=" * 90)
print("PHASE 2 — FROZEN QUANTITATIVE ANALYSIS RECORD")
print("=" * 90)

print(
    json.dumps(
        phase2_final_record,
        indent=4
    )
)

==========================================================================================
PHASE 2 — FROZEN QUANTITATIVE ANALYSIS RECORD
==========================================================================================
{
    "phase": "Phase 2 \u2014 LV Quantitative Analysis",
    "status": "COMPLETE_AND_FROZEN",
    "project_scope": "Assistive, non-diagnostic quantitative analysis of the left ventricle from A4C echocardiography.",
    "dataset": "CAMUS",
    "evaluation_partition": {
        "partition": "test",
        "n_patients": 50,
        "n_frames": 100,
        "ED_frames": 50,
        "ES_frames": 50
    },
    "test_partition_note": "The test partition was excluded from the clean Phase 1A-1D model-selection experiments and from Phase 2A quantitative-method selection. However, because this partition had historical pilot exposure, it is not described as a pristine external test set.",
    "segmentation_pipeline": {
        "model_path": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
        "model_sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
        "input_resolution": "256x256",
        "architecture": "Large U-Net",
        "trainable_parameters": 7759521,
        "threshold": 0.5,
        "postprocessing": [
            "largest connected component",
            "binary hole filling"
        ],
        "status": "FROZEN"
    },
    "quantitative_pipeline": {
        "physical_measurement": "Original NIfTI pixel spacing adjusted separately in x and y for stretch-resize scaling.",
        "LV_area": "binary LV cavity area in mm^2",
        "long_axis_method": "PCA major axis",
        "long_axis_selection_partition": "validation",
        "volume_method": "single-plane A4C area-length",
        "volume_equation": "V = (8/(3*pi)) * A^2/L",
        "EDV": "ED area-length volume in mL",
        "ESV": "ES area-length volume in mL",
        "SV": "EDV - ESV",
        "EF": "(EDV - ESV) / EDV * 100",
        "reference_EF": "CAMUS Info_4CH.cfg EF",
        "status": "FROZEN"
    },
    "sanity_checks": {
        "all_GT_EDV_positive": true,
        "all_GT_ESV_positive": true,
        "all_PRED_EDV_positive": true,
        "all_PRED_ESV_positive": true,
        "GT_EF_within_0_100": true,
        "PRED_EF_within_0_100": true,
        "all_GT_EDV_greater_than_ESV": true,
        "all_PRED_EDV_greater_than_ESV": true,
        "failed_checks": 0
    },
    "segmentation_to_measurement_results": {
        "ED_area": {
            "MAE_mm2": 203.1518,
            "RMSE_mm2": 255.3348,
            "bias_mm2": -146.0928,
            "correlation": 0.9417,
            "relative_MAE_pct": 6.8817,
            "relative_bias_pct": -4.3253
        },
        "ES_area": {
            "MAE_mm2": 179.2046,
            "RMSE_mm2": 236.264,
            "bias_mm2": -112.7997,
            "correlation": 0.9116,
            "relative_MAE_pct": 9.4824,
            "relative_bias_pct": -5.0406
        },
        "ED_length": {
            "MAE_mm": 2.7934,
            "RMSE_mm": 3.8407,
            "bias_mm": -0.9855,
            "correlation": 0.9166,
            "relative_MAE_pct": 3.4233,
            "relative_bias_pct": -1.0651
        },
        "ES_length": {
            "MAE_mm": 3.3978,
            "RMSE_mm": 4.9774,
            "bias_mm": -2.2619,
            "correlation": 0.8589,
            "relative_MAE_pct": 5.1209,
            "relative_bias_pct": -3.2663
        },
        "EDV": {
            "MAE_ml": 11.405,
            "RMSE_ml": 14.6416,
            "bias_ml": -8.2335,
            "correlation": 0.9182,
            "relative_MAE_pct": 11.8762,
            "relative_bias_pct": -7.0275
        },
        "ESV": {
            "MAE_ml": 7.1756,
            "RMSE_ml": 9.5907,
            "bias_ml": -4.1211,
            "correlation": 0.907,
            "relative_MAE_pct": 15.4781,
            "relative_bias_pct": -6.1185
        },
        "SV": {
            "MAE_ml": 7.9325,
            "RMSE_ml": 10.445,
            "bias_ml": -4.1124,
            "correlation": 0.8761
        },
        "EF": {
            "MAE_percentage_points": 5.894,
            "RMSE_percentage_points": 7.5615,
            "bias_percentage_points": 0.1038,
            "correlation": 0.8474
        }
    },
    "EF_error_decomposition": {
        "reference_to_GT_geometry": {
            "interpretation": "Geometry/reference-method disagreement",
            "MAE_pp": 6.6676,
            "RMSE_pp": 9.6954,
            "bias_pp": 4.81,
            "correlation": 0.7994
        },
        "GT_geometry_to_predicted_geometry": {
            "interpretation": "Segmentation-induced downstream disagreement",
            "MAE_pp": 5.894,
            "RMSE_pp": 7.5615,
            "bias_pp": 0.1038,
            "correlation": 0.8474
        },
        "reference_to_predicted_geometry": {
            "interpretation": "Total end-to-end disagreement",
            "MAE_pp": 8.1906,
            "RMSE_pp": 11.0241,
            "bias_pp": 4.9139,
            "correlation": 0.7083
        },
        "important_note": "These error components are not additive because signed errors may interact or partially cancel."
    },
    "bland_altman": {
        "EDV_GT_vs_PRED": {
            "bias_ml": -8.2335,
            "lower_95_LOA_ml": -32.2046,
            "upper_95_LOA_ml": 15.7376
        },
        "ESV_GT_vs_PRED": {
            "bias_ml": -4.1211,
            "lower_95_LOA_ml": -21.2672,
            "upper_95_LOA_ml": 13.0251
        },
        "EF_GT_geometry_vs_PRED": {
            "bias_pp": 0.1038,
            "lower_95_LOA_pp": -14.8657,
            "upper_95_LOA_pp": 15.0734
        },
        "EF_reference_vs_GT_geometry": {
            "bias_pp": 4.81,
            "lower_95_LOA_pp": -11.8571,
            "upper_95_LOA_pp": 21.4771
        },
        "EF_reference_vs_PRED": {
            "bias_pp": 4.9139,
            "lower_95_LOA_pp": -14.6246,
            "upper_95_LOA_pp": 24.4523
        }
    },
    "image_quality_analysis": {
        "Good": {
            "n": 30,
            "GT_to_PRED_EF_MAE_pp": 5.0287,
            "GT_to_PRED_EF_bias_pp": -1.1799,
            "Reference_to_PRED_EF_MAE_pp": 7.3117,
            "Reference_to_PRED_EF_bias_pp": 5.296
        },
        "Medium": {
            "n": 13,
            "GT_to_PRED_EF_MAE_pp": 6.0277,
            "GT_to_PRED_EF_bias_pp": 2.5894,
            "Reference_to_PRED_EF_MAE_pp": 9.7344,
            "Reference_to_PRED_EF_bias_pp": 6.4258
        },
        "Poor": {
            "n": 7,
            "GT_to_PRED_EF_MAE_pp": 9.3545,
            "GT_to_PRED_EF_bias_pp": 0.9895,
            "Reference_to_PRED_EF_MAE_pp": 9.0902,
            "Reference_to_PRED_EF_bias_pp": 0.4682
        },
        "interpretation": "Segmentation-induced EF error increased descriptively from Good to Medium to Poor image quality. The Poor subgroup contained only seven patients, so this analysis is considered descriptive rather than definitive."
    },
    "paired_ED_vs_ES_analysis": {
        "area": {
            "ED_mean_absolute_relative_error_pct": 6.881699,
            "ES_mean_absolute_relative_error_pct": 9.482421,
            "median_paired_ES_minus_ED_difference_pp": 2.324142,
            "ES_error_greater_n": 35,
            "ED_error_greater_n": 15,
            "n": 50,
            "test": "one-sided paired Wilcoxon signed-rank",
            "alternative": "ES absolute relative error > ED absolute relative error",
            "wilcoxon_statistic": 897.0,
            "p_value": 0.005765
        },
        "volume": {
            "EDV_mean_absolute_relative_error_pct": 11.876217,
            "ESV_mean_absolute_relative_error_pct": 15.47809,
            "median_paired_ES_minus_ED_difference_pp": 2.293755,
            "ES_error_greater_n": 31,
            "ED_error_greater_n": 19,
            "n": 50,
            "test": "one-sided paired Wilcoxon signed-rank",
            "alternative": "ESV absolute relative error > EDV absolute relative error",
            "wilcoxon_statistic": 868.0,
            "p_value": 0.01275
        },
        "interpretation": "Within this 50-patient evaluation sample, ES-related area and volume errors were greater than the corresponding ED errors under the predefined paired analysis."
    },
    "failure_case_analysis": {
        "selection": "Three patients with the largest absolute GT-geometry to predicted-geometry EF disagreement.",
        "cases": [
            {
                "patient_id": "patient0358",
                "image_quality": "Poor",
                "reference_EF_pct": 44.0,
                "GT_geometry_EF_pct": 47.5,
                "predicted_EF_pct": 29.4,
                "GT_to_PRED_EF_error_pp": 18.06,
                "ED_area_relative_error_pct": -11.98,
                "ES_area_relative_error_pct": 1.25
            },
            {
                "patient_id": "patient0367",
                "image_quality": "Medium",
                "reference_EF_pct": 62.0,
                "GT_geometry_EF_pct": 65.1,
                "predicted_EF_pct": 47.7,
                "GT_to_PRED_EF_error_pp": 17.42,
                "ED_area_relative_error_pct": -7.66,
                "ES_area_relative_error_pct": 17.45
            },
            {
                "patient_id": "patient0391",
                "image_quality": "Good",
                "reference_EF_pct": 35.0,
                "GT_geometry_EF_pct": 39.9,
                "predicted_EF_pct": 23.5,
                "GT_to_PRED_EF_error_pp": 16.39,
                "ED_area_relative_error_pct": -12.49,
                "ES_area_relative_error_pct": 23.2
            }
        ],
        "observed_pattern": "All three high-error cases showed ED cavity underestimation, while ES was either only slightly different or substantially overestimated. This asymmetric ED/ES error reduced the estimated ED-to-ES volume change and produced substantial EF underestimation.",
        "image_quality_observation": "The three cases included one Good, one Medium, and one Poor quality scan, showing that large downstream errors were not confined to poor-quality images.",
        "interpretation_limit": "These cases were deliberately selected as the largest errors and are not representative samples of the entire evaluation cohort."
    },
    "main_findings": [
        "The frozen segmentation masks enabled extraction of physically scaled LV area, PCA long-axis length, EDV, ESV, SV and EF.",
        "ES measurements were more sensitive to segmentation error than ED measurements.",
        "ES area absolute relative error was 9.48% compared with 6.88% at ED.",
        "ESV absolute relative error was 15.48% compared with 11.88% for EDV.",
        "The paired ED/ES analysis supported greater ES-related error for both area and volume within this evaluation sample.",
        "Predicted masks showed systematic underestimation of LV area and area-length volume on average.",
        "GT-to-predicted EF bias was close to zero despite volume underestimation because ED and ES errors can partially cancel in the EF ratio.",
        "Near-zero mean EF bias did not imply patient-level agreement; GT-to-predicted EF 95% limits of agreement were approximately -14.87 to +15.07 percentage points.",
        "Ground-truth-mask geometry itself differed materially from CAMUS reference EF, indicating that total end-to-end EF disagreement cannot be attributed solely to segmentation.",
        "Failure analysis demonstrated that asymmetric ED/ES segmentation errors can propagate nonlinearly into large EF errors."
    ],
    "limitations": [
        "The volume calculation uses a simplified single-plane A4C area-length approximation.",
        "GT-mask-derived geometric EDV, ESV and EF are internal geometric comparators and are not equivalent to direct clinical ground-truth measurements.",
        "CAMUS Info_4CH.cfg provides reference EF but does not provide corresponding reference EDV and ESV values for direct absolute volume validation.",
        "The Poor image-quality subgroup contains only seven patients.",
        "The final evaluation partition had historical pilot exposure and is therefore not considered a pristine external test set.",
        "CAMUS does not contain longitudinal repeated visits for these patients, so this phase does not validate true longitudinal change tracking."
    ],
    "methodological_integrity": {
        "segmentation_model_changed_after_final_evaluation": false,
        "segmentation_threshold_changed": false,
        "postprocessing_changed": false,
        "geometry_method_changed_after_test": false,
        "bias_correction_applied": false,
        "EF_calibration_applied": false,
        "test_cases_removed": false,
        "post_test_tuning_performed": false
    },
    "phase2_frozen": true,
    "pipeline_changes_allowed": false,
    "next_phase": "Phase 3 \u2014 EF-related classification"
}

In [ ]:
# ================================================================
# PHASE 5B — CELL 6
# INSPECT PHASE 3 FROZEN PREDICTION TABLE
# ================================================================

phase3_frozen_predictions_df = pd.read_csv(
    PHASE3_FINAL_PREDICTIONS_PATH
)


print("=" * 90)
print("PHASE 3 — FROZEN FINAL PREDICTIONS")
print("=" * 90)

print(
    f"\nPatients: {len(phase3_frozen_predictions_df)}"
)

print("\nColumns:")

for column in phase3_frozen_predictions_df.columns:
    print(f"  • {column}")


print("\nFirst 5 rows:")

display(
    phase3_frozen_predictions_df.head()
)


assert len(phase3_frozen_predictions_df) == 50


print(
    "\n✓ Frozen Phase 3 prediction table loaded."
)

==========================================================================================
PHASE 3 — FROZEN FINAL PREDICTIONS
==========================================================================================

Patients: 50

Columns:
  • patient_id
  • reference_EF_pct
  • reference_EF_class
  • PRED_ED_area_mm2
  • PRED_ES_area_mm2
  • PRED_ED_length_mm
  • PRED_ES_length_mm
  • PRED_EDV_ml
  • PRED_ESV_ml
  • PRED_SV_ml
  • PRED_EF_pct
  • learned_prediction
  • correct
  • prob_Higher_EF
  • prob_Intermediate_EF
  • prob_Lower_EF
  • absolute_EF_error_pp

First 5 rows:

,patient_id,reference_EF_pct,reference_EF_class,PRED_ED_area_mm2,PRED_ES_area_mm2,PRED_ED_length_mm,PRED_ES_length_mm,PRED_EDV_ml,PRED_ESV_ml,PRED_SV_ml,PRED_EF_pct,learned_prediction,correct,prob_Higher_EF,prob_Intermediate_EF,prob_Lower_EF,absolute_EF_error_pp
0,patient0004,56.0,Higher_EF,2885.532376,1511.850467,77.877153,59.824512,90.752938,32.430778,58.322160,64.264762,Higher_EF,True,0.805372,0.185380,0.009248,8.264762
1,patient0013,35.0,Lower_EF,2836.311585,2023.798654,90.840418,73.953378,75.170530,47.010562,28.159968,37.461446,Lower_EF,True,0.013721,0.319127,0.667152,2.461446
2,patient0014,50.0,Higher_EF,2092.042272,819.764477,76.068320,44.044877,48.837783,12.950951,35.886833,73.481698,Higher_EF,True,0.931696,0.066975,0.001329,23.481698
3,patient0016,50.0,Higher_EF,2708.549626,1486.667598,74.553165,57.144459,83.526901,32.830121,50.696780,60.695152,Higher_EF,True,0.655681,0.314416,0.029903,10.695152
4,patient0017,58.0,Higher_EF,2088.165464,1239.552437,68.654670,59.090683,53.911149,22.071388,31.839761,59.059696,Higher_EF,True,0.677461,0.298111,0.024428,1.059696

✓ Frozen Phase 3 prediction table loaded.

In [ ]:
# ================================================================
# PHASE 5B — CELL 7
# DISCOVER PHASE 2 AND PHASE 3 IMPLEMENTATION ARTIFACTS
# ================================================================

PHASE2_DIR = (
    PROJECT_ROOT
    / "phase2_quantitative"
)

PHASE3_DIR = (
    PROJECT_ROOT
    / "phase3_classification"
)


def list_project_files(
    root_directory,
    allowed_suffixes=None
):

    records = []

    for path in root_directory.rglob("*"):

        if not path.is_file():
            continue

        if (
            allowed_suffixes is not None
            and path.suffix.lower()
            not in allowed_suffixes
        ):
            continue

        records.append({
            "relative_path":
                str(
                    path.relative_to(
                        PROJECT_ROOT
                    )
                ),

            "suffix":
                path.suffix.lower(),

            "size_kb":
                round(
                    path.stat().st_size / 1024,
                    2
                )
        })

    return pd.DataFrame(records)


artifact_suffixes = {
    ".json",
    ".csv",
    ".pkl",
    ".pickle",
    ".joblib",
    ".keras",
    ".h5",
    ".npz",
    ".npy",
    ".txt"
}


phase2_artifacts_df = list_project_files(
    PHASE2_DIR,
    artifact_suffixes
)

phase3_artifacts_df = list_project_files(
    PHASE3_DIR,
    artifact_suffixes
)


print("=" * 100)
print("PHASE 2 SAVED ARTIFACTS")
print("=" * 100)

display(
    phase2_artifacts_df
)


print("\n" + "=" * 100)
print("PHASE 3 SAVED ARTIFACTS")
print("=" * 100)

display(
    phase3_artifacts_df
)


print(
    f"\nPhase 2 files found: "
    f"{len(phase2_artifacts_df)}"
)

print(
    f"Phase 3 files found: "
    f"{len(phase3_artifacts_df)}"
)

====================================================================================================
PHASE 2 SAVED ARTIFACTS
====================================================================================================

                                        relative_path suffix  size_kb
0        phase2_quantitative/PHASE2_FINAL_RECORD.json  .json    11.14
1            phase2_quantitative/PHASE2_COMPLETE.json  .json     0.67
2   phase2_quantitative/phase2B_final_evaluation/c...  .json     1.45
3   phase2_quantitative/phase2B_final_evaluation/c...  .json     5.25
4   phase2_quantitative/phase2B_final_evaluation/c...  .json     2.07
5   phase2_quantitative/phase2B_final_evaluation/t...   .csv    15.89
6   phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.74
7   phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.49
8   phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.58
9   phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.52
10  phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.52
11  phase2_quantitative/phase2B_final_evaluation/t...   .csv    21.58
12  phase2_quantitative/phase2B_final_evaluation/t...   .csv     1.28
13  phase2_quantitative/phase2B_final_evaluation/t...   .csv     1.29
14  phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.25
15  phase2_quantitative/phase2B_final_evaluation/t...   .csv     0.45
16  phase2_quantitative/phase2A_measurement_method...  .json     1.45
17  phase2_quantitative/phase2A_measurement_method...  .json     1.50
18  phase2_quantitative/phase2A_measurement_method...  .json     2.51
19  phase2_quantitative/phase2A_measurement_method...   .csv    13.23
20  phase2_quantitative/phase2A_measurement_method...   .csv    14.03
21  phase2_quantitative/phase2A_measurement_method...   .csv     0.29
22  phase2_quantitative/phase2A_measurement_method...   .csv     5.49
23  phase2_quantitative/phase2A_measurement_method...   .csv    15.65
24  phase2_quantitative/phase2A_measurement_method...   .csv     0.71
25  phase2_quantitative/phase2A_measurement_method...   .csv     0.48

====================================================================================================
PHASE 3 SAVED ARTIFACTS
====================================================================================================

                                        relative_path   suffix  size_kb
0   phase3_classification/phase3C_classifier_devel...    .json     2.04
1   phase3_classification/phase3C_classifier_devel...    .json     3.83
2   phase3_classification/phase3C_classifier_devel...     .csv    69.62
3   phase3_classification/phase3C_classifier_devel...     .csv    79.81
4   phase3_classification/phase3C_classifier_devel...     .csv     0.38
5   phase3_classification/phase3C_classifier_devel...     .csv     0.19
6   phase3_classification/phase3C_classifier_devel...     .csv     2.26
7   phase3_classification/phase3C_classifier_devel...  .joblib     1.91
8   phase3_classification/phase3D_final_evaluation...    .json     3.23
9   phase3_classification/phase3D_final_evaluation...     .csv     0.20
10  phase3_classification/phase3D_final_evaluation...     .csv     0.12
11  phase3_classification/phase3D_final_evaluation...     .csv     0.34
12  phase3_classification/phase3D_final_evaluation...     .csv    13.32
13  phase3_classification/phase3D_final_evaluation...     .csv     4.68
14  phase3_classification/phase3D_final_evaluation...     .csv     0.16
15  phase3_classification/phase3B_direct_baseline/...    .json     5.81
16  phase3_classification/phase3B_direct_baseline/...     .csv     2.19
17  phase3_classification/phase3B_direct_baseline/...     .csv     2.01
18  phase3_classification/phase3B_direct_baseline/...     .csv     0.15
19  phase3_classification/phase3B_direct_baseline/...     .csv     0.20
20  phase3_classification/phase3B_direct_baseline/...     .csv     0.15
21  phase3_classification/phase3B_direct_baseline/...     .csv    26.56
22  phase3_classification/phase3B_direct_baseline/...     .csv     0.27
23  phase3_classification/phase3A_label_audit/conf...    .json     1.65
24  phase3_classification/phase3A_label_audit/tabl...     .csv     0.10
25  phase3_classification/phase3A_label_audit/tabl...     .csv     0.08
26  phase3_classification/phase3A_label_audit/tabl...     .csv     0.18
27  phase3_classification/phase3A_label_audit/tabl...     .csv    22.33

Phase 2 files found: 26
Phase 3 files found: 28

In [ ]:
# ================================================================
# PHASE 5B — CELL 8
# IDENTIFY LIKELY PIPELINE IMPLEMENTATION ARTIFACTS
# ================================================================

search_terms = [

    # Phase 2
    "pca",
    "measurement",
    "geometry",
    "method",
    "config",
    "final",

    # Phase 3
    "classifier",
    "logistic",
    "scaler",
    "pipeline",
    "model",
    "feature",
    "selected"
]


all_upstream_artifacts_df = pd.concat(
    [
        phase2_artifacts_df.assign(
            phase="Phase 2"
        ),

        phase3_artifacts_df.assign(
            phase="Phase 3"
        )
    ],
    ignore_index=True
)


search_pattern = "|".join(
    search_terms
)


likely_artifacts_df = (
    all_upstream_artifacts_df[
        all_upstream_artifacts_df[
            "relative_path"
        ]
        .str.lower()
        .str.contains(
            search_pattern,
            regex=True
        )
    ]
    .sort_values(
        [
            "phase",
            "relative_path"
        ]
    )
    .reset_index(
        drop=True
    )
)


print("=" * 100)
print("LIKELY PHASE 5B INTEGRATION ARTIFACTS")
print("=" * 100)


if len(likely_artifacts_df) == 0:

    print(
        "\nNo likely implementation artifacts "
        "were automatically identified."
    )

else:

    display(
        likely_artifacts_df
    )


print(
    f"\nLikely artifacts found: "
    f"{len(likely_artifacts_df)}"
)

====================================================================================================
LIKELY PHASE 5B INTEGRATION ARTIFACTS
====================================================================================================

,relative_path,suffix,size_kb,phase
0,phase2_quantitative/PHASE2_FINAL_RECORD.json,.json,11.14,Phase 2
1,phase2_quantitative/phase2A_measurement_method...,.json,2.51,Phase 2
2,phase2_quantitative/phase2A_measurement_method...,.json,1.50,Phase 2
3,phase2_quantitative/phase2A_measurement_method...,.json,1.45,Phase 2
4,phase2_quantitative/phase2A_measurement_method...,.csv,13.23,Phase 2
5,phase2_quantitative/phase2A_measurement_method...,.csv,0.48,Phase 2
6,phase2_quantitative/phase2A_measurement_method...,.csv,0.29,Phase 2
7,phase2_quantitative/phase2A_measurement_method...,.csv,5.49,Phase 2
8,phase2_quantitative/phase2A_measurement_method...,.csv,14.03,Phase 2
9,phase2_quantitative/phase2A_measurement_method...,.csv,15.65,Phase 2
10,phase2_quantitative/phase2A_measurement_method...,.csv,0.71,Phase 2
11,phase2_quantitative/phase2B_final_evaluation/c...,.json,2.07,Phase 2
12,phase2_quantitative/phase2B_final_evaluation/c...,.json,5.25,Phase 2
13,phase2_quantitative/phase2B_final_evaluation/c...,.json,1.45,Phase 2
14,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.45,Phase 2
15,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.25,Phase 2
16,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.49,Phase 2
17,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.52,Phase 2
18,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.52,Phase 2
19,phase2_quantitative/phase2B_final_evaluation/t...,.csv,21.58,Phase 2
20,phase2_quantitative/phase2B_final_evaluation/t...,.csv,15.89,Phase 2
21,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.58,Phase 2
22,phase2_quantitative/phase2B_final_evaluation/t...,.csv,0.74,Phase 2
23,phase2_quantitative/phase2B_final_evaluation/t...,.csv,1.29,Phase 2
24,phase2_quantitative/phase2B_final_evaluation/t...,.csv,1.28,Phase 2
25,phase3_classification/phase3A_label_audit/conf...,.json,1.65,Phase 3
26,phase3_classification/phase3B_direct_baseline/...,.json,5.81,Phase 3
27,phase3_classification/phase3C_classifier_devel...,.json,3.83,Phase 3
28,phase3_classification/phase3C_classifier_devel...,.json,2.04,Phase 3
29,phase3_classification/phase3C_classifier_devel...,.joblib,1.91,Phase 3
30,phase3_classification/phase3C_classifier_devel...,.csv,69.62,Phase 3
31,phase3_classification/phase3C_classifier_devel...,.csv,79.81,Phase 3
32,phase3_classification/phase3C_classifier_devel...,.csv,0.19,Phase 3
33,phase3_classification/phase3C_classifier_devel...,.csv,2.26,Phase 3
34,phase3_classification/phase3C_classifier_devel...,.csv,0.38,Phase 3
35,phase3_classification/phase3D_final_evaluation...,.json,3.23,Phase 3
36,phase3_classification/phase3D_final_evaluation...,.csv,0.34,Phase 3
37,phase3_classification/phase3D_final_evaluation...,.csv,0.16,Phase 3
38,phase3_classification/phase3D_final_evaluation...,.csv,0.12,Phase 3
39,phase3_classification/phase3D_final_evaluation...,.csv,4.68,Phase 3
40,phase3_classification/phase3D_final_evaluation...,.csv,13.32,Phase 3
41,phase3_classification/phase3D_final_evaluation...,.csv,0.20,Phase 3

Likely artifacts found: 42

In [ ]:
# ================================================================
# PHASE 5B — CELL 9
# PRINT EXACT PHASE 2 / PHASE 3 ARTIFACT PATHS
# ================================================================

print("=" * 100)
print("PHASE 2 — EXACT JSON ARTIFACT PATHS")
print("=" * 100)

phase2_json_paths = sorted(
    [
        path
        for path in PHASE2_DIR.rglob("*.json")
        if path.is_file()
    ]
)

for path in phase2_json_paths:
    print(
        path.relative_to(PROJECT_ROOT)
    )


print("\n" + "=" * 100)
print("PHASE 3 — EXACT MODEL / CONFIG ARTIFACT PATHS")
print("=" * 100)

phase3_relevant_suffixes = {
    ".json",
    ".joblib",
    ".pkl",
    ".pickle"
}

phase3_model_config_paths = sorted(
    [
        path
        for path in PHASE3_DIR.rglob("*")
        if (
            path.is_file()
            and path.suffix.lower()
            in phase3_relevant_suffixes
        )
    ]
)

for path in phase3_model_config_paths:
    print(
        path.relative_to(PROJECT_ROOT)
    )


print(
    "\n✓ Exact artifact paths displayed."
)

====================================================================================================
PHASE 2 — EXACT JSON ARTIFACT PATHS
====================================================================================================
phase2_quantitative/PHASE2_COMPLETE.json
phase2_quantitative/PHASE2_FINAL_RECORD.json
phase2_quantitative/phase2A_measurement_method/configs/phase2A_development_record.json
phase2_quantitative/phase2A_measurement_method/configs/phase2A_geometry_method_decision.json
phase2_quantitative/phase2A_measurement_method/configs/phase2A_measurement_protocol.json
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_failure_analysis_record.json
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_final_evaluation_record.json
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_locked_evaluation_protocol.json

====================================================================================================
PHASE 3 — EXACT MODEL / CONFIG ARTIFACT PATHS
====================================================================================================
phase3_classification/phase3A_label_audit/configs/phase3A_classification_target_decision.json
phase3_classification/phase3B_direct_baseline/configs/phase3B_direct_baseline_record.json
phase3_classification/phase3C_classifier_development/configs/phase3C_development_record.json
phase3_classification/phase3C_classifier_development/configs/phase3C_predefined_protocol.json
phase3_classification/phase3C_classifier_development/models/phase3C_selected_logistic_regression.joblib
phase3_classification/phase3D_final_evaluation/configs/phase3D_final_evaluation_record.json

✓ Exact artifact paths displayed.

In [ ]:
# ================================================================
# PHASE 5B — CELL 10
# INSPECT PHASE 2 CONFIGURATION RECORDS
# ================================================================

print("=" * 100)
print("PHASE 2 CONFIGURATION RECORDS")
print("=" * 100)


for path in phase2_json_paths:

    # Skip the large overall record because we already inspected it
    if path == PHASE2_FINAL_RECORD_PATH:
        continue

    print("\n")
    print("-" * 100)

    print(
        path.relative_to(PROJECT_ROOT)
    )

    print("-" * 100)

    try:

        with open(
            path,
            "r"
        ) as file:

            content = json.load(file)

        print(
            json.dumps(
                content,
                indent=4
            )
        )

    except Exception as error:

        print(
            f"Could not read JSON: {error}"
        )

====================================================================================================
PHASE 2 CONFIGURATION RECORDS
====================================================================================================


----------------------------------------------------------------------------------------------------
phase2_quantitative/PHASE2_COMPLETE.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 2 \u2014 LV Quantitative Analysis",
    "status": "COMPLETE",
    "phase2A": "Quantitative measurement methodology developed and selected using validation data.",
    "phase2B": "Locked final quantitative evaluation completed on 50 patients.",
    "final_pipeline": "A4C image \u2192 frozen LV segmentation \u2192 physical LV area \u2192 PCA long-axis \u2192 single-plane area-length EDV/ESV \u2192 SV \u2192 EF",
    "segmentation_model_frozen": true,
    "quantitative_method_frozen": true,
    "post_test_tuning": false,
    "final_record": "/content/drive/MyDrive/CAMUS_FINAL/phase2_quantitative/PHASE2_FINAL_RECORD.json",
    "next_phase": "Phase 3 \u2014 EF-related classification"
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/configs/phase2A_development_record.json
----------------------------------------------------------------------------------------------------
{
    "status": "DEVELOPMENT_COMPLETE_AND_FROZEN",
    "selection_partition": "validation",
    "selection_n_patients": 50,
    "segmentation_model": {
        "status": "FROZEN_FROM_PHASE1F",
        "path": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
        "sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
        "threshold": 0.5,
        "postprocessing": [
            "largest connected component",
            "binary hole filling"
        ]
    },
    "measurement_pipeline": {
        "resize": "256x256 stretch resize",
        "physical_spacing": "Original NIfTI spacing adjusted independently for x and y according to resize scale factors.",
        "area": "binary LV cavity area in mm^2",
        "long_axis": "PCA major axis",
        "volume": "single-plane area-length",
        "volume_equation": "V = (8/(3*pi)) * A^2/L",
        "EDV": "ED single-plane area-length volume",
        "ESV": "ES single-plane area-length volume",
        "SV": "EDV - ESV",
        "EF": "(EDV - ESV)/EDV * 100"
    },
    "geometry_method_selection": {
        "candidates": [
            "Maximum Feret",
            "PCA major axis"
        ],
        "selected": "PCA major axis",
        "PCA_validation_EF_MAE_pp": 8.1604,
        "Feret_validation_EF_MAE_pp": 8.2922,
        "PCA_lower_error_patients": 31,
        "Feret_lower_error_patients": 19,
        "note": "PCA showed only a small advantage. The selection applies to this predefined two-method comparison."
    },
    "validation_error_decomposition": {
        "reference_to_GT_geometry": {
            "EF_MAE_pp": 8.1076,
            "EF_RMSE_pp": 9.3858,
            "EF_bias_pp": 5.7688,
            "correlation": 0.8488
        },
        "GT_geometry_to_predicted_geometry": {
            "EF_MAE_pp": 7.0468,
            "EF_RMSE_pp": 9.5155,
            "EF_bias_pp": -2.1015,
            "correlation": 0.774
        },
        "reference_to_predicted_geometry": {
            "EF_MAE_pp": 8.7448,
            "EF_RMSE_pp": 11.13,
            "EF_bias_pp": 3.6672,
            "correlation": 0.6944
        }
    },
    "interpretation": {
        "geometry_component": "Substantial EF disagreement remains even when ground-truth LV masks are used, showing that single-plane geometric estimation/reference differences contribute independently of segmentation.",
        "segmentation_component": "Predicted masks introduce additional error into area, length, volume and EF measurements.",
        "error_additivity": "Error components must not be treated as directly additive because signed errors can interact and partially cancel."
    },
    "frozen_before_test_quantitative_evaluation": true,
    "test_results_may_change_pipeline": false
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/configs/phase2A_geometry_method_decision.json
----------------------------------------------------------------------------------------------------
{
    "status": "FROZEN",
    "selection_partition": "validation",
    "selection_n_patients": 50,
    "selected_long_axis_method": "PCA_major_axis",
    "alternative_method": "maximum_feret",
    "selected_volume_method": "single-plane area-length",
    "volume_equation": "V = (8 / (3*pi)) * (A^2 / L)",
    "selection_reference": "CAMUS Info_4CH.cfg EF",
    "validation_results": {
        "PCA": {
            "EF_MAE_pp": 8.1604,
            "EF_RMSE_pp": 9.4344,
            "EF_bias_pp": 5.8053,
            "EF_correlation": 0.8475,
            "patients_lower_absolute_error": 31
        },
        "Maximum_Feret": {
            "EF_MAE_pp": 8.2922,
            "EF_RMSE_pp": 9.5364,
            "EF_bias_pp": 6.0454,
            "EF_correlation": 0.8512,
            "patients_lower_absolute_error": 19
        }
    },
    "mean_pca_minus_feret_absolute_EF_error_pp": -0.1318,
    "decision": "PCA major-axis length selected because it produced slightly lower validation EF MAE, RMSE and bias, and lower patient-level absolute EF error in 31 of 50 validation patients.",
    "interpretation_limitation": "The difference between PCA and Maximum Feret was small. Selection applies only to the two tested long-axis definitions under this single-plane A4C area-length measurement protocol.",
    "important_observation": "Even with ground-truth masks, PCA-derived single-plane EF showed positive disagreement relative to CAMUS reference EF. Therefore downstream EF disagreement cannot be attributed solely to segmentation error.",
    "test_data_used_for_method_selection": false,
    "method_changes_after_test_evaluation_allowed": false
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/configs/phase2A_measurement_protocol.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 2A \u2014 LV Quantitative Measurement Method",
    "purpose": "Establish and validate the quantitative measurement methodology used downstream of the frozen LV segmentation model.",
    "segmentation_model_frozen": true,
    "segmentation_model": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
    "segmentation_model_sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
    "segmentation_changes_allowed": false,
    "target_view": "A4C",
    "target_structure": "LV cavity",
    "phases": [
        "ED",
        "ES"
    ],
    "physical_units": {
        "area": "mm^2",
        "length": "mm",
        "volume": "mL",
        "EF": "%"
    },
    "candidate_long_axis_methods": [
        "maximum_feret",
        "PCA_major_axis"
    ],
    "volume_method": "single-plane area-length",
    "volume_equation": "V = (8 / (3*pi)) * (A^2 / L)",
    "method_selection_principle": "Geometry methods will first be evaluated using ground-truth LV masks so that measurement-model error is separated from segmentation error.",
    "downstream_quantities": [
        "ED area",
        "ES area",
        "ED long-axis length",
        "ES long-axis length",
        "EDV",
        "ESV",
        "SV",
        "EF"
    ],
    "test_exposure_note": "The current 50-patient evaluation partition was previously inspected during historical pilot development. It was excluded from the clean Phase 1A-1D model-selection process, but is not claimed to be a pristine external test set."
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_failure_analysis_record.json
----------------------------------------------------------------------------------------------------
{
    "analysis_type": "Locked-test qualitative failure analysis",
    "selection_rule": "Three patients with the largest absolute GT-geometry to predicted-geometry EF error.",
    "n_cases": 3,
    "cases": [
        {
            "patient_id": "patient0358",
            "image_quality": "Poor",
            "reference_EF_pct": 44.0,
            "GT_geometry_EF_pct": 47.49137979205981,
            "predicted_EF_pct": 29.435974828677114,
            "GT_to_PRED_EF_abs_error_pp": 18.055404963382696,
            "ED_area_relative_error_pct": -11.982419616007409,
            "ES_area_relative_error_pct": 1.2525389302640377
        },
        {
            "patient_id": "patient0367",
            "image_quality": "Medium",
            "reference_EF_pct": 62.0,
            "GT_geometry_EF_pct": 65.10591701476162,
            "predicted_EF_pct": 47.68184905915036,
            "GT_to_PRED_EF_abs_error_pp": 17.424067955611257,
            "ED_area_relative_error_pct": -7.664041994750649,
            "ES_area_relative_error_pct": 17.45029977911015
        },
        {
            "patient_id": "patient0391",
            "image_quality": "Good",
            "reference_EF_pct": 35.0,
            "GT_geometry_EF_pct": 39.86842539327857,
            "predicted_EF_pct": 23.478531104926773,
            "GT_to_PRED_EF_abs_error_pp": 16.389894288351798,
            "ED_area_relative_error_pct": 12.489745693191143,
            "ES_area_relative_error_pct": 23.198259450639107
        }
    ],
    "observed_pattern": "The three largest segmentation-induced EF errors showed asymmetric ED/ES segmentation errors. ED cavity area was underestimated in all three cases, while ES area was either only slightly different or substantially overestimated. This reduced the estimated ED-to-ES volume change and resulted in substantial underestimation of EF.",
    "image_quality_observation": "The three cases included Good, Medium, and Poor image quality labels. Therefore, large downstream errors were not confined to a single image-quality category.",
    "interpretation_limit": "These cases were selected because they had the largest errors and are used for qualitative failure analysis. They should not be interpreted as representative of all test patients.",
    "pipeline_modified_after_analysis": false
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_final_evaluation_record.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 2B \u2014 Final Quantitative Evaluation",
    "status": "COMPLETE_AND_FROZEN",
    "evaluation_partition": {
        "name": "test",
        "patients": 50,
        "frames": 100,
        "ED_frames": 50,
        "ES_frames": 50
    },
    "test_partition_note": "This partition was excluded from the clean Phase 1A-1D model-selection process and Phase 2A geometry-method selection. However, because it had historical pilot exposure, it is not described as a pristine external test set.",
    "segmentation_pipeline": {
        "model": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
        "sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
        "resolution": "256x256",
        "threshold": 0.5,
        "postprocessing": "largest connected component + hole filling",
        "status": "frozen before Phase 2B"
    },
    "quantitative_pipeline": {
        "LV_area": "physical mask area using adjusted NIfTI pixel spacing",
        "long_axis": "PCA major axis",
        "volume": "single-plane A4C area-length",
        "equation": "V = (8/(3*pi)) * A^2/L",
        "EDV": "ED area-length volume",
        "ESV": "ES area-length volume",
        "SV": "EDV - ESV",
        "EF": "(EDV - ESV) / EDV * 100",
        "reference_EF": "CAMUS Info_4CH.cfg EF"
    },
    "sanity_checks": {
        "all_passed": true,
        "failed_checks": 0
    },
    "segmentation_to_measurement_error": {
        "ED_area": {
            "MAE_mm2": 203.1518,
            "relative_MAE_pct": 6.8817,
            "relative_bias_pct": -4.3253,
            "correlation": 0.9417
        },
        "ES_area": {
            "MAE_mm2": 179.2046,
            "relative_MAE_pct": 9.4824,
            "relative_bias_pct": -5.0406,
            "correlation": 0.9116
        },
        "ED_length": {
            "MAE_mm": 2.7934,
            "relative_MAE_pct": 3.4233,
            "correlation": 0.9166
        },
        "ES_length": {
            "MAE_mm": 3.3978,
            "relative_MAE_pct": 5.1209,
            "correlation": 0.8589
        },
        "EDV": {
            "MAE_ml": 11.405,
            "relative_MAE_pct": 11.8762,
            "bias_ml": -8.2335,
            "relative_bias_pct": -7.0275,
            "correlation": 0.9182
        },
        "ESV": {
            "MAE_ml": 7.1756,
            "relative_MAE_pct": 15.4781,
            "bias_ml": -4.1211,
            "relative_bias_pct": -6.1185,
            "correlation": 0.907
        },
        "SV": {
            "MAE_ml": 7.9325,
            "RMSE_ml": 10.445,
            "bias_ml": -4.1124,
            "correlation": 0.8761
        },
        "EF": {
            "MAE_percentage_points": 5.894,
            "RMSE_percentage_points": 7.5615,
            "bias_percentage_points": 0.1038,
            "correlation": 0.8474
        }
    },
    "EF_error_decomposition": {
        "reference_to_GT_geometry": {
            "interpretation": "geometry/reference disagreement",
            "MAE_pp": 6.6676,
            "RMSE_pp": 9.6954,
            "bias_pp": 4.81,
            "correlation": 0.7994
        },
        "GT_geometry_to_predicted_geometry": {
            "interpretation": "segmentation-induced downstream disagreement",
            "MAE_pp": 5.894,
            "RMSE_pp": 7.5615,
            "bias_pp": 0.1038,
            "correlation": 0.8474
        },
        "reference_to_predicted_geometry": {
            "interpretation": "total end-to-end disagreement",
            "MAE_pp": 8.1906,
            "RMSE_pp": 11.0241,
            "bias_pp": 4.9139,
            "correlation": 0.7083
        }
    },
    "bland_altman": {
        "EDV_GT_vs_PRED": {
            "bias_ml": -8.2335,
            "lower_95_LOA_ml": -32.2046,
            "upper_95_LOA_ml": 15.7376
        },
        "ESV_GT_vs_PRED": {
            "bias_ml": -4.1211,
            "lower_95_LOA_ml": -21.2672,
            "upper_95_LOA_ml": 13.0251
        },
        "EF_GT_vs_PRED": {
            "bias_pp": 0.1038,
            "lower_95_LOA_pp": -14.8657,
            "upper_95_LOA_pp": 15.0734
        },
        "EF_reference_vs_PRED": {
            "bias_pp": 4.9139,
            "lower_95_LOA_pp": -14.6246,
            "upper_95_LOA_pp": 24.4523
        }
    },
    "image_quality_subgroups": {
        "Good": {
            "n": 30,
            "GT_to_PRED_EF_MAE_pp": 5.0287,
            "Reference_to_PRED_EF_MAE_pp": 7.3117
        },
        "Medium": {
            "n": 13,
            "GT_to_PRED_EF_MAE_pp": 6.0277,
            "Reference_to_PRED_EF_MAE_pp": 9.7344
        },
        "Poor": {
            "n": 7,
            "GT_to_PRED_EF_MAE_pp": 9.3545,
            "Reference_to_PRED_EF_MAE_pp": 9.0902
        }
    },
    "main_findings": [
        "ES measurements were less accurate than ED measurements in relative terms.",
        "Predicted masks systematically underestimated LV area and area-length volumes.",
        "Despite volume underestimation, GT-to-predicted EF bias was close to zero because ED and ES errors can partially cancel in the EF ratio.",
        "Ground-truth-mask geometry itself differed substantially from CAMUS reference EF, demonstrating that downstream EF disagreement cannot be attributed solely to segmentation.",
        "Poor-quality images showed higher segmentation-induced EF error descriptively, but the Poor subgroup contained only seven patients."
    ],
    "limitations": [
        "The area-length calculation is a simplified single-plane A4C geometric estimate.",
        "GT-mask-derived geometric EF is not equivalent to clinical reference EF.",
        "The Poor image-quality subgroup is small.",
        "CAMUS does not provide longitudinal repeated visits, so these results do not validate longitudinal change tracking.",
        "The evaluation partition had historical pilot exposure and is therefore not claimed as a pristine external test set."
    ],
    "post_test_tuning_performed": false,
    "pipeline_changes_allowed_after_this_record": false
}


----------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/configs/phase2B_locked_evaluation_protocol.json
----------------------------------------------------------------------------------------------------
{
    "status": "LOCKED_BEFORE_TEST_INFERENCE",
    "partition": "test",
    "n_patients": 50,
    "n_frames": 100,
    "phases": [
        "ED",
        "ES"
    ],
    "segmentation_model": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
    "segmentation_model_sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
    "segmentation_resolution": 256,
    "segmentation_threshold": 0.5,
    "segmentation_postprocessing": [
        "largest connected component",
        "binary hole filling"
    ],
    "long_axis_method": "PCA major axis",
    "volume_method": "single-plane area-length",
    "volume_equation": "V = (8/(3*pi)) * A^2/L",
    "physical_spacing": "Original NIfTI pixel spacing adjusted for x/y stretch-resize scale factors.",
    "outputs": [
        "ED area",
        "ES area",
        "ED length",
        "ES length",
        "EDV",
        "ESV",
        "SV",
        "EF"
    ],
    "reference_EF_source": "CAMUS Info_4CH.cfg EF",
    "post_test_changes_allowed": false,
    "prohibited_post_test_actions": [
        "segmentation retraining",
        "threshold tuning",
        "postprocessing tuning",
        "PCA/Feret reselection",
        "area-bias correction",
        "EF calibration",
        "geometry-method modification"
    ],
    "test_partition_limitation": "The 50-patient partition was held out from the clean Phase 1A-1D and Phase 2A method-selection processes, but had historical pilot exposure and is therefore not claimed to be a pristine external test set."
}

In [ ]:
# ================================================================
# PHASE 5B — CELL 11
# INSPECT PHASE 3 MODEL / CLASSIFIER CONFIGURATION RECORDS
# ================================================================

phase3_json_paths = sorted(
    [
        path
        for path in PHASE3_DIR.rglob("*.json")
        if path.is_file()
    ]
)


print("=" * 100)
print("PHASE 3 CONFIGURATION RECORDS")
print("=" * 100)


for path in phase3_json_paths:

    print("\n")
    print("-" * 100)

    print(
        path.relative_to(PROJECT_ROOT)
    )

    print("-" * 100)

    try:

        with open(
            path,
            "r"
        ) as file:

            content = json.load(file)

        print(
            json.dumps(
                content,
                indent=4
            )
        )

    except Exception as error:

        print(
            f"Could not read JSON: {error}"
        )

====================================================================================================
PHASE 3 CONFIGURATION RECORDS
====================================================================================================


----------------------------------------------------------------------------------------------------
phase3_classification/phase3A_label_audit/configs/phase3A_classification_target_decision.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 3A \u2014 EF Classification Target Definition",
    "status": "COMPLETE_AND_FROZEN",
    "primary_task": "Three-class EF-based functional classification",
    "reference_source": "CAMUS Info_4CH.cfg EF",
    "target_definition": {
        "Lower_EF": "reference EF <= 40%",
        "Intermediate_EF": "40% < reference EF < 50%",
        "Higher_EF": "reference EF >= 50%"
    },
    "class_order": [
        "Lower_EF",
        "Intermediate_EF",
        "Higher_EF"
    ],
    "terminology_note": "The categories are EF-based functional bands for an assistive, non-diagnostic research system. They are not used as standalone heart-failure diagnoses.",
    "dataset": {
        "total_patients": 500,
        "train": {
            "n": 400,
            "Lower_EF": 143,
            "Intermediate_EF": 125,
            "Higher_EF": 132
        },
        "validation": {
            "n": 50,
            "Lower_EF": 13,
            "Intermediate_EF": 17,
            "Higher_EF": 20
        },
        "test": {
            "n": 50,
            "Lower_EF": 16,
            "Intermediate_EF": 14,
            "Higher_EF": 20
        }
    },
    "class_balance_decision": "No resampling, SMOTE, or other synthetic balancing is introduced at target-definition stage because all three classes have substantial representation and the training distribution is approximately balanced.",
    "split_policy": "Original patient-level 400/50/50 split with seed 42 is retained.",
    "test_policy": "The test partition is not used for classifier selection, feature selection, hyperparameter selection, threshold adjustment, or calibration.",
    "historical_test_note": "The test partition had historical pilot exposure before the clean rebuild and is therefore not described as a pristine external test set.",
    "target_frozen": true
}


----------------------------------------------------------------------------------------------------
phase3_classification/phase3B_direct_baseline/configs/phase3B_direct_baseline_record.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 3B \u2014 Direct Geometry Classification Baseline",
    "status": "COMPLETE_AND_FROZEN",
    "task": "Direct three-class EF-based functional classification using the frozen Phase 2 predicted EF.",
    "evaluation_partition": {
        "split": "test",
        "n_patients": 50
    },
    "method": "CAMUS reference EF was converted to the frozen Phase 3A EF bands and compared with the class obtained by applying the identical fixed bands to the frozen Phase 2 predicted EF. No classifier was trained.",
    "class_definition": {
        "Lower_EF": "EF <= 40%",
        "Intermediate_EF": "40% < EF < 50%",
        "Higher_EF": "EF >= 50%"
    },
    "terminology_note": "These labels represent EF-based functional bands for an assistive, non-diagnostic research system and are not standalone heart-failure diagnoses.",
    "reference_distribution": {
        "Lower_EF": 16,
        "Intermediate_EF": 14,
        "Higher_EF": 20
    },
    "predicted_distribution": {
        "Lower_EF": 13,
        "Intermediate_EF": 11,
        "Higher_EF": 26
    },
    "performance": {
        "accuracy": 0.66,
        "balanced_accuracy": 0.6274,
        "macro_F1": 0.6241,
        "weighted_F1": 0.6457,
        "cohen_kappa": 0.4747,
        "correct_patients": 33,
        "incorrect_patients": 17
    },
    "per_class_performance": {
        "Lower_EF": {
            "precision": 0.7692,
            "recall": 0.625,
            "F1": 0.6897,
            "support": 16
        },
        "Intermediate_EF": {
            "precision": 0.4545,
            "recall": 0.3571,
            "F1": 0.4,
            "support": 14
        },
        "Higher_EF": {
            "precision": 0.6923,
            "recall": 0.9,
            "F1": 0.7826,
            "support": 20
        }
    },
    "confusion_matrix": {
        "class_order": [
            "Lower_EF",
            "Intermediate_EF",
            "Higher_EF"
        ],
        "matrix": [
            [
                10,
                4,
                2
            ],
            [
                3,
                5,
                6
            ],
            [
                0,
                2,
                18
            ]
        ]
    },
    "transition_analysis": {
        "total_errors": 17,
        "adjacent_class_errors": 15,
        "two_class_errors": 2,
        "adjacent_error_fraction_pct": 88.24,
        "predicted_higher_band": 12,
        "predicted_lower_band": 5,
        "exact_transitions": {
            "Lower_to_Intermediate": 4,
            "Lower_to_Higher": 2,
            "Intermediate_to_Lower": 3,
            "Intermediate_to_Higher": 6,
            "Higher_to_Intermediate": 2,
            "Higher_to_Lower": 0
        }
    },
    "boundary_analysis": {
        "correct": {
            "n": 33,
            "mean_distance_pp": 7.0,
            "median_distance_pp": 6.0
        },
        "incorrect": {
            "n": 17,
            "mean_distance_pp": 5.647,
            "median_distance_pp": 4.0
        },
        "mann_whitney_U": 331.0,
        "two_sided_p_value": 0.303953,
        "interpretation": "Misclassified patients were descriptively closer to the nearest 40% or 50% EF boundary, but the difference was not statistically significant in this 50-patient evaluation sample. Boundary proximity alone therefore did not explain all classification errors.",
        "analysis_type": "descriptive post-hoc locked-baseline analysis",
        "used_for_threshold_tuning": false
    },
    "two_class_jump_analysis": {
        "n_cases": 2,
        "patient0217": {
            "image_quality": "Good",
            "reference_EF_pct": 19.0,
            "GT_geometry_EF_pct": 67.673,
            "predicted_geometry_EF_pct": 61.795,
            "reference_to_GT_geometry_error_pp": 48.673,
            "GT_geometry_to_predicted_error_pp": -5.878,
            "reference_to_predicted_error_pp": 42.795,
            "transition": "Lower_EF -> Higher_EF",
            "interpretation": "The dominant disagreement occurred before segmentation propagation: even GT-mask geometry produced an EF far above the CAMUS reference EF. The segmentation-derived EF was slightly lower than GT geometry. This case is therefore primarily a reference-versus-geometric-method disagreement rather than a segmentation-driven classification failure."
        },
        "patient0072": {
            "image_quality": "Medium",
            "reference_EF_pct": 38.0,
            "GT_geometry_EF_pct": 47.885,
            "predicted_geometry_EF_pct": 53.532,
            "reference_to_GT_geometry_error_pp": 9.885,
            "GT_geometry_to_predicted_error_pp": 5.647,
            "reference_to_predicted_error_pp": 15.532,
            "transition": "Lower_EF -> Higher_EF",
            "interpretation": "Both reference-versus-geometry disagreement and segmentation propagation contributed to the final two-class transition."
        }
    },
    "main_findings": [
        "The direct frozen quantitative pipeline achieved 66.0% exact three-class agreement with the reference EF-based functional bands.",
        "Higher EF showed the highest recall at 90.0%, while Intermediate EF was the most difficult class with 35.7% recall and F1 of 0.400.",
        "Fifteen of seventeen classification errors (88.24%) were adjacent-band errors.",
        "Twelve of seventeen misclassified patients were assigned to a higher EF band than their reference band.",
        "Boundary proximity alone did not adequately explain classification disagreement.",
        "The two largest class-jump errors had different error sources, demonstrating that end-to-end classification failure cannot be attributed solely to segmentation."
    ],
    "methodological_integrity": {
        "classifier_trained": false,
        "EF_boundaries_modified": false,
        "segmentation_modified": false,
        "phase2_geometry_modified": false,
        "bias_correction_applied": false,
        "calibration_applied": false,
        "patients_removed": false,
        "test_based_tuning": false
    },
    "limitations": [
        "The evaluation contains only 50 patients.",
        "The Intermediate EF band spans a relatively narrow range and is sensitive to quantitative EF disagreement.",
        "Predicted EF inherits both segmentation error and single-plane geometry/reference-method disagreement.",
        "The evaluation partition had historical pilot exposure and is not described as a pristine external test set."
    ],
    "phase3B_frozen": true,
    "post_evaluation_threshold_tuning": false,
    "next_phase": "Phase 3C \u2014 Learned Classifier Development"
}


----------------------------------------------------------------------------------------------------
phase3_classification/phase3C_classifier_development/configs/phase3C_development_record.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 3C \u2014 Learned Classifier Development",
    "status": "DEVELOPMENT_COMPLETE_AND_FROZEN",
    "development_data": {
        "train_patients": 400,
        "validation_patients": 50,
        "test_patients_used": 0
    },
    "classification_target": {
        "type": "Frozen Phase 3A EF-based functional bands",
        "Lower_EF": "reference EF <= 40%",
        "Intermediate_EF": "40% < reference EF < 50%",
        "Higher_EF": "reference EF >= 50%"
    },
    "input_source": "Frozen Phase 1 segmentation model followed by the frozen Phase 2 PCA area-length quantitative pipeline.",
    "candidate_feature_sets": {
        "F1_EF_only": [
            "PRED_EF_pct"
        ],
        "F2_volumetric": [
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ],
        "F3_full_quantitative": [
            "PRED_ED_area_mm2",
            "PRED_ES_area_mm2",
            "PRED_ED_length_mm",
            "PRED_ES_length_mm",
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ]
    },
    "classifier": {
        "pipeline": "StandardScaler + LogisticRegression",
        "solver": "lbfgs",
        "max_iter": 5000,
        "random_state": 42,
        "class_weight": null,
        "resampling": null
    },
    "selection": {
        "primary_metric": "validation macro F1",
        "tie_break": "fewer features for exact macro-F1 tie",
        "selected_feature_set": "F3_full_quantitative",
        "selected_features": [
            "PRED_ED_area_mm2",
            "PRED_ES_area_mm2",
            "PRED_ED_length_mm",
            "PRED_ES_length_mm",
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ],
        "selected_n_features": 8
    },
    "candidate_validation_results": [
        {
            "feature_set": "F3_full_quantitative",
            "n_features": 8,
            "accuracy": 0.48,
            "balanced_accuracy": 0.4982654600301659,
            "macro_f1": 0.49692969870875175,
            "weighted_f1": 0.48037417503586805,
            "cohen_kappa": 0.21497584541062797
        },
        {
            "feature_set": "F2_volumetric",
            "n_features": 4,
            "accuracy": 0.48,
            "balanced_accuracy": 0.4982654600301659,
            "macro_f1": 0.4928838099569807,
            "weighted_f1": 0.47896526237989656,
            "cohen_kappa": 0.21828021647624773
        },
        {
            "feature_set": "F1_EF_only",
            "n_features": 1,
            "accuracy": 0.42,
            "balanced_accuracy": 0.4394419306184012,
            "macro_f1": 0.43526860193526856,
            "weighted_f1": 0.41989989989989984,
            "cohen_kappa": 0.12545235223160422
        }
    ],
    "selected_validation_results": {
        "accuracy": 0.48,
        "balanced_accuracy": 0.4982654600301659,
        "macro_f1": 0.49692969870875175,
        "weighted_f1": 0.48037417503586805,
        "cohen_kappa": 0.21497584541062797,
        "correct": 24,
        "incorrect": 26
    },
    "selected_validation_confusion_matrix": {
        "class_order": [
            "Lower_EF",
            "Intermediate_EF",
            "Higher_EF"
        ],
        "matrix": [
            [
                8,
                4,
                1
            ],
            [
                2,
                9,
                6
            ],
            [
                2,
                11,
                7
            ]
        ]
    },
    "selected_model_artifact": {
        "path": "/content/drive/MyDrive/CAMUS_FINAL/phase3_classification/phase3C_classifier_development/models/phase3C_selected_logistic_regression.joblib",
        "sha256": "2ab03a57d0655aa557d0f3ce30c7438c84baa8e068575ba0ebc2ead3344194e6"
    },
    "development_constraints": {
        "segmentation_model_modified": false,
        "quantitative_pipeline_modified": false,
        "classification_thresholds_modified": false,
        "test_data_used_for_selection": false,
        "post_validation_hyperparameter_search": false
    },
    "interpretation": "Among the three predefined quantitative feature representations, F3_full_quantitative achieved the highest validation macro F1 and was therefore selected. The selected classifier is frozen before final test evaluation. Validation performance is moderate and does not establish clinical diagnostic performance.",
    "phase3C_frozen": true
}


----------------------------------------------------------------------------------------------------
phase3_classification/phase3C_classifier_development/configs/phase3C_predefined_protocol.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 3C \u2014 Learned Classifier Development",
    "purpose": "Develop a lightweight classifier using frozen quantitative LV measurements to predict the frozen Phase 3A EF-based functional categories.",
    "classification_target": "Phase 3A frozen 3-class reference-EF target",
    "classes": [
        "Lower_EF",
        "Intermediate_EF",
        "Higher_EF"
    ],
    "class_definition": {
        "Lower_EF": "reference EF <= 40%",
        "Intermediate_EF": "40% < reference EF < 50%",
        "Higher_EF": "reference EF >= 50%"
    },
    "development_partitions": {
        "training": 400,
        "validation": 50,
        "test_used_during_phase3C": 0
    },
    "primary_selection_metric": "validation macro F1",
    "secondary_metrics": [
        "accuracy",
        "balanced accuracy",
        "weighted F1",
        "Cohen kappa",
        "per-class precision",
        "per-class recall",
        "per-class F1"
    ],
    "feature_sets": {
        "F1_EF_only": [
            "PRED_EF_pct"
        ],
        "F2_volumetric": [
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ],
        "F3_full_quantitative": [
            "PRED_ED_area_mm2",
            "PRED_ES_area_mm2",
            "PRED_ED_length_mm",
            "PRED_ES_length_mm",
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ]
    },
    "classifier": "StandardScaler + multinomial-capable LogisticRegression",
    "classifier_settings": {
        "solver": "lbfgs",
        "max_iter": 5000,
        "random_state": 42
    },
    "resampling": "none",
    "SMOTE": false,
    "class_weights_predefined": null,
    "feature_scaling": "StandardScaler fitted on training data only within sklearn Pipeline.",
    "segmentation_model_frozen": true,
    "quantitative_pipeline_frozen": true,
    "phase2_geometry_method": "PCA major-axis + single-plane area-length",
    "test_data_allowed_for_model_selection": false,
    "selection_rule": "Select the feature set/classifier configuration with the highest validation macro F1. The final test partition is reserved for Phase 3D.",
    "clinical_framing": "EF-based functional classification for an assistive, non-diagnostic application."
}


----------------------------------------------------------------------------------------------------
phase3_classification/phase3D_final_evaluation/configs/phase3D_final_evaluation_record.json
----------------------------------------------------------------------------------------------------
{
    "phase": "Phase 3D \u2014 Final Locked Evaluation",
    "status": "COMPLETE_AND_FROZEN",
    "evaluation_set": {
        "n_patients": 50,
        "role": "locked final evaluation set",
        "historical_note": "This partition had historical pilot exposure earlier in the overall project; therefore it is not described as a pristine external or never-seen test cohort."
    },
    "classification_target": {
        "Lower_EF": "reference EF <= 40%",
        "Intermediate_EF": "40% < reference EF < 50%",
        "Higher_EF": "reference EF >= 50%"
    },
    "learned_classifier": {
        "selected_feature_set": "F3_full_quantitative",
        "features": [
            "PRED_ED_area_mm2",
            "PRED_ES_area_mm2",
            "PRED_ED_length_mm",
            "PRED_ES_length_mm",
            "PRED_EDV_ml",
            "PRED_ESV_ml",
            "PRED_SV_ml",
            "PRED_EF_pct"
        ],
        "model_path": "/content/drive/MyDrive/CAMUS_FINAL/phase3_classification/phase3C_classifier_development/models/phase3C_selected_logistic_regression.joblib",
        "model_sha256": "2ab03a57d0655aa557d0f3ce30c7438c84baa8e068575ba0ebc2ead3344194e6",
        "training_or_tuning_in_phase3D": false
    },
    "final_learned_classifier_metrics": {
        "accuracy": 0.7,
        "balanced_accuracy": 0.6732142857142858,
        "macro_f1": 0.6629307007355788,
        "weighted_f1": 0.6860882694541232,
        "cohen_kappa": 0.5415647921760391,
        "correct": 35,
        "incorrect": 15
    },
    "confusion_matrix": {
        "class_order": [
            "Lower_EF",
            "Intermediate_EF",
            "Higher_EF"
        ],
        "matrix": [
            [
                13,
                2,
                1
            ],
            [
                6,
                5,
                3
            ],
            [
                0,
                3,
                17
            ]
        ]
    },
    "per_class_metrics": [
        {
            "class": "Lower_EF",
            "precision": 0.6842105263157895,
            "recall": 0.8125,
            "f1": 0.7428571428571429,
            "support": 16
        },
        {
            "class": "Intermediate_EF",
            "precision": 0.5,
            "recall": 0.35714285714285715,
            "f1": 0.4166666666666667,
            "support": 14
        },
        {
            "class": "Higher_EF",
            "precision": 0.8095238095238095,
            "recall": 0.85,
            "f1": 0.8292682926829268,
            "support": 20
        }
    ],
    "direct_geometry_baseline": {
        "accuracy": 0.66,
        "balanced_accuracy": 0.6274,
        "macro_f1": 0.6241,
        "weighted_f1": 0.6457,
        "cohen_kappa": 0.4747
    },
    "learned_minus_baseline": {
        "accuracy": 0.039999999999999925,
        "balanced_accuracy": 0.04581428571428581,

In [ ]:
# ================================================================
# PHASE 5B — CELL 12
# LOCATE AND INSPECT SAVED PHASE 3 CLASSIFIER ARTIFACT
# ================================================================

import joblib


phase3_joblib_paths = sorted(
    [
        path
        for path in PHASE3_DIR.rglob("*.joblib")
        if path.is_file()
    ]
)


print("=" * 100)
print("PHASE 3 SAVED JOBLIB ARTIFACTS")
print("=" * 100)


for path in phase3_joblib_paths:

    print(
        "\n",
        path.relative_to(PROJECT_ROOT)
    )


assert len(phase3_joblib_paths) >= 1, (
    "No Phase 3 joblib artifact found."
)


# ---------------------------------------------------------------
# Load artifact
# ---------------------------------------------------------------

PHASE3_CLASSIFIER_ARTIFACT_PATH = (
    phase3_joblib_paths[0]
)


phase3_classifier_artifact = joblib.load(
    PHASE3_CLASSIFIER_ARTIFACT_PATH
)


print("\n" + "=" * 100)
print("LOADED ARTIFACT")
print("=" * 100)

print(
    "\nPath:"
)

print(
    PHASE3_CLASSIFIER_ARTIFACT_PATH
)

print(
    "\nPython type:"
)

print(
    type(phase3_classifier_artifact)
)


# ---------------------------------------------------------------
# Inspect structure without changing anything
# ---------------------------------------------------------------

if isinstance(
    phase3_classifier_artifact,
    dict
):

    print(
        "\nDictionary keys:"
    )

    for key in phase3_classifier_artifact.keys():
        print(
            f"  • {key}"
        )


elif hasattr(
    phase3_classifier_artifact,
    "named_steps"
):

    print(
        "\nPipeline steps:"
    )

    for name, object_ in (
        phase3_classifier_artifact
        .named_steps
        .items()
    ):

        print(
            f"  • {name}: {type(object_)}"
        )


else:

    print(
        "\nObject representation:"
    )

    print(
        phase3_classifier_artifact
    )


print(
    "\n✓ Saved classifier artifact inspected."
)

====================================================================================================
PHASE 3 SAVED JOBLIB ARTIFACTS
====================================================================================================

 phase3_classification/phase3C_classifier_development/models/phase3C_selected_logistic_regression.joblib

====================================================================================================
LOADED ARTIFACT
====================================================================================================

Path:
/content/drive/MyDrive/CAMUS_FINAL/phase3_classification/phase3C_classifier_development/models/phase3C_selected_logistic_regression.joblib

Python type:
<class 'sklearn.pipeline.Pipeline'>

Pipeline steps:
  • scaler: <class 'sklearn.preprocessing._data.StandardScaler'>
  • classifier: <class 'sklearn.linear_model._logistic.LogisticRegression'>

✓ Saved classifier artifact inspected.

In [ ]:
# ================================================================
# PHASE 5B — CELL 13
# INSPECT FROZEN CLASSIFIER METADATA
# ================================================================

print("=" * 100)
print("FROZEN CLASSIFIER METADATA")
print("=" * 100)


if hasattr(
    phase3_classifier_artifact,
    "named_steps"
):

    print(
        "\nArtifact is an sklearn-style Pipeline."
    )

    print(
        "\nPipeline:"
    )

    print(
        phase3_classifier_artifact
    )

    if hasattr(
        phase3_classifier_artifact,
        "feature_names_in_"
    ):

        print(
            "\nFeature names:"
        )

        for feature in (
            phase3_classifier_artifact
            .feature_names_in_
        ):
            print(
                f"  • {feature}"
            )

    if hasattr(
        phase3_classifier_artifact,
        "classes_"
    ):

        print(
            "\nClass order:"
        )

        print(
            phase3_classifier_artifact.classes_
        )


elif isinstance(
    phase3_classifier_artifact,
    dict
):

    print(
        "\nArtifact is a dictionary."
    )

    for key, value in (
        phase3_classifier_artifact.items()
    ):

        print(
            f"\n{key}"
        )

        print(
            f"Type: {type(value)}"
        )

        if isinstance(
            value,
            (
                str,
                int,
                float,
                bool,
                list,
                tuple
            )
        ):

            print(
                value
            )

        elif hasattr(
            value,
            "classes_"
        ):

            print(
                "Classes:",
                value.classes_
            )

        elif hasattr(
            value,
            "feature_names_in_"
        ):

            print(
                "Features:",
                value.feature_names_in_
            )


else:

    print(
        "\nArtifact type:"
    )

    print(
        type(
            phase3_classifier_artifact
        )
    )


print(
    "\n✓ Frozen classifier metadata inspection complete."
)

====================================================================================================
FROZEN CLASSIFIER METADATA
====================================================================================================

Artifact is an sklearn-style Pipeline.

Pipeline:
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 LogisticRegression(max_iter=5000, random_state=42))])

Class order:
['Higher_EF' 'Intermediate_EF' 'Lower_EF']

✓ Frozen classifier metadata inspection complete.

In [ ]:
# ================================================================
# PHASE 5B — CELL 14
# DEFINE FROZEN PHASE 3 FEATURE CONTRACT
# ================================================================

PHASE3_FEATURE_COLUMNS = [

    "PRED_ED_area_mm2",
    "PRED_ES_area_mm2",

    "PRED_ED_length_mm",
    "PRED_ES_length_mm",

    "PRED_EDV_ml",
    "PRED_ESV_ml",

    "PRED_SV_ml",
    "PRED_EF_pct"
]


missing_features = [
    feature
    for feature in PHASE3_FEATURE_COLUMNS
    if feature not in phase3_frozen_predictions_df.columns
]


assert len(missing_features) == 0, (
    f"Missing Phase 3 features: {missing_features}"
)


print("=" * 90)
print("FROZEN PHASE 3 FEATURE CONTRACT")
print("=" * 90)

for index, feature in enumerate(
    PHASE3_FEATURE_COLUMNS,
    start=1
):
    print(
        f"{index}. {feature}"
    )


print(
    "\nFeature count:",
    len(PHASE3_FEATURE_COLUMNS)
)

print(
    "\n✓ Frozen Phase 3 feature contract defined."
)

==========================================================================================
FROZEN PHASE 3 FEATURE CONTRACT
==========================================================================================
1. PRED_ED_area_mm2
2. PRED_ES_area_mm2
3. PRED_ED_length_mm
4. PRED_ES_length_mm
5. PRED_EDV_ml
6. PRED_ESV_ml
7. PRED_SV_ml
8. PRED_EF_pct

Feature count: 8

✓ Frozen Phase 3 feature contract defined.

In [ ]:
# ================================================================
# PHASE 5B — CELL 15
# VERIFY FROZEN CLASSIFIER STRUCTURE
# ================================================================

EXPECTED_CLASS_ORDER = np.array([
    "Higher_EF",
    "Intermediate_EF",
    "Lower_EF"
])


assert hasattr(
    phase3_classifier_artifact,
    "predict"
)

assert hasattr(
    phase3_classifier_artifact,
    "predict_proba"
)

assert hasattr(
    phase3_classifier_artifact,
    "named_steps"
)


assert "scaler" in (
    phase3_classifier_artifact.named_steps
)

assert "classifier" in (
    phase3_classifier_artifact.named_steps
)


actual_class_order = (
    phase3_classifier_artifact.classes_
)


assert np.array_equal(
    actual_class_order,
    EXPECTED_CLASS_ORDER
), (
    "Frozen classifier class order differs "
    "from expected Phase 3 order."
)


print("=" * 90)
print("FROZEN CLASSIFIER VERIFICATION")
print("=" * 90)

print(
    "\nPipeline:"
)

print(
    phase3_classifier_artifact
)

print(
    "\nClass order:"
)

for index, class_name in enumerate(
    actual_class_order
):
    print(
        f"  Probability column {index}: "
        f"{class_name}"
    )


print(
    "\n✓ Frozen scaler + classifier pipeline verified."
)

print(
    "✓ Class-probability ordering verified."
)

==========================================================================================
FROZEN CLASSIFIER VERIFICATION
==========================================================================================

Pipeline:
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 LogisticRegression(max_iter=5000, random_state=42))])

Class order:
  Probability column 0: Higher_EF
  Probability column 1: Intermediate_EF
  Probability column 2: Lower_EF

✓ Frozen scaler + classifier pipeline verified.
✓ Class-probability ordering verified.

In [ ]:
# ================================================================
# PHASE 5B — CELL 16
# REPRODUCE FROZEN PHASE 3 PREDICTIONS
# ================================================================

phase3_verification_features = (
    phase3_frozen_predictions_df[
        PHASE3_FEATURE_COLUMNS
    ].copy()
)


reproduced_predictions = (
    phase3_classifier_artifact.predict(
        phase3_verification_features
    )
)


reproduced_probabilities = (
    phase3_classifier_artifact.predict_proba(
        phase3_verification_features
    )
)


assert reproduced_probabilities.shape == (
    len(phase3_frozen_predictions_df),
    3
)


phase3_classifier_verification_df = pd.DataFrame({

    "patient_id":
        phase3_frozen_predictions_df[
            "patient_id"
        ].values,

    "frozen_prediction":
        phase3_frozen_predictions_df[
            "learned_prediction"
        ].values,

    "reproduced_prediction":
        reproduced_predictions,

    "frozen_prob_Higher_EF":
        phase3_frozen_predictions_df[
            "prob_Higher_EF"
        ].values,

    "reproduced_prob_Higher_EF":
        reproduced_probabilities[:, 0],

    "frozen_prob_Intermediate_EF":
        phase3_frozen_predictions_df[
            "prob_Intermediate_EF"
        ].values,

    "reproduced_prob_Intermediate_EF":
        reproduced_probabilities[:, 1],

    "frozen_prob_Lower_EF":
        phase3_frozen_predictions_df[
            "prob_Lower_EF"
        ].values,

    "reproduced_prob_Lower_EF":
        reproduced_probabilities[:, 2]
})


phase3_classifier_verification_df[
    "prediction_match"
] = (
    phase3_classifier_verification_df[
        "frozen_prediction"
    ]
    ==
    phase3_classifier_verification_df[
        "reproduced_prediction"
    ]
)


print("=" * 90)
print("PHASE 3 CLASSIFIER REPRODUCTION CHECK")
print("=" * 90)

print(
    "\nPrediction matches:",
    phase3_classifier_verification_df[
        "prediction_match"
    ].sum(),
    "/",
    len(
        phase3_classifier_verification_df
    )
)


display(
    phase3_classifier_verification_df.head()
)

==========================================================================================
PHASE 3 CLASSIFIER REPRODUCTION CHECK
==========================================================================================

Prediction matches: 50 / 50

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

,patient_id,frozen_prediction,reproduced_prediction,frozen_prob_Higher_EF,reproduced_prob_Higher_EF,frozen_prob_Intermediate_EF,reproduced_prob_Intermediate_EF,frozen_prob_Lower_EF,reproduced_prob_Lower_EF,prediction_match
0,patient0004,Higher_EF,Higher_EF,0.805372,0.805372,0.185380,0.185380,0.009248,0.009248,True
1,patient0013,Lower_EF,Lower_EF,0.013721,0.013721,0.319127,0.319127,0.667152,0.667152,True
2,patient0014,Higher_EF,Higher_EF,0.931696,0.931696,0.066975,0.066975,0.001329,0.001329,True
3,patient0016,Higher_EF,Higher_EF,0.655681,0.655681,0.314416,0.314416,0.029903,0.029903,True
4,patient0017,Higher_EF,Higher_EF,0.677461,0.677461,0.298111,0.298111,0.024428,0.024428,True

In [ ]:
# ================================================================
# PHASE 5B — CELL 17
# VERIFY NUMERICAL PROBABILITY REPRODUCTION
# ================================================================

probability_checks = {}


for class_name, probability_index in [

    ("Higher_EF", 0),

    ("Intermediate_EF", 1),

    ("Lower_EF", 2)

]:

    frozen_values = (
        phase3_frozen_predictions_df[
            f"prob_{class_name}"
        ].to_numpy()
    )

    reproduced_values = (
        reproduced_probabilities[
            :,
            probability_index
        ]
    )

    absolute_difference = np.abs(
        frozen_values
        -
        reproduced_values
    )

    probability_checks[
        class_name
    ] = {

        "max_absolute_difference":
            float(
                absolute_difference.max()
            ),

        "mean_absolute_difference":
            float(
                absolute_difference.mean()
            )
    }


all_predictions_match = bool(
    np.all(
        reproduced_predictions
        ==
        phase3_frozen_predictions_df[
            "learned_prediction"
        ].to_numpy()
    )
)


max_probability_difference = max(

    result[
        "max_absolute_difference"
    ]

    for result
    in probability_checks.values()
)


print("=" * 90)
print("PHASE 3 NUMERICAL REPRODUCTION")
print("=" * 90)

print(
    "\nAll predicted classes match:",
    all_predictions_match
)


for class_name, result in (
    probability_checks.items()
):

    print(
        f"\n{class_name}"
    )

    print(
        "  Max absolute probability difference:",
        f"{result['max_absolute_difference']:.12f}"
    )

    print(
        "  Mean absolute probability difference:",
        f"{result['mean_absolute_difference']:.12f}"
    )


print(
    "\nOverall maximum probability difference:",
    f"{max_probability_difference:.12f}"
)


assert all_predictions_match, (
    "Frozen classifier does not reproduce "
    "all Phase 3 predictions."
)


# CSV values may have undergone decimal serialization,
# so use a very small numerical tolerance rather than exact equality.

assert max_probability_difference < 1e-10, (
    "Probability reproduction discrepancy "
    "is larger than expected."
)


print(
    "\n✓ Frozen Phase 3 classifier reproduced successfully."
)

==========================================================================================
PHASE 3 NUMERICAL REPRODUCTION
==========================================================================================

All predicted classes match: True

Higher_EF
  Max absolute probability difference: 0.000000000000
  Mean absolute probability difference: 0.000000000000

Intermediate_EF
  Max absolute probability difference: 0.000000000000
  Mean absolute probability difference: 0.000000000000

Lower_EF
  Max absolute probability difference: 0.000000000000
  Mean absolute probability difference: 0.000000000000

Overall maximum probability difference: 0.000000000000

✓ Frozen Phase 3 classifier reproduced successfully.

In [ ]:
# ================================================================
# PHASE 5B — CELL 18
# LOAD EXACT FROZEN PHASE 2A MEASUREMENT SPECIFICATIONS
# ================================================================

PHASE2A_CONFIG_DIR = (
    PROJECT_ROOT
    / "phase2_quantitative"
    / "phase2A_measurement_method"
    / "configs"
)


PHASE2A_PROTOCOL_PATH = (
    PHASE2A_CONFIG_DIR
    / "phase2A_measurement_protocol.json"
)

PHASE2A_GEOMETRY_DECISION_PATH = (
    PHASE2A_CONFIG_DIR
    / "phase2A_geometry_method_decision.json"
)

PHASE2A_DEVELOPMENT_RECORD_PATH = (
    PHASE2A_CONFIG_DIR
    / "phase2A_development_record.json"
)


phase2A_config_paths = {

    "MEASUREMENT PROTOCOL":
        PHASE2A_PROTOCOL_PATH,

    "GEOMETRY METHOD DECISION":
        PHASE2A_GEOMETRY_DECISION_PATH,

    "DEVELOPMENT RECORD":
        PHASE2A_DEVELOPMENT_RECORD_PATH
}


phase2A_configs = {}


print("=" * 100)
print("FROZEN PHASE 2A MEASUREMENT SPECIFICATIONS")
print("=" * 100)


for name, path in phase2A_config_paths.items():

    assert path.exists(), (
        f"Missing Phase 2A configuration: {path}"
    )

    with open(
        path,
        "r"
    ) as file:

        content = json.load(file)

    phase2A_configs[name] = content

    print("\n")
    print("=" * 100)
    print(name)
    print("=" * 100)

    print(
        json.dumps(
            content,
            indent=4
        )
    )


print(
    "\n✓ All frozen Phase 2A configuration records loaded."
)

====================================================================================================
FROZEN PHASE 2A MEASUREMENT SPECIFICATIONS
====================================================================================================


====================================================================================================
MEASUREMENT PROTOCOL
====================================================================================================
{
    "phase": "Phase 2A \u2014 LV Quantitative Measurement Method",
    "purpose": "Establish and validate the quantitative measurement methodology used downstream of the frozen LV segmentation model.",
    "segmentation_model_frozen": true,
    "segmentation_model": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
    "segmentation_model_sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
    "segmentation_changes_allowed": false,
    "target_view": "A4C",
    "target_structure": "LV cavity",
    "phases": [
        "ED",
        "ES"
    ],
    "physical_units": {
        "area": "mm^2",
        "length": "mm",
        "volume": "mL",
        "EF": "%"
    },
    "candidate_long_axis_methods": [
        "maximum_feret",
        "PCA_major_axis"
    ],
    "volume_method": "single-plane area-length",
    "volume_equation": "V = (8 / (3*pi)) * (A^2 / L)",
    "method_selection_principle": "Geometry methods will first be evaluated using ground-truth LV masks so that measurement-model error is separated from segmentation error.",
    "downstream_quantities": [
        "ED area",
        "ES area",
        "ED long-axis length",
        "ES long-axis length",
        "EDV",
        "ESV",
        "SV",
        "EF"
    ],
    "test_exposure_note": "The current 50-patient evaluation partition was previously inspected during historical pilot development. It was excluded from the clean Phase 1A-1D model-selection process, but is not claimed to be a pristine external test set."
}


====================================================================================================
GEOMETRY METHOD DECISION
====================================================================================================
{
    "status": "FROZEN",
    "selection_partition": "validation",
    "selection_n_patients": 50,
    "selected_long_axis_method": "PCA_major_axis",
    "alternative_method": "maximum_feret",
    "selected_volume_method": "single-plane area-length",
    "volume_equation": "V = (8 / (3*pi)) * (A^2 / L)",
    "selection_reference": "CAMUS Info_4CH.cfg EF",
    "validation_results": {
        "PCA": {
            "EF_MAE_pp": 8.1604,
            "EF_RMSE_pp": 9.4344,
            "EF_bias_pp": 5.8053,
            "EF_correlation": 0.8475,
            "patients_lower_absolute_error": 31
        },
        "Maximum_Feret": {
            "EF_MAE_pp": 8.2922,
            "EF_RMSE_pp": 9.5364,
            "EF_bias_pp": 6.0454,
            "EF_correlation": 0.8512,
            "patients_lower_absolute_error": 19
        }
    },
    "mean_pca_minus_feret_absolute_EF_error_pp": -0.1318,
    "decision": "PCA major-axis length selected because it produced slightly lower validation EF MAE, RMSE and bias, and lower patient-level absolute EF error in 31 of 50 validation patients.",
    "interpretation_limitation": "The difference between PCA and Maximum Feret was small. Selection applies only to the two tested long-axis definitions under this single-plane A4C area-length measurement protocol.",
    "important_observation": "Even with ground-truth masks, PCA-derived single-plane EF showed positive disagreement relative to CAMUS reference EF. Therefore downstream EF disagreement cannot be attributed solely to segmentation error.",
    "test_data_used_for_method_selection": false,
    "method_changes_after_test_evaluation_allowed": false
}


====================================================================================================
DEVELOPMENT RECORD
====================================================================================================
{
    "status": "DEVELOPMENT_COMPLETE_AND_FROZEN",
    "selection_partition": "validation",
    "selection_n_patients": 50,
    "segmentation_model": {
        "status": "FROZEN_FROM_PHASE1F",
        "path": "/content/drive/MyDrive/CAMUS_FINAL/phase1_segmentation/phase1F_final_model/models/final_lv_segmentation_model.keras",
        "sha256": "65ec53959831c6b7c08747a5d94de6563580ce9ec052aa7b9afa614bee5705d3",
        "threshold": 0.5,
        "postprocessing": [
            "largest connected component",
            "binary hole filling"
        ]
    },
    "measurement_pipeline": {
        "resize": "256x256 stretch resize",
        "physical_spacing": "Original NIfTI spacing adjusted independently for x and y according to resize scale factors.",
        "area": "binary LV cavity area in mm^2",
        "long_axis": "PCA major axis",
        "volume": "single-plane area-length",
        "volume_equation": "V = (8/(3*pi)) * A^2/L",
        "EDV": "ED single-plane area-length volume",
        "ESV": "ES single-plane area-length volume",
        "SV": "EDV - ESV",
        "EF": "(EDV - ESV)/EDV * 100"
    },
    "geometry_method_selection": {
        "candidates": [
            "Maximum Feret",
            "PCA major axis"
        ],
        "selected": "PCA major axis",
        "PCA_validation_EF_MAE_pp": 8.1604,
        "Feret_validation_EF_MAE_pp": 8.2922,
        "PCA_lower_error_patients": 31,
        "Feret_lower_error_patients": 19,
        "note": "PCA showed only a small advantage. The selection applies to this predefined two-method comparison."
    },
    "validation_error_decomposition": {
        "reference_to_GT_geometry": {
            "EF_MAE_pp": 8.1076,
            "EF_RMSE_pp": 9.3858,
            "EF_bias_pp": 5.7688,
            "correlation": 0.8488
        },
        "GT_geometry_to_predicted_geometry": {
            "EF_MAE_pp": 7.0468,
            "EF_RMSE_pp": 9.5155,
            "EF_bias_pp": -2.1015,
            "correlation": 0.774
        },
        "reference_to_predicted_geometry": {
            "EF_MAE_pp": 8.7448,
            "EF_RMSE_pp": 11.13,
            "EF_bias_pp": 3.6672,
            "correlation": 0.6944
        }
    },
    "interpretation": {
        "geometry_component": "Substantial EF disagreement remains even when ground-truth LV masks are used, showing that single-plane geometric estimation/reference differences contribute independently of segmentation.",
        "segmentation_component": "Predicted masks introduce additional error into area, length, volume and EF measurements.",
        "error_additivity": "Error components must not be treated as directly additive because signed errors can interact and partially cancel."
    },
    "frozen_before_test_quantitative_evaluation": true,
    "test_results_may_change_pipeline": false
}

✓ All frozen Phase 2A configuration records loaded.

In [ ]:
# ================================================================
# PHASE 5B — CELL 19
# IDENTIFY EXACT PHASE 2 SAVED TABLES
# ================================================================

phase2_csv_paths = sorted(
    [
        path
        for path in PHASE2_DIR.rglob("*.csv")
        if path.is_file()
    ]
)


print("=" * 100)
print("PHASE 2 — EXACT SAVED CSV TABLES")
print("=" * 100)


for index, path in enumerate(
    phase2_csv_paths,
    start=1
):

    print(
        f"{index:02d}. "
        f"{path.relative_to(PROJECT_ROOT)}"
    )


print(
    f"\nTotal Phase 2 CSV files: "
    f"{len(phase2_csv_paths)}"
)

====================================================================================================
PHASE 2 — EXACT SAVED CSV TABLES
====================================================================================================
01. phase2_quantitative/phase2A_measurement_method/tables/ground_truth_geometry_candidates.csv
02. phase2_quantitative/phase2A_measurement_method/tables/validation_EF_error_decomposition.csv
03. phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_method_comparison.csv
04. phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_paired_comparison.csv
05. phase2_quantitative/phase2A_measurement_method/tables/validation_gt_geometry_candidates.csv
06. phase2_quantitative/phase2A_measurement_method/tables/validation_gt_vs_pred_quantitative_measurements.csv
07. phase2_quantitative/phase2A_measurement_method/tables/validation_segmentation_to_measurement_error.csv
08. phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_paired_statistics.csv
09. phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_quantitative_error.csv
10. phase2_quantitative/phase2B_final_evaluation/tables/final_test_EF_error_decomposition.csv
11. phase2_quantitative/phase2B_final_evaluation/tables/final_test_bland_altman_statistics.csv
12. phase2_quantitative/phase2B_final_evaluation/tables/final_test_image_quality_subgroups.csv
13. phase2_quantitative/phase2B_final_evaluation/tables/final_test_patient_level_errors.csv
14. phase2_quantitative/phase2B_final_evaluation/tables/final_test_quantitative_measurements.csv
15. phase2_quantitative/phase2B_final_evaluation/tables/final_test_relative_measurement_errors.csv
16. phase2_quantitative/phase2B_final_evaluation/tables/final_test_segmentation_to_measurement_error.csv
17. phase2_quantitative/phase2B_final_evaluation/tables/worst_10_end_to_end_EF_cases.csv
18. phase2_quantitative/phase2B_final_evaluation/tables/worst_10_segmentation_induced_EF_cases.csv

Total Phase 2 CSV files: 18

In [ ]:
# ================================================================
# PHASE 5B — CELL 20
# INSPECT PHASE 2 TABLE SCHEMAS
# ================================================================

phase2_table_schema_records = []


for path in phase2_csv_paths:

    try:

        table_df = pd.read_csv(
            path
        )

        phase2_table_schema_records.append({

            "file":
                str(
                    path.relative_to(
                        PROJECT_ROOT
                    )
                ),

            "rows":
                len(table_df),

            "columns":
                len(table_df.columns),

            "column_names":
                " | ".join(
                    table_df.columns.astype(str)
                )
        })

    except Exception as error:

        phase2_table_schema_records.append({

            "file":
                str(
                    path.relative_to(
                        PROJECT_ROOT
                    )
                ),

            "rows":
                None,

            "columns":
                None,

            "column_names":
                f"READ ERROR: {error}"
        })


phase2_table_schemas_df = pd.DataFrame(
    phase2_table_schema_records
)


pd.set_option(
    "display.max_colwidth",
    None
)


display(
    phase2_table_schemas_df
)

,file,rows,columns,column_names
0,phase2_quantitative/phase2A_measurement_method/tables/ground_truth_geometry_candidates.csv,50,15,patient_id | ED_area_mm2 | ED_feret_length_mm | ED_pca_length_mm | ED_feret_volume_ml | ED_pca_volume_ml | ES_area_mm2 | ES_feret_length_mm | ES_pca_length_mm | ES_feret_volume_ml | ES_pca_volume_ml | feret_SV_ml | feret_EF_pct | pca_SV_ml | pca_EF_pct
1,phase2_quantitative/phase2A_measurement_method/tables/validation_EF_error_decomposition.csv,3,6,comparison | interpretation | MAE | RMSE | bias | correlation
2,phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_method_comparison.csv,2,7,method | EF_MAE_pp | EF_RMSE_pp | EF_bias_pp | EF_correlation | mean_estimated_EF | mean_reference_EF
3,phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_paired_comparison.csv,50,7,patient_id | reference_EF_pct | feret_EF_pct | pca_EF_pct | feret_abs_error_pp | pca_abs_error_pp | pca_minus_feret_abs_error_pp
4,phase2_quantitative/phase2A_measurement_method/tables/validation_gt_geometry_candidates.csv,50,19,patient_id | reference_EF_pct | image_quality | age | sex | ED_area_mm2 | ED_feret_length_mm | ED_pca_length_mm | ED_feret_volume_ml | ED_pca_volume_ml | ES_area_mm2 | ES_feret_length_mm | ES_pca_length_mm | ES_feret_volume_ml | ES_pca_volume_ml | feret_SV_ml | feret_EF_pct | pca_SV_ml | pca_EF_pct
5,phase2_quantitative/phase2A_measurement_method/tables/validation_gt_vs_pred_quantitative_measurements.csv,50,19,patient_id | reference_EF_pct | image_quality | ED_GT_area_mm2 | ED_PRED_area_mm2 | ED_GT_length_mm | ED_PRED_length_mm | ED_GT_volume_ml | ED_PRED_volume_ml | ES_GT_area_mm2 | ES_PRED_area_mm2 | ES_GT_length_mm | ES_PRED_length_mm | ES_GT_volume_ml | ES_PRED_volume_ml | GT_SV_ml | GT_EF_pct | PRED_SV_ml | PRED_EF_pct
6,phase2_quantitative/phase2A_measurement_method/tables/validation_segmentation_to_measurement_error.csv,8,5,quantity | MAE | RMSE | bias | correlation
7,phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_paired_statistics.csv,2,9,comparison | n | ED_mean_abs_relative_error_pct | ES_mean_abs_relative_error_pct | median_paired_difference_ES_minus_ED_pct | ES_error_greater_patients | ED_error_greater_patients | wilcoxon_statistic | p_value_one_sided
8,phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_quantitative_error.csv,2,5,phase | area_relative_MAE_pct | area_relative_bias_pct | volume_relative_MAE_pct | volume_relative_bias_pct
9,phase2_quantitative/phase2B_final_evaluation/tables/final_test_EF_error_decomposition.csv,3,7,comparison | interpretation | n | MAE | RMSE | bias | correlation
10,phase2_quantitative/phase2B_final_evaluation/tables/final_test_bland_altman_statistics.csv,5,5,comparison | bias | SD_difference | lower_95_LOA | upper_95_LOA
11,phase2_quantitative/phase2B_final_evaluation/tables/final_test_image_quality_subgroups.csv,3,8,image_quality | n | GT_to_PRED_EF_MAE_pp | GT_to_PRED_EF_bias_pp | GT_to_PRED_EF_correlation | Reference_to_PRED_EF_MAE_pp | Reference_to_PRED_EF_bias_pp | Reference_to_PRED_EF_correlation
12,phase2_quantitative/phase2B_final_evaluation/tables/final_test_patient_level_errors.csv,50,27,patient_id | reference_EF_pct | image_quality | age | sex | ED_GT_area_mm2 | ED_PRED_area_mm2 | ED_GT_length_mm | ED_PRED_length_mm | ED_GT_volume_ml | ED_PRED_volume_ml | ES_GT_area_mm2 | ES_PRED_area_mm2 | ES_GT_length_mm | ES_PRED_length_mm | ES_GT_volume_ml | ES_PRED_volume_ml | GT_SV_ml | GT_EF_pct | PRED_SV_ml | PRED_EF_pct | GT_to_PRED_EF_error_pp | GT_to_PRED_EF_abs_error_pp | Reference_to_PRED_EF_error_pp | Reference_to_PRED_EF_abs_error_pp | ED_area_relative_error_pct | ES_area_relative_error_pct
13,phase2_quantitative/phase2B_final_evaluation/tables/final_test_quantitative_measurements.csv,50,21,patient_id | reference_EF_pct | image_quality | age | sex | ED_GT_area_mm2 | ED_PRED_area_mm2 | ED_GT_length_mm | ED_PRED_length_mm | ED_GT_volume_ml | ED_PRED_volume_ml | ES_GT_area_mm2 | ES_PRED_area_mm2 | ES_GT_length_mm | ES_PRED_length_mm | ES_GT_volume_ml | ES_PRED_volume_ml | GT_SV_ml | GT_EF_pct | PRED_SV_ml | PRED_EF_pct
14,phase2_quantitative/phase2B_final_evaluation/tables/final_test_relative_measurement_errors.csv,6,5,quantity | relative_MAE_pct | relative_bias_pct | median_absolute_relative_error_pct | q75_absolute_relative_error_pct
15,phase2_quantitative/phase2B_final_evaluation/tables/final_test_segmentation_to_measurement_error.csv,8,6,quantity | n | MAE | RMSE | bias | correlation
16,phase2_quantitative/phase2B_final_evaluation/tables/worst_10_end_to_end_EF_cases.csv,10,8,patient_id | image_quality | reference_EF_pct | GT_EF_pct | PRED_EF_pct | Reference_to_PRED_EF_abs_error_pp | ED_area_relative_error_pct | ES_area_relative_error_pct
17,phase2_quantitative/phase2B_final_evaluation/tables/worst_10_segmentation_induced_EF_cases.csv,10,8,patient_id | image_quality | reference_EF_pct | GT_EF_pct | PRED_EF_pct | GT_to_PRED_EF_abs_error_pp | ED_area_relative_error_pct | ES_area_relative_error_pct

In [ ]:
# ================================================================
# PHASE 5B — CELL 21
# LOCATE FROZEN PHASE 2 PATIENT-LEVEL QUANTITATIVE TABLE
# ================================================================

required_quantitative_columns = {

    "patient_id",

    "PRED_ED_area_mm2",
    "PRED_ES_area_mm2",

    "PRED_ED_length_mm",
    "PRED_ES_length_mm",

    "PRED_EDV_ml",
    "PRED_ESV_ml",

    "PRED_SV_ml",
    "PRED_EF_pct"
}


phase2_quantitative_candidates = []


for path in phase2_csv_paths:

    try:

        candidate_df = pd.read_csv(
            path
        )

        candidate_columns = set(
            candidate_df.columns
        )

        if required_quantitative_columns.issubset(
            candidate_columns
        ):

            phase2_quantitative_candidates.append(
                {
                    "path":
                        path,

                    "rows":
                        len(
                            candidate_df
                        ),

                    "columns":
                        list(
                            candidate_df.columns
                        )
                }
            )

    except Exception:

        pass


print("=" * 100)
print("PHASE 2 QUANTITATIVE TABLE CANDIDATES")
print("=" * 100)


if len(
    phase2_quantitative_candidates
) == 0:

    print(
        "\nNo table contains the complete "
        "expected quantitative schema."
    )


else:

    for index, candidate in enumerate(
        phase2_quantitative_candidates,
        start=1
    ):

        print(
            f"\nCandidate {index}"
        )

        print(
            candidate["path"].relative_to(
                PROJECT_ROOT
            )
        )

        print(
            "Rows:",
            candidate["rows"]
        )

        print(
            "Columns:"
        )

        for column in candidate[
            "columns"
        ]:

            print(
                f"  • {column}"
            )

====================================================================================================
PHASE 2 QUANTITATIVE TABLE CANDIDATES
====================================================================================================

No table contains the complete expected quantitative schema.

In [ ]:
# ================================================================
# PHASE 5B — CELL 21B
# INSPECT ACTUAL PHASE 2 PATIENT-LEVEL TABLES
# ================================================================

print("=" * 110)
print("PHASE 2 — PATIENT-LEVEL TABLE DISCOVERY")
print("=" * 110)

patient_level_tables = []


for path in phase2_csv_paths:

    try:

        df = pd.read_csv(path)

    except Exception:
        continue


    # Candidate patient-level table:
    # contains patient_id and has a substantial number of rows
    if (
        "patient_id" in df.columns
        and len(df) >= 40
    ):

        patient_level_tables.append(
            {
                "path": path,
                "dataframe": df
            }
        )


print(
    f"\nPatient-level candidate tables found: "
    f"{len(patient_level_tables)}"
)


for index, item in enumerate(
    patient_level_tables,
    start=1
):

    path = item["path"]
    df = item["dataframe"]

    print("\n")
    print("=" * 110)

    print(
        f"CANDIDATE {index}"
    )

    print(
        path.relative_to(PROJECT_ROOT)
    )

    print("-" * 110)

    print(
        f"Shape: {df.shape}"
    )

    print("\nColumns:")

    for column in df.columns:
        print(
            f"  • {column}"
        )

    print("\nFirst 2 rows:")

    display(
        df.head(2)
    )


print(
    "\n✓ Phase 2 patient-level table inspection complete."
)

==============================================================================================================
PHASE 2 — PATIENT-LEVEL TABLE DISCOVERY
==============================================================================================================

Patient-level candidate tables found: 6


==============================================================================================================
CANDIDATE 1
phase2_quantitative/phase2A_measurement_method/tables/ground_truth_geometry_candidates.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 15)

Columns:
  • patient_id
  • ED_area_mm2
  • ED_feret_length_mm
  • ED_pca_length_mm
  • ED_feret_volume_ml
  • ED_pca_volume_ml
  • ES_area_mm2
  • ES_feret_length_mm
  • ES_pca_length_mm
  • ES_feret_volume_ml
  • ES_pca_volume_ml
  • feret_SV_ml
  • feret_EF_pct
  • pca_SV_ml
  • pca_EF_pct

First 2 rows:

,patient_id,ED_area_mm2,ED_feret_length_mm,ED_pca_length_mm,ED_feret_volume_ml,ED_pca_volume_ml,ES_area_mm2,ES_feret_length_mm,ES_pca_length_mm,ES_feret_volume_ml,ES_pca_volume_ml,feret_SV_ml,feret_EF_pct,pca_SV_ml,pca_EF_pct
0,patient0173,2859.580385,78.916550,77.592016,87.953958,89.455376,1616.387678,68.289932,66.432410,32.475305,33.383350,55.478653,63.076926,56.072026,62.681561
1,patient0391,1523.326095,60.781441,59.640382,32.406612,33.026626,1149.467076,57.473164,56.230151,19.514024,19.945397,12.892589,39.783821,13.081229,39.608130

==============================================================================================================
CANDIDATE 2
phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_paired_comparison.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 7)

Columns:
  • patient_id
  • reference_EF_pct
  • feret_EF_pct
  • pca_EF_pct
  • feret_abs_error_pp
  • pca_abs_error_pp
  • pca_minus_feret_abs_error_pp

First 2 rows:

,patient_id,reference_EF_pct,feret_EF_pct,pca_EF_pct,feret_abs_error_pp,pca_abs_error_pp,pca_minus_feret_abs_error_pp
0,patient0037,49.0,53.997354,53.294235,4.997354,4.294235,-0.703119
1,patient0332,48.0,53.870095,53.352376,5.870095,5.352376,-0.517719

==============================================================================================================
CANDIDATE 3
phase2_quantitative/phase2A_measurement_method/tables/validation_gt_geometry_candidates.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 19)

Columns:
  • patient_id
  • reference_EF_pct
  • image_quality
  • age
  • sex
  • ED_area_mm2
  • ED_feret_length_mm
  • ED_pca_length_mm
  • ED_feret_volume_ml
  • ED_pca_volume_ml
  • ES_area_mm2
  • ES_feret_length_mm
  • ES_pca_length_mm
  • ES_feret_volume_ml
  • ES_pca_volume_ml
  • feret_SV_ml
  • feret_EF_pct
  • pca_SV_ml
  • pca_EF_pct

First 2 rows:

,patient_id,reference_EF_pct,image_quality,age,sex,ED_area_mm2,ED_feret_length_mm,ED_pca_length_mm,ED_feret_volume_ml,ED_pca_volume_ml,ES_area_mm2,ES_feret_length_mm,ES_pca_length_mm,ES_feret_volume_ml,ES_pca_volume_ml,feret_SV_ml,feret_EF_pct,pca_SV_ml,pca_EF_pct
0,patient0037,49.0,Medium,72,M,2989.354336,81.585121,79.995256,92.974251,94.822067,1850.417164,67.953629,65.626350,42.770616,44.287372,50.203635,53.997354,50.534695,53.294235
1,patient0332,48.0,Medium,74,M,3022.272143,87.744873,85.981802,88.361737,90.173609,1866.354316,72.537109,70.290732,40.761185,42.063847,47.600552,53.870095,48.109763,53.352376

==============================================================================================================
CANDIDATE 4
phase2_quantitative/phase2A_measurement_method/tables/validation_gt_vs_pred_quantitative_measurements.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 19)

Columns:
  • patient_id
  • reference_EF_pct
  • image_quality
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct

First 2 rows:

,patient_id,reference_EF_pct,image_quality,ED_GT_area_mm2,ED_PRED_area_mm2,ED_GT_length_mm,ED_PRED_length_mm,ED_GT_volume_ml,ED_PRED_volume_ml,ES_GT_area_mm2,ES_PRED_area_mm2,ES_GT_length_mm,ES_PRED_length_mm,ES_GT_volume_ml,ES_PRED_volume_ml,GT_SV_ml,GT_EF_pct,PRED_SV_ml,PRED_EF_pct
0,patient0037,49.0,Medium,2992.825742,3023.138453,79.525485,84.883087,95.603853,91.393175,1840.942712,1568.128310,65.054206,66.741899,44.220539,31.274004,51.383314,53.746070,60.119171,65.780810
1,patient0332,48.0,Medium,3023.494206,2902.483775,85.809088,82.951774,90.428193,86.205065,1868.153738,1730.066409,70.146932,70.887809,42.231393,35.840401,48.196800,53.298422,50.364665,58.424252

==============================================================================================================
CANDIDATE 5
phase2_quantitative/phase2B_final_evaluation/tables/final_test_patient_level_errors.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 27)

Columns:
  • patient_id
  • reference_EF_pct
  • image_quality
  • age
  • sex
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct
  • GT_to_PRED_EF_error_pp
  • GT_to_PRED_EF_abs_error_pp
  • Reference_to_PRED_EF_error_pp
  • Reference_to_PRED_EF_abs_error_pp
  • ED_area_relative_error_pct
  • ES_area_relative_error_pct

First 2 rows:

,patient_id,reference_EF_pct,image_quality,age,sex,ED_GT_area_mm2,ED_PRED_area_mm2,ED_GT_length_mm,ED_PRED_length_mm,ED_GT_volume_ml,...,GT_SV_ml,GT_EF_pct,PRED_SV_ml,PRED_EF_pct,GT_to_PRED_EF_error_pp,GT_to_PRED_EF_abs_error_pp,Reference_to_PRED_EF_error_pp,Reference_to_PRED_EF_abs_error_pp,ED_area_relative_error_pct,ES_area_relative_error_pct
0,patient0173,59.0,Good,57,M,2855.499180,2714.265708,77.659494,78.143962,89.122710,...,55.731421,62.533356,48.534747,60.649136,-1.884220,1.884220,1.649136,1.649136,-4.946017,-5.710594
1,patient0391,35.0,Good,46,F,1524.992144,1715.459785,59.292864,62.373792,33.292901,...,13.273356,39.868425,9.402616,23.478531,-16.389894,16.389894,-11.521469,11.521469,12.489746,23.198259

==============================================================================================================
CANDIDATE 6
phase2_quantitative/phase2B_final_evaluation/tables/final_test_quantitative_measurements.csv
--------------------------------------------------------------------------------------------------------------
Shape: (50, 21)

Columns:
  • patient_id
  • reference_EF_pct
  • image_quality
  • age
  • sex
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct

First 2 rows:

,patient_id,reference_EF_pct,image_quality,age,sex,ED_GT_area_mm2,ED_PRED_area_mm2,ED_GT_length_mm,ED_PRED_length_mm,ED_GT_volume_ml,...,ES_GT_area_mm2,ES_PRED_area_mm2,ES_GT_length_mm,ES_PRED_length_mm,ES_GT_volume_ml,ES_PRED_volume_ml,GT_SV_ml,GT_EF_pct,PRED_SV_ml,PRED_EF_pct
0,patient0173,59.0,Good,57,M,2855.499180,2714.265708,77.659494,78.143962,89.122710,...,1612.311326,1520.238767,66.082047,62.295982,33.391289,31.490708,55.731421,62.533356,48.534747,60.649136
1,patient0391,35.0,Good,46,F,1524.992144,1715.459785,59.292864,62.373792,33.292901,...,1149.999203,1416.779002,56.073765,55.598361,20.019546,30.645103,13.273356,39.868425,9.402616,23.478531

✓ Phase 2 patient-level table inspection complete.

In [ ]:
# ================================================================
# PHASE 5B — CELL 21C
# SEARCH PHASE 2 TABLES FOR QUANTITATIVE MEASUREMENT COLUMNS
# ================================================================

measurement_keywords = [
    "area",
    "length",
    "edv",
    "esv",
    "sv",
    "ef",
    "volume",
    "pca",
    "pred",
    "patient"
]


print("=" * 110)
print("PHASE 2 — QUANTITATIVE COLUMN SEARCH")
print("=" * 110)


for path in phase2_csv_paths:

    try:

        df = pd.read_csv(path)

    except Exception:
        continue


    matched_columns = [

        column

        for column in df.columns

        if any(
            keyword in str(column).lower()
            for keyword in measurement_keywords
        )
    ]


    if matched_columns:

        print("\n" + "-" * 110)

        print(
            path.relative_to(PROJECT_ROOT)
        )

        print(
            f"Shape: {df.shape}"
        )

        print("Relevant columns:")

        for column in matched_columns:
            print(
                f"  • {column}"
            )

==============================================================================================================
PHASE 2 — QUANTITATIVE COLUMN SEARCH
==============================================================================================================

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/tables/ground_truth_geometry_candidates.csv
Shape: (50, 15)
Relevant columns:
  • patient_id
  • ED_area_mm2
  • ED_feret_length_mm
  • ED_pca_length_mm
  • ED_feret_volume_ml
  • ED_pca_volume_ml
  • ES_area_mm2
  • ES_feret_length_mm
  • ES_pca_length_mm
  • ES_feret_volume_ml
  • ES_pca_volume_ml
  • feret_SV_ml
  • feret_EF_pct
  • pca_SV_ml
  • pca_EF_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_method_comparison.csv
Shape: (2, 7)
Relevant columns:
  • EF_MAE_pp
  • EF_RMSE_pp
  • EF_bias_pp
  • EF_correlation
  • mean_estimated_EF
  • mean_reference_EF

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/tables/validation_geometry_paired_comparison.csv
Shape: (50, 7)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • feret_EF_pct
  • pca_EF_pct
  • pca_abs_error_pp
  • pca_minus_feret_abs_error_pp

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/tables/validation_gt_geometry_candidates.csv
Shape: (50, 19)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • ED_area_mm2
  • ED_feret_length_mm
  • ED_pca_length_mm
  • ED_feret_volume_ml
  • ED_pca_volume_ml
  • ES_area_mm2
  • ES_feret_length_mm
  • ES_pca_length_mm
  • ES_feret_volume_ml
  • ES_pca_volume_ml
  • feret_SV_ml
  • feret_EF_pct
  • pca_SV_ml
  • pca_EF_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2A_measurement_method/tables/validation_gt_vs_pred_quantitative_measurements.csv
Shape: (50, 19)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_paired_statistics.csv
Shape: (2, 9)
Relevant columns:
  • ES_error_greater_patients
  • ED_error_greater_patients

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/final_test_ED_vs_ES_quantitative_error.csv
Shape: (2, 5)
Relevant columns:
  • area_relative_MAE_pct
  • area_relative_bias_pct
  • volume_relative_MAE_pct
  • volume_relative_bias_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/final_test_image_quality_subgroups.csv
Shape: (3, 8)
Relevant columns:
  • GT_to_PRED_EF_MAE_pp
  • GT_to_PRED_EF_bias_pp
  • GT_to_PRED_EF_correlation
  • Reference_to_PRED_EF_MAE_pp
  • Reference_to_PRED_EF_bias_pp
  • Reference_to_PRED_EF_correlation

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/final_test_patient_level_errors.csv
Shape: (50, 27)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct
  • GT_to_PRED_EF_error_pp
  • GT_to_PRED_EF_abs_error_pp
  • Reference_to_PRED_EF_error_pp
  • Reference_to_PRED_EF_abs_error_pp
  • ED_area_relative_error_pct
  • ES_area_relative_error_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/final_test_quantitative_measurements.csv
Shape: (50, 21)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/worst_10_end_to_end_EF_cases.csv
Shape: (10, 8)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • GT_EF_pct
  • PRED_EF_pct
  • Reference_to_PRED_EF_abs_error_pp
  • ED_area_relative_error_pct
  • ES_area_relative_error_pct

--------------------------------------------------------------------------------------------------------------
phase2_quantitative/phase2B_final_evaluation/tables/worst_10_segmentation_induced_EF_cases.csv
Shape: (10, 8)
Relevant columns:
  • patient_id
  • reference_EF_pct
  • GT_EF_pct
  • PRED_EF_pct
  • GT_to_PRED_EF_abs_error_pp
  • ED_area_relative_error_pct
  • ES_area_relative_error_pct

In [ ]:
# ================================================================
# PHASE 5B — CELL 22
# LOAD CANONICAL FROZEN PHASE 2 TEST MEASUREMENTS
# ================================================================

PHASE2_FROZEN_PATIENT_TABLE_PATH = (
    PROJECT_ROOT
    / "phase2_quantitative"
    / "phase2B_final_evaluation"
    / "tables"
    / "final_test_quantitative_measurements.csv"
)


assert PHASE2_FROZEN_PATIENT_TABLE_PATH.exists(), (
    f"Missing frozen Phase 2 table:\n"
    f"{PHASE2_FROZEN_PATIENT_TABLE_PATH}"
)


phase2_frozen_patient_df = pd.read_csv(
    PHASE2_FROZEN_PATIENT_TABLE_PATH
)


assert len(phase2_frozen_patient_df) == 50


print("=" * 100)
print("FROZEN PHASE 2 TEST MEASUREMENTS")
print("=" * 100)

print(
    "\nPath:",
    PHASE2_FROZEN_PATIENT_TABLE_PATH.relative_to(
        PROJECT_ROOT
    )
)

print(
    "\nPatients:",
    len(phase2_frozen_patient_df)
)

print("\nColumns:")

for column in phase2_frozen_patient_df.columns:
    print(f"  • {column}")


display(
    phase2_frozen_patient_df.head()
)


print(
    "\n✓ Canonical frozen Phase 2 table loaded."
)

====================================================================================================
FROZEN PHASE 2 TEST MEASUREMENTS
====================================================================================================

Path: phase2_quantitative/phase2B_final_evaluation/tables/final_test_quantitative_measurements.csv

Patients: 50

Columns:
  • patient_id
  • reference_EF_pct
  • image_quality
  • age
  • sex
  • ED_GT_area_mm2
  • ED_PRED_area_mm2
  • ED_GT_length_mm
  • ED_PRED_length_mm
  • ED_GT_volume_ml
  • ED_PRED_volume_ml
  • ES_GT_area_mm2
  • ES_PRED_area_mm2
  • ES_GT_length_mm
  • ES_PRED_length_mm
  • ES_GT_volume_ml
  • ES_PRED_volume_ml
  • GT_SV_ml
  • GT_EF_pct
  • PRED_SV_ml
  • PRED_EF_pct

,patient_id,reference_EF_pct,image_quality,age,sex,ED_GT_area_mm2,ED_PRED_area_mm2,ED_GT_length_mm,ED_PRED_length_mm,ED_GT_volume_ml,...,ES_GT_area_mm2,ES_PRED_area_mm2,ES_GT_length_mm,ES_PRED_length_mm,ES_GT_volume_ml,ES_PRED_volume_ml,GT_SV_ml,GT_EF_pct,PRED_SV_ml,PRED_EF_pct
0,patient0173,59.0,Good,57,M,2855.499180,2714.265708,77.659494,78.143962,89.122710,...,1612.311326,1520.238767,66.082047,62.295982,33.391289,31.490708,55.731421,62.533356,48.534747,60.649136
1,patient0391,35.0,Good,46,F,1524.992144,1715.459785,59.292864,62.373792,33.292901,...,1149.999203,1416.779002,56.073765,55.598361,20.019546,30.645103,13.273356,39.868425,9.402616,23.478531
2,patient0111,43.0,Medium,53,M,2885.189635,2603.580738,74.982090,75.924522,94.234525,...,1884.176499,1513.588657,62.372586,53.419584,48.313475,36.402741,45.921050,48.730601,39.381498,51.965288
3,patient0080,60.0,Good,72,M,3814.560535,3583.520570,88.612761,82.955918,139.383580,...,2000.923487,1998.789169,71.352804,67.785216,47.628706,50.028542,91.754874,65.829041,81.370225,61.926171
4,patient0465,45.0,Medium,85,F,4225.675841,3835.133556,90.137512,85.782194,168.153398,...,2591.137843,2027.159847,72.178011,65.549362,78.957790,53.214058,89.195609,53.044190,92.326050,63.436843

✓ Canonical frozen Phase 2 table loaded.

In [ ]:
# ================================================================
# PHASE 5B — CELL 23
# DEFINE PHASE 2 → PHASE 3 FEATURE MAPPING
# ================================================================

PHASE2_TO_PHASE3_FEATURE_MAP = {

    "ED_PRED_area_mm2":
        "PRED_ED_area_mm2",

    "ES_PRED_area_mm2":
        "PRED_ES_area_mm2",

    "ED_PRED_length_mm":
        "PRED_ED_length_mm",

    "ES_PRED_length_mm":
        "PRED_ES_length_mm",

    "ED_PRED_volume_ml":
        "PRED_EDV_ml",

    "ES_PRED_volume_ml":
        "PRED_ESV_ml",

    "PRED_SV_ml":
        "PRED_SV_ml",

    "PRED_EF_pct":
        "PRED_EF_pct"
}


print("=" * 100)
print("PHASE 2 → PHASE 3 FEATURE CONTRACT")
print("=" * 100)


for phase2_name, phase3_name in (
    PHASE2_TO_PHASE3_FEATURE_MAP.items()
):

    print(
        f"{phase2_name:<25} → {phase3_name}"
    )


missing_phase2_columns = [

    column

    for column
    in PHASE2_TO_PHASE3_FEATURE_MAP.keys()

    if column
    not in phase2_frozen_patient_df.columns
]


assert not missing_phase2_columns, (
    f"Missing Phase 2 columns: "
    f"{missing_phase2_columns}"
)


print(
    "\n✓ Phase 2 → Phase 3 feature contract defined."
)

====================================================================================================
PHASE 2 → PHASE 3 FEATURE CONTRACT
====================================================================================================
ED_PRED_area_mm2          → PRED_ED_area_mm2
ES_PRED_area_mm2          → PRED_ES_area_mm2
ED_PRED_length_mm         → PRED_ED_length_mm
ES_PRED_length_mm         → PRED_ES_length_mm
ED_PRED_volume_ml         → PRED_EDV_ml
ES_PRED_volume_ml         → PRED_ESV_ml
PRED_SV_ml                → PRED_SV_ml
PRED_EF_pct               → PRED_EF_pct

✓ Phase 2 → Phase 3 feature contract defined.

In [ ]:
# ================================================================
# PHASE 5B — CELL 24
# VERIFY EXACT PHASE 2 → PHASE 3 NUMERICAL HANDOFF
# ================================================================

phase2_for_comparison_df = (
    phase2_frozen_patient_df[
        ["patient_id"]
        +
        list(
            PHASE2_TO_PHASE3_FEATURE_MAP.keys()
        )
    ]
    .rename(
        columns=
        PHASE2_TO_PHASE3_FEATURE_MAP
    )
)


phase2_phase3_comparison_df = (

    phase2_for_comparison_df

    .merge(

        phase3_frozen_predictions_df[
            ["patient_id"]
            +
            PHASE3_FEATURE_COLUMNS
        ],

        on="patient_id",

        how="inner",

        suffixes=(
            "_phase2",
            "_phase3"
        )
    )
)


assert len(
    phase2_phase3_comparison_df
) == 50


print("=" * 100)
print("PHASE 2 → PHASE 3 NUMERICAL CONSISTENCY")
print("=" * 100)

print(
    "\nMatched patients:",
    len(
        phase2_phase3_comparison_df
    )
)


phase2_phase3_max_differences = {}


for feature in PHASE3_FEATURE_COLUMNS:

    phase2_values = (
        phase2_phase3_comparison_df[
            f"{feature}_phase2"
        ]
        .to_numpy(
            dtype=float
        )
    )

    phase3_values = (
        phase2_phase3_comparison_df[
            f"{feature}_phase3"
        ]
        .to_numpy(
            dtype=float
        )
    )

    absolute_difference = np.abs(
        phase2_values
        -
        phase3_values
    )

    max_difference = float(
        absolute_difference.max()
    )

    phase2_phase3_max_differences[
        feature
    ] = max_difference

    print(
        f"\n{feature}"
    )

    print(
        "  max |Phase 2 - Phase 3| =",
        f"{max_difference:.12f}"
    )


overall_max_phase2_phase3_difference = max(
    phase2_phase3_max_differences.values()
)


print(
    "\nOverall maximum difference:",
    f"{overall_max_phase2_phase3_difference:.12f}"
)


assert (
    overall_max_phase2_phase3_difference
    < 1e-10
), (
    "Phase 2 → Phase 3 numerical handoff "
    "does not reproduce exactly."
)


print(
    "\n✓ Frozen Phase 2 quantitative outputs "
    "match Phase 3 classifier inputs exactly."
)

====================================================================================================
PHASE 2 → PHASE 3 NUMERICAL CONSISTENCY
====================================================================================================

Matched patients: 50

PRED_ED_area_mm2
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_ES_area_mm2
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_ED_length_mm
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_ES_length_mm
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_EDV_ml
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_ESV_ml
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_SV_ml
  max |Phase 2 - Phase 3| = 0.000000000000

PRED_EF_pct
  max |Phase 2 - Phase 3| = 0.000000000000

Overall maximum difference: 0.000000000000

✓ Frozen Phase 2 quantitative outputs match Phase 3 classifier inputs exactly.

In [ ]:
# ================================================================
# PHASE 5B — CELL 25
# VERIFY FROZEN PHASE 2 QUANTITATIVE EQUATIONS
# ================================================================

def area_length_volume_ml(
    area_mm2,
    length_mm
):
    """
    Single-plane area-length volume.

    Inputs
    ------
    area_mm2 : float or array
        LV cavity area in mm^2.

    length_mm : float or array
        PCA major-axis length in mm.

    Returns
    -------
    volume_ml : float or array
        Estimated volume in mL.
    """

    area_cm2 = (
        np.asarray(
            area_mm2,
            dtype=float
        )
        / 100.0
    )

    length_cm = (
        np.asarray(
            length_mm,
            dtype=float
        )
        / 10.0
    )

    volume_ml = (
        8.0
        /
        (
            3.0
            *
            np.pi
        )
    ) * (
        area_cm2 ** 2
        /
        length_cm
    )

    return volume_ml


recomputed_EDV_ml = area_length_volume_ml(

    phase2_frozen_patient_df[
        "ED_PRED_area_mm2"
    ],

    phase2_frozen_patient_df[
        "ED_PRED_length_mm"
    ]
)


recomputed_ESV_ml = area_length_volume_ml(

    phase2_frozen_patient_df[
        "ES_PRED_area_mm2"
    ],

    phase2_frozen_patient_df[
        "ES_PRED_length_mm"
    ]
)


recomputed_SV_ml = (
    recomputed_EDV_ml
    -
    recomputed_ESV_ml
)


recomputed_EF_pct = (

    recomputed_SV_ml
    /
    recomputed_EDV_ml

) * 100.0


equation_checks = {

    "EDV_ml":
        np.max(
            np.abs(
                recomputed_EDV_ml
                -
                phase2_frozen_patient_df[
                    "ED_PRED_volume_ml"
                ].to_numpy()
            )
        ),

    "ESV_ml":
        np.max(
            np.abs(
                recomputed_ESV_ml
                -
                phase2_frozen_patient_df[
                    "ES_PRED_volume_ml"
                ].to_numpy()
            )
        ),

    "SV_ml":
        np.max(
            np.abs(
                recomputed_SV_ml
                -
                phase2_frozen_patient_df[
                    "PRED_SV_ml"
                ].to_numpy()
            )
        ),

    "EF_pct":
        np.max(
            np.abs(
                recomputed_EF_pct
                -
                phase2_frozen_patient_df[
                    "PRED_EF_pct"
                ].to_numpy()
            )
        )
}


print("=" * 100)
print("PHASE 2 EQUATION REPRODUCTION")
print("=" * 100)


for quantity, difference in (
    equation_checks.items()
):

    print(
        f"\n{quantity}"
    )

    print(
        "  Maximum absolute difference:",
        f"{difference:.12f}"
    )


overall_equation_difference = max(
    equation_checks.values()
)


assert overall_equation_difference < 1e-10


print(
    "\n✓ Area-length volume equation reproduced."
)

print(
    "✓ EDV/ESV → SV reproduced."
)

print(
    "✓ SV/EDV → EF reproduced."
)

====================================================================================================
PHASE 2 EQUATION REPRODUCTION
====================================================================================================

EDV_ml
  Maximum absolute difference: 0.000000000000

ESV_ml
  Maximum absolute difference: 0.000000000000

SV_ml
  Maximum absolute difference: 0.000000000000

EF_pct
  Maximum absolute difference: 0.000000000000

✓ Area-length volume equation reproduced.
✓ EDV/ESV → SV reproduced.
✓ SV/EDV → EF reproduced.

In [ ]:
# ================================================================
# PHASE 5B — CELL 26
# LOCATE ORIGINAL PHASE 1 / PHASE 2 IMPLEMENTATION NOTEBOOKS
# ================================================================

search_roots = [
    PROJECT_ROOT / "phase1_segmentation",
    PROJECT_ROOT / "phase2_quantitative"
]

source_files = []

for root in search_roots:

    if not root.exists():
        continue

    for path in root.rglob("*"):

        if (
            path.is_file()
            and path.suffix.lower() in {
                ".ipynb",
                ".py"
            }
        ):
            source_files.append(path)


source_files = sorted(source_files)


print("=" * 105)
print("PHASE 1 / PHASE 2 SOURCE FILE DISCOVERY")
print("=" * 105)

print(
    f"\nSource files found: {len(source_files)}"
)


for index, path in enumerate(
    source_files,
    start=1
):

    print(
        f"{index:02d}. "
        f"{path.relative_to(PROJECT_ROOT)}"
    )

=========================================================================================================
PHASE 1 / PHASE 2 SOURCE FILE DISCOVERY
=========================================================================================================

Source files found: 0

In [ ]:
# ================================================================
# PHASE 5B — CELL 27
# SEARCH GOOGLE DRIVE FOR ORIGINAL PHASE 2 NOTEBOOKS
# ================================================================

DRIVE_ROOT = Path("/content/drive/MyDrive")


all_drive_notebooks = sorted(
    [
        path
        for path in DRIVE_ROOT.rglob("*.ipynb")
        if path.is_file()
    ]
)


print("=" * 105)
print("GOOGLE DRIVE NOTEBOOK DISCOVERY")
print("=" * 105)

print(
    f"\nTotal .ipynb files found in MyDrive: "
    f"{len(all_drive_notebooks)}"
)


likely_keywords = [
    "phase2",
    "phase_2",
    "quantitative",
    "measurement",
    "echo",
    "camus",
    "lv"
]


likely_phase2_notebooks = []


for path in all_drive_notebooks:

    path_text = str(path).lower()

    if any(
        keyword in path_text
        for keyword in likely_keywords
    ):
        likely_phase2_notebooks.append(path)


print(
    f"\nLikely relevant notebooks: "
    f"{len(likely_phase2_notebooks)}"
)

print("\n" + "-" * 105)


for index, path in enumerate(
    likely_phase2_notebooks,
    start=1
):

    print(
        f"{index:02d}. "
        f"{path.relative_to(DRIVE_ROOT)}"
    )

=========================================================================================================
GOOGLE DRIVE NOTEBOOK DISCOVERY
=========================================================================================================

Total .ipynb files found in MyDrive: 35

Likely relevant notebooks: 7

---------------------------------------------------------------------------------------------------------
01. Colab Notebooks/CAMUS_Metadata_Target_Audit.ipynb
02. Colab Notebooks/Phase2A_LV_Quantitative_Analysis.ipynb
03. Colab Notebooks/Phase2B_Final_Quantitative_Evaluation.ipynb
04. Colab Notebooks/phase_2.ipynb
05. Phase_2_Improved_Final_Analysis (1).ipynb
06. Phase_2_Improved_Final_Analysis.ipynb
07. camus_lv_project/phase2_revised.ipynb

In [ ]:
# ================================================================
# PHASE 5B — CELL 27B
# FALLBACK: LIST ALL GOOGLE DRIVE NOTEBOOKS
# ================================================================

print("=" * 105)
print("ALL GOOGLE DRIVE NOTEBOOKS")
print("=" * 105)


for index, path in enumerate(
    all_drive_notebooks,
    start=1
):

    print(
        f"{index:03d}. "
        f"{path.relative_to(DRIVE_ROOT)}"
    )

=========================================================================================================
ALL GOOGLE DRIVE NOTEBOOKS
=========================================================================================================
001. Colab Notebooks/CAMUS_Metadata_Target_Audit.ipynb
002. Colab Notebooks/Phase _2.5 _Validation_Audit.ipynb
003. Colab Notebooks/Phase1A_Clean_Baseline_and_Resolution.ipynb
004. Colab Notebooks/Phase1B2_Clean_Optimizer_Experiment.ipynb
005. Colab Notebooks/Phase1B3_Clean_Batch_Size_Experiment.ipynb
006. Colab Notebooks/Phase1B4_Clean_Augmentation_Experiment.ipynb
007. Colab Notebooks/Phase1B_Clean_Hyperparameter_Experiments.ipynb
008. Colab Notebooks/Phase1C_Clean_Model_Capacity_Experiment.ipynb
009. Colab Notebooks/Phase1D_Clean_Loss_Function_Experiment.ipynb
010. Colab Notebooks/Phase1E_Final_Segmentation_Validation.ipynb
011. Colab Notebooks/Phase1F_Freeze_Final_Segmentation_Model.ipynb
012. Colab Notebooks/Phase2A_LV_Quantitative_Analysis.ipynb
013. Colab Notebooks/Phase2B_Final_Quantitative_Evaluation.ipynb
014. Colab Notebooks/Phase3A_EF_Classification_Design_and_Label_Audit.ipynb
015. Colab Notebooks/Phase3B_Direct_Geometry_Classification_Baseline.ipynb
016. Colab Notebooks/Phase3C_Learned_Classifier_Development (1).ipynb
017. Colab Notebooks/Phase3C_Learned_Classifier_Development.ipynb
018. Colab Notebooks/Phase3D_Final_Locked_Evaluation.ipynb
019. Colab Notebooks/Phase4A_End_to_End_Error_Propagation.ipynb
020. Colab Notebooks/Phase4B_Confidence_and_Uncertainty_Analysis.ipynb
021. Colab Notebooks/Phase4C_Image_Quality_and_Failure_Subgroups.ipynb
022. Colab Notebooks/Phase4D_Representative_Failure_Cases.ipynb
023. Colab Notebooks/Phase5A_Final_System_Specification.ipynb
024. Colab Notebooks/Phase5B_Integrated_Frozen_Inference_Pipeline.ipynb
025. Colab Notebooks/Untitled0.ipynb
026. Colab Notebooks/Untitled1.ipynb
027. Colab Notebooks/Untitled2.ipynb
028. Colab Notebooks/phase1_2.ipynb
029. Colab Notebooks/phase3.ipynb
030. Colab Notebooks/phase3_diagnostic_and_improvement.ipynb
031. Colab Notebooks/phase3_revised.ipynb
032. Colab Notebooks/phase_2.ipynb
033. Phase_2_Improved_Final_Analysis (1).ipynb
034. Phase_2_Improved_Final_Analysis.ipynb
035. camus_lv_project/phase2_revised.ipynb

In [ ]:
# ================================================================
# PHASE 5B — CELL 28
# EXTRACT AUTHORITATIVE PHASE 2A MEASUREMENT IMPLEMENTATION
# ================================================================

import nbformat


PHASE2A_NOTEBOOK_PATH = (
    DRIVE_ROOT
    / "Colab Notebooks"
    / "Phase2A_LV_Quantitative_Analysis.ipynb"
)


assert PHASE2A_NOTEBOOK_PATH.exists(), (
    f"Notebook not found:\n{PHASE2A_NOTEBOOK_PATH}"
)


phase2A_notebook = nbformat.read(
    PHASE2A_NOTEBOOK_PATH,
    as_version=4
)


phase2A_search_terms = [

    "def ",
    "pca",
    "feret",
    "spacing",
    "area_mm2",
    "length_mm",
    "volume",
    "resize",
    "connected",
    "fill_holes",
    "binary_fill",
    "predict",
    "nifti",
    "header",
    "pixdim"
]


phase2A_relevant_cells = []


print("=" * 110)
print("AUTHORITATIVE PHASE 2A — RELEVANT CODE CELLS")
print("=" * 110)


for cell_index, cell in enumerate(
    phase2A_notebook.cells
):

    if cell.cell_type != "code":
        continue

    source = cell.source

    matched_terms = [
        term
        for term in phase2A_search_terms
        if term.lower() in source.lower()
    ]

    if matched_terms:

        phase2A_relevant_cells.append(
            {
                "cell_index": cell_index,
                "matched_terms": matched_terms,
                "source": source
            }
        )

        print("\n" + "=" * 110)

        print(
            f"NOTEBOOK CELL INDEX: {cell_index}"
        )

        print(
            "MATCHED:",
            ", ".join(matched_terms)
        )

        print("-" * 110)

        print(source)


print(
    "\nRelevant Phase 2A code cells found:",
    len(phase2A_relevant_cells)
)

==============================================================================================================
AUTHORITATIVE PHASE 2A — RELEVANT CODE CELLS
==============================================================================================================

==============================================================================================================
NOTEBOOK CELL INDEX: 1
MATCHED: fill_holes, binary_fill
--------------------------------------------------------------------------------------------------------------
import os
import gc
import json
import random
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import cv2
import nibabel as nib
import tensorflow as tf

from scipy.ndimage import binary_fill_holes
from scipy.spatial.distance import cdist


SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

try:
    tf.config.experimental.enable_op_determinism()
except Exception:
    pass


print("TensorFlow:", tf.__version__)

gpus = tf.config.list_physical_devices("GPU")
print("GPU(s):", gpus)

==============================================================================================================
NOTEBOOK CELL INDEX: 2
MATCHED: predict
--------------------------------------------------------------------------------------------------------------
PROJECT_DIR = Path(
    "/content/drive/MyDrive/CAMUS_FINAL"
)

PHASE1F_DIR = (
    PROJECT_DIR /
    "phase1_segmentation" /
    "phase1F_final_model"
)

PHASE2_DIR = (
    PROJECT_DIR /
    "phase2_quantitative"
)

P2A_DIR = (
    PHASE2_DIR /
    "phase2A_measurement_method"
)

P2A_CONFIG_DIR = (
    P2A_DIR /
    "configs"
)

P2A_TABLE_DIR = (
    P2A_DIR /
    "tables"
)

P2A_PLOT_DIR = (
    P2A_DIR /
    "plots"
)

P2A_PREDICTION_DIR = (
    P2A_DIR /
    "predictions"
)


for folder in [
    P2A_CONFIG_DIR,
    P2A_TABLE_DIR,
    P2A_PLOT_DIR,
    P2A_PREDICTION_DIR
]:
    folder.mkdir(
        parents=True,
        exist_ok=True
    )


print("Phase 2A directory:")
print(P2A_DIR)

print("\n✓ Phase 2A folders ready.")

==============================================================================================================
NOTEBOOK CELL INDEX: 4
MATCHED: def
--------------------------------------------------------------------------------------------------------------
def sha256_file(file_path):

    sha = hashlib.sha256()

    with open(
        file_path,
        "rb"
    ) as f:

        while True:

            chunk = f.read(
                1024 * 1024
            )

            if not chunk:
                break

            sha.update(chunk)

    return sha.hexdigest()


CURRENT_MODEL_SHA256 = (
    sha256_file(
        FINAL_MODEL_PATH
    )
)


assert (
    CURRENT_MODEL_SHA256
    ==
    EXPECTED_MODEL_SHA256
)


print("=" * 70)
print("MODEL INTEGRITY VERIFIED")
print("=" * 70)

print(
    "\nSHA-256 matches Phase 1F manifest:"
)

print(True)

print(
    "\n✓ Correct frozen segmentation "
    "model confirmed."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 5
MATCHED: connected
--------------------------------------------------------------------------------------------------------------
with open(
    FINAL_CONFIG_PATH,
    "r"
) as f:
    segmentation_config = json.load(f)


assert (
    segmentation_config[
        "frozen"
    ]
    is True
)

assert (
    segmentation_config[
        "input"
    ][
        "resolution"
    ]
    == [256, 256]
)

assert np.isclose(
    segmentation_config[
        "inference"
    ][
        "threshold"
    ],
    0.50
)


SEGMENTATION_RESOLUTION = 256
SEGMENTATION_THRESHOLD = 0.50


print("=" * 70)
print("SEGMENTATION CONFIGURATION")
print("=" * 70)

print("\nResolution : 256×256")
print("Threshold  : 0.50")
print(
    "Postprocess: largest connected "
    "component + hole filling"
)

print(
    "\n✓ Segmentation configuration locked."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 6
MATCHED: nifti
--------------------------------------------------------------------------------------------------------------
import zipfile

OUTER_ZIP_PATH = Path(
    "/content/drive/MyDrive/download.zip"
)

OUTER_EXTRACT_DIR = Path(
    "/content/camus_data"
)

INNER_ARCHIVE_PATH = (
    OUTER_EXTRACT_DIR /
    "download"
)

INNER_EXTRACT_DIR = Path(
    "/content/camus_data_final"
)

DATASET_PATH = (
    INNER_EXTRACT_DIR /
    "database_nifti"
)


if not DATASET_PATH.exists():

    assert OUTER_ZIP_PATH.exists(), (
        f"Archive not found: {OUTER_ZIP_PATH}"
    )

    if not INNER_ARCHIVE_PATH.exists():

        print("Extracting outer archive...")

        OUTER_EXTRACT_DIR.mkdir(
            parents=True,
            exist_ok=True
        )

        with zipfile.ZipFile(
            OUTER_ZIP_PATH,
            "r"
        ) as archive:

            archive.extractall(
                OUTER_EXTRACT_DIR
            )

        print("✓ Outer archive extracted.")


    print("Extracting CAMUS archive...")

    INNER_EXTRACT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    with zipfile.ZipFile(
        INNER_ARCHIVE_PATH,
        "r"
    ) as archive:

        archive.extractall(
            INNER_EXTRACT_DIR
        )


assert DATASET_PATH.exists()

print("\n✓ CAMUS dataset ready:")
print(DATASET_PATH)

==============================================================================================================
NOTEBOOK CELL INDEX: 8
MATCHED: def , spacing, nifti, header
--------------------------------------------------------------------------------------------------------------
def parse_info_cfg(cfg_path):

    info = {}

    with open(
        cfg_path,
        "r",
        encoding="utf-8"
    ) as f:

        for raw in f:

            line = raw.strip()

            if (
                not line
                or line.startswith("#")
                or ":" not in line
            ):
                continue

            key, value = line.split(
                ":",
                1
            )

            key = key.strip()
            value = value.strip()

            try:
                value = int(value)

            except ValueError:

                try:
                    value = float(value)

                except ValueError:
                    pass

            info[key] = value

    return info


def load_nifti_2d(file_path):

    nii = nib.load(
        str(file_path)
    )

    data = np.asarray(
        nii.get_fdata()
    )

    if (
        data.ndim == 3
        and data.shape[-1] == 1
    ):
        data = data[:, :, 0]

    if data.ndim != 2:

        raise ValueError(
            f"Expected 2D NIfTI, "
            f"got {data.shape}"
        )

    spacing = tuple(
        float(x)
        for x in
        nii.header.get_zooms()[:2]
    )

    return (
        data,
        spacing
    )


def load_patient_data(
    patient_id
):

    patient_dir = (
        DATASET_PATH /
        patient_id
    )

    clinical = parse_info_cfg(
        patient_dir /
        "Info_4CH.cfg"
    )

    patient = {

        "patient_id":
            patient_id,

        "clinical":
            clinical
    }


    for phase in [
        "ED",
        "ES"
    ]:

        image, spacing = (
            load_nifti_2d(
                patient_dir /
                f"{patient_id}_4CH_{phase}.nii.gz"
            )
        )

        gt, gt_spacing = (
            load_nifti_2d(
                patient_dir /
                f"{patient_id}_4CH_{phase}_gt.nii.gz"
            )
        )


        assert np.allclose(
            spacing,
            gt_spacing
        )


        patient[phase] = {

            "image":
                image.astype(
                    np.float32
                ),

            "mask":
                (gt == 1),

            "spacing":
                spacing,

            "original_shape":
                image.shape
        }


    return patient


sample_patient = load_patient_data(
    test_ids[0]
)


print("=" * 70)
print("SAMPLE PHYSICAL DATA CHECK")
print("=" * 70)

print(
    "\nPatient:",
    sample_patient[
        "patient_id"
    ]
)

for phase in ["ED", "ES"]:

    print(
        f"\n{phase}:"
    )

    print(
        "Shape:",
        sample_patient[
            phase
        ][
            "original_shape"
        ]
    )

    print(
        "Spacing:",
        sample_patient[
            phase
        ][
            "spacing"
        ]
    )

    print(
        "LV pixels:",
        int(
            sample_patient[
                phase
            ][
                "mask"
            ].sum()
        )
    )

==============================================================================================================
NOTEBOOK CELL INDEX: 9
MATCHED: def , spacing, resize
--------------------------------------------------------------------------------------------------------------
def preprocess_for_segmentation(
    image,
    target_size=256
):

    image = np.asarray(
        image,
        dtype=np.float32
    )

    original_h, original_w = (
        image.shape
    )


    resized = cv2.resize(
        image,
        (
            target_size,
            target_size
        ),
        interpolation=cv2.INTER_LINEAR
    )


    minimum = float(
        resized.min()
    )

    maximum = float(
        resized.max()
    )


    if maximum > minimum:

        normalized = (
            resized - minimum
        ) / (
            maximum - minimum
        )

    else:

        normalized = (
            np.zeros_like(
                resized
            )
        )


    scale_x = (
        original_w /
        target_size
    )

    scale_y = (
        original_h /
        target_size
    )


    return (
        normalized.astype(
            np.float32
        ),
        (
            scale_x,
            scale_y
        )
    )


def preprocess_mask(
    mask,
    target_size=256
):

    resized = cv2.resize(
        np.asarray(
            mask
        ).astype(
            np.uint8
        ),
        (
            target_size,
            target_size
        ),
        interpolation=cv2.INTER_NEAREST
    )

    return (
        resized > 0
    )


def effective_spacing(
    native_spacing,
    scale_factors
):

    spacing_x, spacing_y = map(
        float,
        native_spacing
    )

    scale_x, scale_y = map(
        float,
        scale_factors
    )

    return (
        spacing_x * scale_x,
        spacing_y * scale_y
    )


print(
    "✓ Resize geometry and "
    "effective-spacing functions ready."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 10
MATCHED: spacing, area_mm2, resize
--------------------------------------------------------------------------------------------------------------
sample_phase = "ED"

sample_image = (
    sample_patient[
        sample_phase
    ][
        "image"
    ]
)

sample_mask_native = (
    sample_patient[
        sample_phase
    ][
        "mask"
    ]
)

sample_native_spacing = (
    sample_patient[
        sample_phase
    ][
        "spacing"
    ]
)


_, sample_scale = (
    preprocess_for_segmentation(
        sample_image
    )
)

sample_mask_resized = (
    preprocess_mask(
        sample_mask_native
    )
)

sample_effective_spacing = (
    effective_spacing(
        sample_native_spacing,
        sample_scale
    )
)


native_area_mm2 = (

    sample_mask_native.sum()

    *

    sample_native_spacing[0]

    *

    sample_native_spacing[1]
)


resized_area_mm2 = (

    sample_mask_resized.sum()

    *

    sample_effective_spacing[0]

    *

    sample_effective_spacing[1]
)


area_difference_pct = (

    (
        resized_area_mm2
        -
        native_area_mm2
    )

    /

    native_area_mm2

    *

    100.0
)


print("=" * 70)
print("PHYSICAL AREA SANITY CHECK")
print("=" * 70)

print(
    f"\nNative area  : "
    f"{native_area_mm2:.2f} mm²"
)

print(
    f"Resized area : "
    f"{resized_area_mm2:.2f} mm²"
)

print(
    f"Difference   : "
    f"{area_difference_pct:+.3f}%"
)

print(
    "\nNative spacing:",
    sample_native_spacing
)

print(
    "Effective resized spacing:",
    sample_effective_spacing
)

==============================================================================================================
NOTEBOOK CELL INDEX: 11
MATCHED: pca, feret, volume
--------------------------------------------------------------------------------------------------------------
phase2a_protocol = {

    "phase":
        "Phase 2A — LV Quantitative Measurement Method",

    "purpose":
        (
            "Establish and validate the quantitative "
            "measurement methodology used downstream "
            "of the frozen LV segmentation model."
        ),

    "segmentation_model_frozen":
        True,

    "segmentation_model":
        str(
            FINAL_MODEL_PATH
        ),

    "segmentation_model_sha256":
        EXPECTED_MODEL_SHA256,

    "segmentation_changes_allowed":
        False,

    "target_view":
        "A4C",

    "target_structure":
        "LV cavity",

    "phases":
        ["ED", "ES"],

    "physical_units": {
        "area":
            "mm^2",
        "length":
            "mm",
        "volume":
            "mL",
        "EF":
            "%"
    },

    "candidate_long_axis_methods": [
        "maximum_feret",
        "PCA_major_axis"
    ],

    "volume_method":
        "single-plane area-length",

    "volume_equation":
        "V = (8 / (3*pi)) * (A^2 / L)",

    "method_selection_principle":
        (
            "Geometry methods will first be evaluated "
            "using ground-truth LV masks so that "
            "measurement-model error is separated from "
            "segmentation error."
        ),

    "downstream_quantities": [
        "ED area",
        "ES area",
        "ED long-axis length",
        "ES long-axis length",
        "EDV",
        "ESV",
        "SV",
        "EF"
    ],

    "test_exposure_note":
        (
            "The current 50-patient evaluation partition "
            "was previously inspected during historical "
            "pilot development. It was excluded from the "
            "clean Phase 1A-1D model-selection process, "
            "but is not claimed to be a pristine external "
            "test set."
        )
}


P2A_PROTOCOL_PATH = (
    P2A_CONFIG_DIR /
    "phase2A_measurement_protocol.json"
)


with open(
    P2A_PROTOCOL_PATH,
    "w"
) as f:

    json.dump(
        phase2a_protocol,
        f,
        indent=2
    )


print("=" * 70)
print("PHASE 2A PROTOCOL FROZEN")
print("=" * 70)

print(
    "\nSegmentation model changes: NO"
)

print(
    "Candidate geometry methods:"
)

print(
    "  1. Maximum Feret"
)

print(
    "  2. PCA major axis"
)

print(
    "\nVolume method:"
)

print(
    "  Single-plane area-length"
)

print(
    "\nGround-truth geometry will "
    "be examined first."
)

print("\nSaved:")
print(P2A_PROTOCOL_PATH)

==============================================================================================================
NOTEBOOK CELL INDEX: 13
MATCHED: def , pca, feret, spacing, area_mm2, length_mm, volume
--------------------------------------------------------------------------------------------------------------
# ================================================================
# PHASE 2A — CELL 14
# PHYSICAL LV GEOMETRY FUNCTIONS
# ================================================================

def mask_area_mm2(
    mask,
    spacing
):

    mask = np.asarray(
        mask
    ).astype(bool)

    spacing_x, spacing_y = map(
        float,
        spacing
    )

    return float(
        mask.sum()
        *
        spacing_x
        *
        spacing_y
    )


def mask_points_mm(
    mask,
    spacing
):

    mask = np.asarray(
        mask
    ).astype(bool)

    rows, cols = np.where(
        mask
    )

    spacing_x, spacing_y = map(
        float,
        spacing
    )

    # x corresponds to image columns
    # y corresponds to image rows

    x_mm = (
        cols.astype(np.float64)
        *
        spacing_x
    )

    y_mm = (
        rows.astype(np.float64)
        *
        spacing_y
    )

    return np.column_stack([
        x_mm,
        y_mm
    ])


def maximum_feret_mm(
    mask,
    spacing
):

    points = mask_points_mm(
        mask,
        spacing
    )

    if len(points) < 2:
        return np.nan


    hull = cv2.convexHull(
        points.astype(
            np.float32
        )
    ).reshape(-1, 2)


    if len(hull) < 2:
        return np.nan


    differences = (
        hull[:, None, :]
        -
        hull[None, :, :]
    )

    distances_squared = (
        differences ** 2
    ).sum(axis=2)


    return float(
        np.sqrt(
            distances_squared.max()
        )
    )


def pca_major_axis_mm(
    mask,
    spacing
):

    points = mask_points_mm(
        mask,
        spacing
    )

    if len(points) < 2:
        return np.nan


    centered = (
        points
        -
        points.mean(
            axis=0
        )
    )


    covariance = np.cov(
        centered,
        rowvar=False
    )


    eigenvalues, eigenvectors = (
        np.linalg.eigh(
            covariance
        )
    )


    principal_axis = (
        eigenvectors[
            :,
            np.argmax(
                eigenvalues
            )
        ]
    )


    projections = (
        centered
        @
        principal_axis
    )


    return float(
        projections.max()
        -
        projections.min()
    )


def area_length_volume_ml(
    area_mm2,
    length_mm
):

    if (
        not np.isfinite(area_mm2)
        or not np.isfinite(length_mm)
        or area_mm2 <= 0
        or length_mm <= 0
    ):
        return np.nan


    # Convert:
    # mm² -> cm²
    # mm  -> cm

    area_cm2 = (
        area_mm2 /
        100.0
    )

    length_cm = (
        length_mm /
        10.0
    )


    volume_ml = (
        8.0
        /
        (
            3.0
            *
            np.pi
        )
        *
        (
            area_cm2 ** 2
        )
        /
        length_cm
    )


    return float(
        volume_ml
    )


print(
    "✓ Physical LV geometry "
    "functions ready."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 14
MATCHED: pca, feret, spacing, area_mm2, length_mm, volume
--------------------------------------------------------------------------------------------------------------
# ================================================================
# PHASE 2A — CELL 15
# SAMPLE GT GEOMETRY CHECK
# ================================================================

sample_geometry = []


for phase in [
    "ED",
    "ES"
]:

    phase_data = (
        sample_patient[
            phase
        ]
    )

    native_mask = (
        phase_data[
            "mask"
        ]
    )

    native_spacing = (
        phase_data[
            "spacing"
        ]
    )


    area_mm2 = mask_area_mm2(
        native_mask,
        native_spacing
    )


    feret_length = (
        maximum_feret_mm(
            native_mask,
            native_spacing
        )
    )


    pca_length = (
        pca_major_axis_mm(
            native_mask,
            native_spacing
        )
    )


    feret_volume = (
        area_length_volume_ml(
            area_mm2,
            feret_length
        )
    )


    pca_volume = (
        area_length_volume_ml(
            area_mm2,
            pca_length
        )
    )


    sample_geometry.append({

        "phase":
            phase,

        "area_mm2":
            area_mm2,


In [ ]:
# ================================================================
# PHASE 5B — CELL 29
# EXTRACT AUTHORITATIVE PHASE 1F INFERENCE IMPLEMENTATION
# ================================================================

PHASE1F_NOTEBOOK_PATH = (
    DRIVE_ROOT
    / "Colab Notebooks"
    / "Phase1F_Freeze_Final_Segmentation_Model.ipynb"
)


assert PHASE1F_NOTEBOOK_PATH.exists(), (
    f"Notebook not found:\n{PHASE1F_NOTEBOOK_PATH}"
)


phase1F_notebook = nbformat.read(
    PHASE1F_NOTEBOOK_PATH,
    as_version=4
)


phase1F_search_terms = [

    "def ",
    "normalize",
    "resize",
    "predict",
    "threshold",
    "connected",
    "component",
    "fill_holes",
    "binary_fill",
    "load_model",
    "nib",
    "nifti"
]


phase1F_relevant_cells = []


print("=" * 110)
print("AUTHORITATIVE PHASE 1F — RELEVANT CODE CELLS")
print("=" * 110)


for cell_index, cell in enumerate(
    phase1F_notebook.cells
):

    if cell.cell_type != "code":
        continue

    source = cell.source

    matched_terms = [
        term
        for term in phase1F_search_terms
        if term.lower() in source.lower()
    ]

    if matched_terms:

        phase1F_relevant_cells.append(
            {
                "cell_index": cell_index,
                "matched_terms": matched_terms,
                "source": source
            }
        )

        print("\n" + "=" * 110)

        print(
            f"NOTEBOOK CELL INDEX: {cell_index}"
        )

        print(
            "MATCHED:",
            ", ".join(matched_terms)
        )

        print("-" * 110)

        print(source)


print(
    "\nRelevant Phase 1F code cells found:",
    len(phase1F_relevant_cells)
)

==============================================================================================================
AUTHORITATIVE PHASE 1F — RELEVANT CODE CELLS
==============================================================================================================

==============================================================================================================
NOTEBOOK CELL INDEX: 4
MATCHED: threshold
--------------------------------------------------------------------------------------------------------------
final_config = (
    phase1e_record[
        "final_configuration"
    ]
)


assert (
    final_config["resolution"]
    == 256
)

assert (
    final_config["architecture"]
    == "Large U-Net"
)

assert (
    final_config["filters"]
    == [32, 64, 128, 256, 512]
)

assert (
    final_config["parameters"]
    == 7_759_521
)

assert (
    final_config["optimizer"]
    == "Adam"
)

assert np.isclose(
    final_config[
        "learning_rate"
    ],
    1e-4
)

assert (
    final_config["batch_size"]
    == 2
)

assert (
    final_config["augmentation"]
    is False
)

assert (
    final_config["loss"]
    == "BCE + Dice"
)

assert np.isclose(
    final_config[
        "threshold"
    ],
    0.50
)


print("=" * 70)
print("ACCEPTED FINAL CONFIGURATION")
print("=" * 70)

print("\nResolution    : 256×256")
print("Architecture  : Large U-Net")
print("Filters       : [32, 64, 128, 256, 512]")
print("Parameters    : 7,759,521")
print("Optimizer     : Adam")
print("Learning rate : 1e-4")
print("Batch size    : 2")
print("Augmentation  : None")
print("Loss          : BCE + Dice")
print("Threshold     : 0.50")
print("Postprocess   : LCC + hole filling")

print(
    "\n✓ Configuration verified."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 5
MATCHED: def
--------------------------------------------------------------------------------------------------------------
def sha256_file(file_path):

    sha = hashlib.sha256()

    with open(
        file_path,
        "rb"
    ) as f:

        while True:

            chunk = f.read(
                1024 * 1024
            )

            if not chunk:
                break

            sha.update(chunk)

    return sha.hexdigest()


source_sha256 = sha256_file(
    SOURCE_CHECKPOINT
)


source_size_bytes = (
    SOURCE_CHECKPOINT
    .stat()
    .st_size
)


print("=" * 70)
print("SOURCE MODEL FINGERPRINT")
print("=" * 70)

print(
    "\nFile:",
    SOURCE_CHECKPOINT
)

print(
    "\nSize:",
    f"{source_size_bytes:,}",
    "bytes"
)

print(
    "\nSHA-256:"
)

print(source_sha256)

==============================================================================================================
NOTEBOOK CELL INDEX: 8
MATCHED: def
--------------------------------------------------------------------------------------------------------------
SMOOTH = 1e-6


def dice_coefficient(
    y_true,
    y_pred
):

    y_true = tf.cast(
        y_true,
        tf.float32
    )

    y_pred = tf.cast(
        y_pred,
        tf.float32
    )

    intersection = tf.reduce_sum(
        y_true * y_pred,
        axis=[1, 2, 3]
    )

    denominator = (
        tf.reduce_sum(
            y_true,
            axis=[1, 2, 3]
        )
        +
        tf.reduce_sum(
            y_pred,
            axis=[1, 2, 3]
        )
    )

    dice = (
        2.0 * intersection
        + SMOOTH
    ) / (
        denominator
        + SMOOTH
    )

    return tf.reduce_mean(
        dice
    )


def iou_metric(
    y_true,
    y_pred
):

    y_true = tf.cast(
        y_true,
        tf.float32
    )

    y_pred = tf.cast(
        y_pred,
        tf.float32
    )

    intersection = tf.reduce_sum(
        y_true * y_pred,
        axis=[1, 2, 3]
    )

    union = (
        tf.reduce_sum(
            y_true,
            axis=[1, 2, 3]
        )
        +
        tf.reduce_sum(
            y_pred,
            axis=[1, 2, 3]
        )
        -
        intersection
    )

    iou = (
        intersection
        + SMOOTH
    ) / (
        union
        + SMOOTH
    )

    return tf.reduce_mean(
        iou
    )


def dice_loss(
    y_true,
    y_pred
):

    return (
        1.0 -
        dice_coefficient(
            y_true,
            y_pred
        )
    )


def bce_dice_loss(
    y_true,
    y_pred
):

    bce = (
        tf.keras.losses
        .binary_crossentropy(
            y_true,
            y_pred
        )
    )

    bce = tf.reduce_mean(
        bce
    )

    return (
        bce +
        dice_loss(
            y_true,
            y_pred
        )
    )


CUSTOM_OBJECTS = {

    "bce_dice_loss":
        bce_dice_loss,

    "dice_loss":
        dice_loss,

    "dice_coefficient":
        dice_coefficient,

    "iou_metric":
        iou_metric
}


print("✓ Custom objects ready.")

==============================================================================================================
NOTEBOOK CELL INDEX: 9
MATCHED: load_model
--------------------------------------------------------------------------------------------------------------
tf.keras.backend.clear_session()
gc.collect()


source_segmentation_model = (
    tf.keras.models.load_model(
        SOURCE_CHECKPOINT,
        custom_objects=CUSTOM_OBJECTS,
        compile=False
    )
)


frozen_segmentation_model = (
    tf.keras.models.load_model(
        FINAL_MODEL_PATH,
        custom_objects=CUSTOM_OBJECTS,
        compile=False
    )
)


assert (
    source_segmentation_model.count_params()
    ==
    7_759_521
)

assert (
    frozen_segmentation_model.count_params()
    ==
    7_759_521
)

assert (
    source_segmentation_model.input_shape
    ==
    (None, 256, 256, 1)
)

assert (
    frozen_segmentation_model.input_shape
    ==
    (None, 256, 256, 1)
)

assert (
    source_segmentation_model.output_shape
    ==
    (None, 256, 256, 1)
)

assert (
    frozen_segmentation_model.output_shape
    ==
    (None, 256, 256, 1)
)


print("=" * 70)
print("MODEL-LEVEL VERIFICATION")
print("=" * 70)

print(
    "\nParameters:",
    f"{frozen_segmentation_model.count_params():,}"
)

print(
    "Input shape :",
    frozen_segmentation_model.input_shape
)

print(
    "Output shape:",
    frozen_segmentation_model.output_shape
)

print(
    "\n✓ Source and frozen models "
    "load successfully."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 10
MATCHED: predict
--------------------------------------------------------------------------------------------------------------
rng = np.random.default_rng(
    SEED
)

verification_input = (
    rng.random(
        (
            1,
            256,
            256,
            1
        ),
        dtype=np.float32
    )
)


source_prediction = (
    source_segmentation_model(
        verification_input,
        training=False
    )
    .numpy()
)


frozen_prediction = (
    frozen_segmentation_model(
        verification_input,
        training=False
    )
    .numpy()
)


max_abs_difference = float(
    np.max(
        np.abs(
            source_prediction
            -
            frozen_prediction
        )
    )
)


mean_abs_difference = float(
    np.mean(
        np.abs(
            source_prediction
            -
            frozen_prediction
        )
    )
)


assert np.array_equal(
    source_prediction,
    frozen_prediction
)


print("=" * 70)
print("PREDICTION EQUIVALENCE CHECK")
print("=" * 70)

print(
    "\nMaximum absolute difference:",
    max_abs_difference
)

print(
    "Mean absolute difference   :",
    mean_abs_difference
)

print(
    "\nExact prediction match:",
    np.array_equal(
        source_prediction,
        frozen_prediction
    )
)

print(
    "\n✓ Frozen model reproduces "
    "the source model exactly."
)

==============================================================================================================
NOTEBOOK CELL INDEX: 11
MATCHED: resize, threshold, connected, component, nifti
--------------------------------------------------------------------------------------------------------------
FINAL_CONFIG_PATH = (
    P1F_CONFIG_DIR /
    "final_segmentation_config.json"
)


final_segmentation_config = {

    "model_name":
        "CAMUS A4C LV Final Segmentation Model",

    "task":
        "Left ventricular cavity segmentation",

    "view":
        "A4C",

    "phases":
        ["ED", "ES"],

    "dataset":
        "CAMUS",

    "input": {

        "resolution":
            [256, 256],

        "channels":
            1,

        "normalization":
            "per-image min-max normalization",

        "resize":
            "stretch resize to 256x256"
    },

    "architecture": {

        "name":
            "Large U-Net",

        "filters":
            [32, 64, 128, 256, 512],

        "parameters":
            7_759_521,

        "output_activation":
            "sigmoid"
    },

    "training": {

        "optimizer":
            "Adam",

        "learning_rate":
            1e-4,

        "batch_size":
            2,

        "augmentation":
            False,

        "loss":
            "BCE + Dice",

        "maximum_epochs":
            30,

        "selected_checkpoint_epoch":
            int(
                phase1d_decision[
                    "selected_validation_results"
                ].get(
                    "best_epoch",
                    28
                )
            )
            if isinstance(
                phase1d_decision[
                    "selected_validation_results"
                ],
                dict
            )
            else 28,

        "seed":
            42
    },

    "inference": {

        "threshold":
            0.50,

        "postprocessing": [
            "largest connected component",
            "binary hole filling"
        ]
    },

    "final_model_path":
        str(
            FINAL_MODEL_PATH
        ),

    "sha256":
        final_sha256,

    "phase1e_test_results":
        phase1e_record[
            "final_test_results"
        ],

    "phase2_measurement_note":
        (
            "Quantitative physical measurements must use "
            "the original NIfTI pixel spacing and account "
            "for the geometric scaling introduced by "
            "256x256 stretch resizing."
        ),

    "frozen":
        True
}


with open(
    FINAL_CONFIG_PATH,
    "w"
) as f:

    json.dump(
        final_segmentation_config,
        f,
        indent=2
    )


print("Final configuration saved:")
print(FINAL_CONFIG_PATH)

==============================================================================================================
NOTEBOOK CELL INDEX: 12
MATCHED: predict
--------------------------------------------------------------------------------------------------------------
MANIFEST_PATH = (
    P1F_CONFIG_DIR /
    "final_segmentation_manifest.json"
)


final_manifest = {

    "status":
        "FROZEN",

    "project":
        "Computer Vision Based Assistive Application for Analyzing ECHO Scans — LV A4C",

    "phase":
        "Phase 1F — Freeze Final Segmentation Model",

    "source_checkpoint":
        str(
            SOURCE_CHECKPOINT
        ),

    "frozen_model":
        str(
            FINAL_MODEL_PATH
        ),

    "source_sha256":
        source_sha256,

    "frozen_sha256":
        final_sha256,

    "byte_identical":
        bool(
            source_sha256
            ==
            final_sha256
        ),

    "prediction_equivalence_verified":
        True,

    "prediction_max_abs_difference":
        max_abs_difference,

    "selection_history": {

        "Phase_1A":
            (
                "256x256 resolution selected"
            ),

        "Phase_1B1":
            (
                "learning rate 1e-4 selected"
            ),

        "Phase_1B2":
            (
                "Adam retained"
            ),

        "Phase_1B3":
            (
                "batch size 2 selected"
            ),

        "Phase_1B4":
            (
                "no augmentation selected"
            ),

        "Phase_1C":
            (
                "Large U-Net selected"
            ),

        "Phase_1D":
            (
                "BCE + Dice selected"
            ),

        "Phase_1E":
            (
                "locked final segmentation evaluation completed"
            )
    },

    "test_driven_tuning_after_phase1e":
        False,

    "model_is_frozen_for_phase2":
        True,

    "phase2_instruction":
        (
            "Phase 2 must load this frozen model. "
            "Do not substitute an experimental Phase 1 checkpoint."
        )
}


with open(
    MANIFEST_PATH,
    "w"
) as f:

    json.dump(
        final_manifest,
        f,
        indent=2
    )


print("Manifest saved:")
print(MANIFEST_PATH)

==============================================================================================================
NOTEBOOK CELL INDEX: 13
MATCHED: threshold, connected, component
--------------------------------------------------------------------------------------------------------------
PHASE2_POINTER_PATH = (
    P1F_CONFIG_DIR /
    "phase2_segmentation_model_pointer.json"
)


phase2_pointer = {

    "model_path":
        str(
            FINAL_MODEL_PATH
        ),

    "config_path":
        str(
            FINAL_CONFIG_PATH
        ),

    "manifest_path":
        str(
            MANIFEST_PATH
        ),

    "sha256":
        final_sha256,

    "resolution":
        256,

    "threshold":
        0.50,

    "postprocessing":
        [
            "largest connected component",
            "binary hole filling"
        ],

    "frozen":
        True
}


with open(
    PHASE2_POINTER_PATH,
    "w"
) as f:

    json.dump(
        phase2_pointer,
        f,
        indent=2
    )


print("=" * 70)
print("PHASE 2 MODEL POINTER CREATED")
print("=" * 70)

print("\nPhase 2 should read:")
print(PHASE2_POINTER_PATH)

print("\nWhich points to:")
print(FINAL_MODEL_PATH)

==============================================================================================================
NOTEBOOK CELL INDEX: 14
MATCHED: threshold, connected, component
--------------------------------------------------------------------------------------------------------------
required_files = {

    "Frozen model":
        FINAL_MODEL_PATH,

    "Final configuration":
        FINAL_CONFIG_PATH,

    "Provenance manifest":
        MANIFEST_PATH,

    "Phase 2 pointer":
        PHASE2_POINTER_PATH,

    "Phase 1E record":
        P1E_RECORD_PATH
}


print("=" * 70)
print("FINAL ARTIFACT CHECK")
print("=" * 70)


all_present = True


for name, path in required_files.items():

    exists = path.exists()

    print(
        f"{name:24s}: "
        f"{'✓' if exists else '✗'}"
    )

    if not exists:
        all_present = False


assert all_present


# Recheck final hash

current_final_hash = sha256_file(
    FINAL_MODEL_PATH
)

assert (
    current_final_hash
    ==
    final_sha256
)


print("\n" + "=" * 70)
print("PHASE 1F COMPLETED")
print("=" * 70)

print(
    "\nFINAL MODEL:"
)

print(FINAL_MODEL_PATH)

print(
    "\nPARAMETERS:"
)

print("7,759,521")

print(
    "\nSHA-256:"
)

print(final_sha256)

print(
    "\nFINAL CONFIGURATION:"
)

print(
    "256×256 → Large U-Net → "
    "Adam (1e-4) → batch 2 → "
    "no augmentation → BCE+Dice"
)

print(
    "\nINFERENCE:"
)

print(
    "Threshold 0.50 → "
    "largest connected component → "
    "hole filling"
)

print(
    "\nMODEL STATUS: FROZEN"
)

print(
    "POST-TEST TUNING: NONE"
)

print(
    "\n✓ PHASE 1 SEGMENTATION IS COMPLETE."
)

print(
    "\nNEXT: Phase 2 — "
    "Quantitative LV Analysis"
)

Relevant Phase 1F code cells found: 9

In [ ]:
# ================================================================
# PHASE 5B — CELL 30
# EXACT FROZEN PREPROCESSING + PHYSICAL GEOMETRY
# Reconstructed directly from authoritative Phase 2A implementation
# ================================================================

import cv2
import nibabel as nib

from scipy.ndimage import binary_fill_holes


SEGMENTATION_RESOLUTION = 256
SEGMENTATION_THRESHOLD = 0.50


def load_nifti_2d(file_path):

    nii = nib.load(
        str(file_path)
    )

    data = np.asarray(
        nii.get_fdata()
    )

    if (
        data.ndim == 3
        and data.shape[-1] == 1
    ):
        data = data[:, :, 0]

    if data.ndim != 2:
        raise ValueError(
            f"Expected 2D NIfTI, got {data.shape}"
        )

    spacing = tuple(
        float(x)
        for x in nii.header.get_zooms()[:2]
    )

    return data, spacing


def preprocess_for_segmentation(
    image,
    target_size=256
):

    image = np.asarray(
        image,
        dtype=np.float32
    )

    original_h, original_w = image.shape

    resized = cv2.resize(
        image,
        (
            target_size,
            target_size
        ),
        interpolation=cv2.INTER_LINEAR
    )

    minimum = float(
        resized.min()
    )

    maximum = float(
        resized.max()
    )

    if maximum > minimum:

        normalized = (
            resized - minimum
        ) / (
            maximum - minimum
        )

    else:

        normalized = np.zeros_like(
            resized
        )

    scale_x = (
        original_w
        /
        target_size
    )

    scale_y = (
        original_h
        /
        target_size
    )

    return (
        normalized.astype(
            np.float32
        ),
        (
            scale_x,
            scale_y
        )
    )


def effective_spacing(
    native_spacing,
    scale_factors
):

    spacing_x, spacing_y = map(
        float,
        native_spacing
    )

    scale_x, scale_y = map(
        float,
        scale_factors
    )

    return (
        spacing_x * scale_x,
        spacing_y * scale_y
    )


def keep_largest_component(mask):

    mask_uint8 = (
        np.asarray(mask)
        .astype(np.uint8)
    )

    if mask_uint8.sum() == 0:

        return np.zeros_like(
            mask_uint8,
            dtype=bool
        )

    n_labels, labels, stats, _ = (
        cv2.connectedComponentsWithStats(
            mask_uint8,
            connectivity=8
        )
    )

    if n_labels <= 1:

        return np.zeros_like(
            mask_uint8,
            dtype=bool
        )

    largest_label = (
        1
        +
        np.argmax(
            stats[
                1:,
                cv2.CC_STAT_AREA
            ]
        )
    )

    return (
        labels
        ==
        largest_label
    )


def postprocess_prediction(
    probability_mask,
    threshold=0.50
):

    binary_mask = (
        probability_mask
        >=
        threshold
    )

    largest = keep_largest_component(
        binary_mask
    )

    filled = binary_fill_holes(
        largest
    )

    return np.asarray(
        filled
    ).astype(bool)


def mask_area_mm2(
    mask,
    spacing
):

    mask = np.asarray(
        mask
    ).astype(bool)

    spacing_x, spacing_y = map(
        float,
        spacing
    )

    return float(
        mask.sum()
        *
        spacing_x
        *
        spacing_y
    )


def mask_points_mm(
    mask,
    spacing
):

    mask = np.asarray(
        mask
    ).astype(bool)

    rows, cols = np.where(
        mask
    )

    spacing_x, spacing_y = map(
        float,
        spacing
    )

    # Exact Phase 2A coordinate convention:
    # x = image columns
    # y = image rows

    x_mm = (
        cols.astype(np.float64)
        *
        spacing_x
    )

    y_mm = (
        rows.astype(np.float64)
        *
        spacing_y
    )

    return np.column_stack([
        x_mm,
        y_mm
    ])


def pca_major_axis_mm(
    mask,
    spacing
):

    points = mask_points_mm(
        mask,
        spacing
    )

    if len(points) < 2:
        return np.nan

    centered = (
        points
        -
        points.mean(
            axis=0
        )
    )

    covariance = np.cov(
        centered,
        rowvar=False
    )

    eigenvalues, eigenvectors = (
        np.linalg.eigh(
            covariance
        )
    )

    principal_axis = (
        eigenvectors[
            :,
            np.argmax(
                eigenvalues
            )
        ]
    )

    projections = (
        centered
        @
        principal_axis
    )

    return float(
        projections.max()
        -
        projections.min()
    )


def frozen_area_length_volume_ml(
    area_mm2,
    length_mm
):

    if (
        not np.isfinite(area_mm2)
        or not np.isfinite(length_mm)
        or area_mm2 <= 0
        or length_mm <= 0
    ):
        return np.nan

    area_cm2 = (
        area_mm2
        /
        100.0
    )

    length_cm = (
        length_mm
        /
        10.0
    )

    volume_ml = (
        8.0
        /
        (
            3.0
            *
            np.pi
        )
        *
        (
            area_cm2 ** 2
        )
        /
        length_cm
    )

    return float(
        volume_ml
    )


print("=" * 80)
print("FROZEN PHASE 2 MEASUREMENT FUNCTIONS")
print("=" * 80)

print("\n✓ 256×256 stretch preprocessing")
print("✓ Post-resize per-image min-max normalization")
print("✓ Anisotropic effective spacing")
print("✓ Threshold >= 0.50")
print("✓ 8-connected largest component")
print("✓ Binary hole filling")
print("✓ Physical LV area")
print("✓ Exact PCA major-axis length")
print("✓ Single-plane area-length volume")

================================================================================
FROZEN PHASE 2 MEASUREMENT FUNCTIONS
================================================================================

✓ 256×256 stretch preprocessing
✓ Post-resize per-image min-max normalization
✓ Anisotropic effective spacing
✓ Threshold >= 0.50
✓ 8-connected largest component
✓ Binary hole filling
✓ Physical LV area
✓ Exact PCA major-axis length
✓ Single-plane area-length volume

In [ ]:
# ================================================================
# PHASE 5B — CELL 31
# LOAD EXACT FROZEN PHASE 1 SEGMENTATION MODEL
# ================================================================

import gc
import tensorflow as tf


SMOOTH = 1e-6


def dice_coefficient(
    y_true,
    y_pred
):

    y_true = tf.cast(
        y_true,
        tf.float32
    )

    y_pred = tf.cast(
        y_pred,
        tf.float32
    )

    intersection = tf.reduce_sum(
        y_true * y_pred,
        axis=[1, 2, 3]
    )

    denominator = (
        tf.reduce_sum(
            y_true,
            axis=[1, 2, 3]
        )
        +
        tf.reduce_sum(
            y_pred,
            axis=[1, 2, 3]
        )
    )

    dice = (
        2.0 * intersection
        +
        SMOOTH
    ) / (
        denominator
        +
        SMOOTH
    )

    return tf.reduce_mean(
        dice
    )


def dice_loss(
    y_true,
    y_pred
):

    return (
        1.0
        -
        dice_coefficient(
            y_true,
            y_pred
        )
    )


def bce_dice_loss(
    y_true,
    y_pred
):

    bce = (
        tf.keras.losses
        .binary_crossentropy(
            y_true,
            y_pred
        )
    )

    bce = tf.reduce_mean(
        bce
    )

    return (
        bce
        +
        dice_loss(
            y_true,
            y_pred
        )
    )


CUSTOM_OBJECTS = {

    "bce_dice_loss":
        bce_dice_loss,

    "dice_loss":
        dice_loss,

    "dice_coefficient":
        dice_coefficient
}


gc.collect()


frozen_segmentation_model = (
    tf.keras.models.load_model(
        FROZEN_SEGMENTATION_MODEL_PATH,
        custom_objects=CUSTOM_OBJECTS,
        compile=False
    )
)


assert (
    frozen_segmentation_model.input_shape
    ==
    (None, 256, 256, 1)
)

assert (
    frozen_segmentation_model.output_shape
    ==
    (None, 256, 256, 1)
)

assert (
    frozen_segmentation_model.count_params()
    ==
    7_759_521
)


print("=" * 80)
print("FROZEN SEGMENTATION MODEL LOADED")
print("=" * 80)

print(
    "\nParameters:",
    f"{frozen_segmentation_model.count_params():,}"
)

print(
    "Input shape :",
    frozen_segmentation_model.input_shape
)

print(
    "Output shape:",
    frozen_segmentation_model.output_shape
)

print(
    "\n✓ Frozen Phase 1 model ready for inference."
)

================================================================================
FROZEN SEGMENTATION MODEL LOADED
================================================================================

Parameters: 7,759,521
Input shape : (None, 256, 256, 1)
Output shape: (None, 256, 256, 1)

✓ Frozen Phase 1 model ready for inference.

In [ ]:
# ================================================================
# PHASE 5B — CELL 32
# RESTORE / VERIFY CAMUS DATASET
# ================================================================

import zipfile


OUTER_ZIP_PATH = Path(
    "/content/drive/MyDrive/download.zip"
)

OUTER_EXTRACT_DIR = Path(
    "/content/camus_data"
)

INNER_ARCHIVE_PATH = (
    OUTER_EXTRACT_DIR
    /
    "download"
)

INNER_EXTRACT_DIR = Path(
    "/content/camus_data_final"
)

DATASET_PATH = (
    INNER_EXTRACT_DIR
    /
    "database_nifti"
)


if not DATASET_PATH.exists():

    assert OUTER_ZIP_PATH.exists(), (
        f"CAMUS archive not found:\n"
        f"{OUTER_ZIP_PATH}"
    )

    if not INNER_ARCHIVE_PATH.exists():

        print(
            "Extracting outer archive..."
        )

        OUTER_EXTRACT_DIR.mkdir(
            parents=True,
            exist_ok=True
        )

        with zipfile.ZipFile(
            OUTER_ZIP_PATH,
            "r"
        ) as archive:

            archive.extractall(
                OUTER_EXTRACT_DIR
            )

    print(
        "Extracting CAMUS archive..."
    )

    INNER_EXTRACT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    with zipfile.ZipFile(
        INNER_ARCHIVE_PATH,
        "r"
    ) as archive:

        archive.extractall(
            INNER_EXTRACT_DIR
        )


assert DATASET_PATH.exists()


patient_dirs = sorted([
    path
    for path in DATASET_PATH.iterdir()
    if (
        path.is_dir()
        and path.name.startswith(
            "patient"
        )
    )
])


assert len(patient_dirs) == 500


print("=" * 80)
print("CAMUS DATASET")
print("=" * 80)

print(
    "\nPath:",
    DATASET_PATH
)

print(
    "Patients:",
    len(patient_dirs)
)

print(
    "\n✓ CAMUS dataset ready."
)

Extracting outer archive...
Extracting CAMUS archive...
================================================================================
CAMUS DATASET
================================================================================

Path: /content/camus_data_final/database_nifti
Patients: 500

✓ CAMUS dataset ready.

In [ ]:
# ================================================================
# PHASE 5B — CELL 33
# SINGLE-FRAME FROZEN SEGMENTATION → MEASUREMENT FUNCTION
# ================================================================

def analyze_lv_frame(
    image,
    native_spacing
):

    # ------------------------------------------------------------
    # 1. Frozen preprocessing
    # ------------------------------------------------------------

    processed_image, scale_factors = (
        preprocess_for_segmentation(
            image,
            target_size=
                SEGMENTATION_RESOLUTION
        )
    )


    resized_spacing = effective_spacing(
        native_spacing,
        scale_factors
    )


    # ------------------------------------------------------------
    # 2. Frozen segmentation inference
    # ------------------------------------------------------------

    model_input = (
        processed_image[
            None,
            ...,
            None
        ]
    )


    probability_mask = (
        frozen_segmentation_model(
            model_input,
            training=False
        )
        .numpy()[0, :, :, 0]
    )


    predicted_mask = (
        postprocess_prediction(
            probability_mask,
            threshold=
                SEGMENTATION_THRESHOLD
        )
    )


    # ------------------------------------------------------------
    # 3. Frozen quantitative geometry
    # ------------------------------------------------------------

    area_mm2 = mask_area_mm2(
        predicted_mask,
        resized_spacing
    )


    length_mm = pca_major_axis_mm(
        predicted_mask,
        resized_spacing
    )


    volume_ml = (
        frozen_area_length_volume_ml(
            area_mm2,
            length_mm
        )
    )


    # ------------------------------------------------------------
    # 4. Structured output
    # ------------------------------------------------------------

    return {

        "processed_image":
            processed_image,

        "probability_mask":
            probability_mask,

        "predicted_mask":
            predicted_mask,

        "native_spacing":
            tuple(
                float(x)
                for x in native_spacing
            ),

        "effective_spacing":
            tuple(
                float(x)
                for x in resized_spacing
            ),

        "scale_factors":
            tuple(
                float(x)
                for x in scale_factors
            ),

        "area_mm2":
            float(area_mm2),

        "length_mm":
            float(length_mm),

        "volume_ml":
            float(volume_ml)
    }


print(
    "✓ Single-frame frozen inference function ready."
)

✓ Single-frame frozen inference function ready.

In [ ]:
# ================================================================
# PHASE 5B — CELL 34
# ONE-PATIENT END-TO-END PHASE 2 REPRODUCTION CHECK
# ================================================================

verification_patient_id = "patient0173"


verification_patient_dir = (
    DATASET_PATH
    /
    verification_patient_id
)


assert verification_patient_dir.exists()


frame_results = {}


for phase in [
    "ED",
    "ES"
]:

    frame_path = (
        verification_patient_dir
        /
        f"{verification_patient_id}_4CH_{phase}.nii.gz"
    )


    assert frame_path.exists(), (
        f"Missing frame:\n{frame_path}"
    )


    image, native_spacing = (
        load_nifti_2d(
            frame_path
        )
    )


    frame_results[phase] = (
        analyze_lv_frame(
            image,
            native_spacing
        )
    )


# ------------------------------------------------------------
# Patient-level quantities
# ------------------------------------------------------------

reproduced_EDV_ml = (
    frame_results[
        "ED"
    ][
        "volume_ml"
    ]
)


reproduced_ESV_ml = (
    frame_results[
        "ES"
    ][
        "volume_ml"
    ]
)


reproduced_SV_ml = (
    reproduced_EDV_ml
    -
    reproduced_ESV_ml
)


reproduced_EF_pct = (
    reproduced_SV_ml
    /
    reproduced_EDV_ml
    *
    100.0
)


# ------------------------------------------------------------
# Frozen Phase 2 reference
# ------------------------------------------------------------

frozen_row = (
    phase2_frozen_patient_df[
        phase2_frozen_patient_df[
            "patient_id"
        ]
        ==
        verification_patient_id
    ]
    .iloc[0]
)


comparison_records = [

    (
        "ED area (mm²)",
        frozen_row[
            "ED_PRED_area_mm2"
        ],
        frame_results[
            "ED"
        ][
            "area_mm2"
        ]
    ),

    (
        "ES area (mm²)",
        frozen_row[
            "ES_PRED_area_mm2"
        ],
        frame_results[
            "ES"
        ][
            "area_mm2"
        ]
    ),

    (
        "ED length (mm)",
        frozen_row[
            "ED_PRED_length_mm"
        ],
        frame_results[
            "ED"
        ][
            "length_mm"
        ]
    ),

    (
        "ES length (mm)",
        frozen_row[
            "ES_PRED_length_mm"
        ],
        frame_results[
            "ES"
        ][
            "length_mm"
        ]
    ),

    (
        "EDV (mL)",
        frozen_row[
            "ED_PRED_volume_ml"
        ],
        reproduced_EDV_ml
    ),

    (
        "ESV (mL)",
        frozen_row[
            "ES_PRED_volume_ml"
        ],
        reproduced_ESV_ml
    ),

    (
        "SV (mL)",
        frozen_row[
            "PRED_SV_ml"
        ],
        reproduced_SV_ml
    ),

    (
        "EF (%)",
        frozen_row[
            "PRED_EF_pct"
        ],
        reproduced_EF_pct
    )
]


verification_rows = []


for (
    quantity,
    frozen_value,
    reproduced_value
) in comparison_records:

    verification_rows.append({

        "quantity":
            quantity,

        "frozen_phase2":
            float(
                frozen_value
            ),

        "reproduced":
            float(
                reproduced_value
            ),

        "absolute_difference":
            float(
                abs(
                    frozen_value
                    -
                    reproduced_value
                )
            )
    })


single_patient_verification_df = (
    pd.DataFrame(
        verification_rows
    )
)


print("=" * 100)
print(
    f"PHASE 2 REPRODUCTION — "
    f"{verification_patient_id}"
)
print("=" * 100)


display(
    single_patient_verification_df
)


print(
    "\nMaximum absolute difference:",
    single_patient_verification_df[
        "absolute_difference"
    ].max()
)


print(
    "\nED native spacing:",
    frame_results[
        "ED"
    ][
        "native_spacing"
    ]
)

print(
    "ED effective spacing:",
    frame_results[
        "ED"
    ][
        "effective_spacing"
    ]
)

print(
    "\nES native spacing:",
    frame_results[
        "ES"
    ][
        "native_spacing"
    ]
)

print(
    "ES effective spacing:",
    frame_results[
        "ES"
    ][
        "effective_spacing"
    ]
)

====================================================================================================
PHASE 2 REPRODUCTION — patient0173
====================================================================================================

         quantity  frozen_phase2   reproduced  absolute_difference
0   ED area (mm²)    2714.265708  2714.265708         0.000000e+00
1   ES area (mm²)    1520.238767  1520.238767         0.000000e+00
2  ED length (mm)      78.143962    78.143962         0.000000e+00
3  ES length (mm)      62.295982    62.295982         0.000000e+00
4        EDV (mL)      80.025456    80.025456         0.000000e+00
5        ESV (mL)      31.490708    31.490708         0.000000e+00
6         SV (mL)      48.534747    48.534747         7.105427e-15
7          EF (%)      60.649136    60.649136         0.000000e+00

Maximum absolute difference: 7.105427357601002e-15

ED native spacing: (0.30799999833106995, 0.30799999833106995)
ED effective spacing: (0.5859218718251213, 0.7110468711471185)

ES native spacing: (0.30799999833106995, 0.30799999833106995)
ES effective spacing: (0.5859218718251213, 0.7110468711471185)

In [ ]:
# ================================================================
# PHASE 5B — CELL 35
# FULL 50-PATIENT PHASE 2 REPRODUCTION
# ================================================================

import time


phase2_reproduction_records = []

verification_patient_ids = (
    phase2_frozen_patient_df[
        "patient_id"
    ]
    .astype(str)
    .tolist()
)


assert len(
    verification_patient_ids
) == 50


print("=" * 90)
print("FULL PHASE 2 REPRODUCTION")
print("=" * 90)

print(
    f"\nPatients to reproduce: "
    f"{len(verification_patient_ids)}"
)


start_time = time.time()


for patient_index, patient_id in enumerate(
    verification_patient_ids,
    start=1
):

    patient_dir = (
        DATASET_PATH
        /
        patient_id
    )

    assert patient_dir.exists(), (
        f"Patient directory missing:\n"
        f"{patient_dir}"
    )


    patient_frame_results = {}


    # ------------------------------------------------------------
    # ED + ES
    # ------------------------------------------------------------

    for phase in [
        "ED",
        "ES"
    ]:

        frame_path = (
            patient_dir
            /
            f"{patient_id}_4CH_{phase}.nii.gz"
        )


        assert frame_path.exists(), (
            f"Missing frame:\n"
            f"{frame_path}"
        )


        image, native_spacing = (
            load_nifti_2d(
                frame_path
            )
        )


        patient_frame_results[
            phase
        ] = analyze_lv_frame(
            image,
            native_spacing
        )


    # ------------------------------------------------------------
    # Patient-level quantitative analysis
    # ------------------------------------------------------------

    ed_volume = (
        patient_frame_results[
            "ED"
        ][
            "volume_ml"
        ]
    )


    es_volume = (
        patient_frame_results[
            "ES"
        ][
            "volume_ml"
        ]
    )


    stroke_volume = (
        ed_volume
        -
        es_volume
    )


    ejection_fraction = (
        stroke_volume
        /
        ed_volume
        *
        100.0
    )


    phase2_reproduction_records.append({

        "patient_id":
            patient_id,

        "ED_PRED_area_mm2":
            patient_frame_results[
                "ED"
            ][
                "area_mm2"
            ],

        "ES_PRED_area_mm2":
            patient_frame_results[
                "ES"
            ][
                "area_mm2"
            ],

        "ED_PRED_length_mm":
            patient_frame_results[
                "ED"
            ][
                "length_mm"
            ],

        "ES_PRED_length_mm":
            patient_frame_results[
                "ES"
            ][
                "length_mm"
            ],

        "ED_PRED_volume_ml":
            ed_volume,

        "ES_PRED_volume_ml":
            es_volume,

        "PRED_SV_ml":
            stroke_volume,

        "PRED_EF_pct":
            ejection_fraction
    })


    if (
        patient_index % 5 == 0
        or
        patient_index
        ==
        len(
            verification_patient_ids
        )
    ):

        elapsed = (
            time.time()
            -
            start_time
        )

        print(
            f"Processed "
            f"{patient_index:02d}/"
            f"{len(verification_patient_ids)} "
            f"patients "
            f"({elapsed:.1f} s)"
        )


phase2_reproduced_df = (
    pd.DataFrame(
        phase2_reproduction_records
    )
)


assert len(
    phase2_reproduced_df
) == 50


print(
    "\n✓ All 50 patients reproduced."
)

print(
    f"Total time: "
    f"{time.time() - start_time:.1f} s"
)


display(
    phase2_reproduced_df.head()
)

==========================================================================================
FULL PHASE 2 REPRODUCTION
==========================================================================================

Patients to reproduce: 50
Processed 05/50 patients (0.5 s)
Processed 10/50 patients (1.1 s)
Processed 15/50 patients (1.7 s)
Processed 20/50 patients (2.2 s)
Processed 25/50 patients (2.7 s)
Processed 30/50 patients (3.3 s)
Processed 35/50 patients (3.8 s)
Processed 40/50 patients (4.4 s)
Processed 45/50 patients (4.9 s)
Processed 50/50 patients (5.4 s)

✓ All 50 patients reproduced.
Total time: 5.4 s

,patient_id,ED_PRED_area_mm2,ES_PRED_area_mm2,ED_PRED_length_mm,ES_PRED_length_mm,ED_PRED_volume_ml,ES_PRED_volume_ml,PRED_SV_ml,PRED_EF_pct
0,patient0173,2714.265708,1520.238767,78.143962,62.295982,80.025456,31.490708,48.534747,60.649136
1,patient0391,1715.459785,1416.779002,62.373792,55.598361,40.047720,30.645103,9.402616,23.478531
2,patient0111,2603.580738,1513.588657,75.924522,53.419584,75.784239,36.402741,39.381498,51.965288
3,patient0080,3583.520570,1998.789169,82.955918,67.785216,131.398768,50.028542,81.370225,61.926171
4,patient0465,3835.133556,2027.159847,85.782194,65.549362,145.540108,53.214058,92.326050,63.436843

In [ ]:
# ================================================================
# PHASE 5B — CELL 36
# VERIFY REPRODUCED PHASE 2 VALUES AGAINST FROZEN OUTPUTS
# ================================================================

PHASE2_QUANTITATIVE_COLUMNS = [

    "ED_PRED_area_mm2",
    "ES_PRED_area_mm2",

    "ED_PRED_length_mm",
    "ES_PRED_length_mm",

    "ED_PRED_volume_ml",
    "ES_PRED_volume_ml",

    "PRED_SV_ml",
    "PRED_EF_pct"
]


phase2_verification_df = (

    phase2_frozen_patient_df[
        [
            "patient_id"
        ]
        +
        PHASE2_QUANTITATIVE_COLUMNS
    ]

    .merge(

        phase2_reproduced_df,

        on="patient_id",

        how="inner",

        suffixes=(
            "_frozen",
            "_reproduced"
        )
    )
)


assert len(
    phase2_verification_df
) == 50


phase2_verification_summary = []


for column in PHASE2_QUANTITATIVE_COLUMNS:

    frozen_values = (
        phase2_verification_df[
            f"{column}_frozen"
        ]
        .to_numpy(
            dtype=float
        )
    )


    reproduced_values = (
        phase2_verification_df[
            f"{column}_reproduced"
        ]
        .to_numpy(
            dtype=float
        )
    )


    absolute_difference = np.abs(
        frozen_values
        -
        reproduced_values
    )


    phase2_verification_summary.append({

        "quantity":
            column,

        "max_abs_difference":
            float(
                absolute_difference.max()
            ),

        "mean_abs_difference":
            float(
                absolute_difference.mean()
            ),

        "exact_matches":
            int(
                np.sum(
                    frozen_values
                    ==
                    reproduced_values
                )
            ),

        "all_close_1e-10":
            bool(
                np.allclose(
                    frozen_values,
                    reproduced_values,
                    rtol=0.0,
                    atol=1e-10
                )
            )
    })


phase2_verification_summary_df = (
    pd.DataFrame(
        phase2_verification_summary
    )
)


print("=" * 100)
print("PHASE 2 — 50-PATIENT REPRODUCTION VERIFICATION")
print("=" * 100)


display(
    phase2_verification_summary_df
)


overall_max_difference = max(

    item[
        "max_abs_difference"
    ]

    for item
    in phase2_verification_summary
)


all_quantities_reproduced = all(

    item[
        "all_close_1e-10"
    ]

    for item
    in phase2_verification_summary
)


print(
    "\nOverall maximum absolute difference:",
    overall_max_difference
)

print(
    "\nAll 8 quantities reproduced "
    "within atol=1e-10:",
    all_quantities_reproduced
)


if all_quantities_reproduced:

    print(
        "\n✓ Frozen Phase 1 → Phase 2 pipeline "
        "reproduced successfully for all 50 patients."
    )

else:

    print(
        "\n⚠ At least one quantity requires "
        "further investigation."
    )

====================================================================================================
PHASE 2 — 50-PATIENT REPRODUCTION VERIFICATION
====================================================================================================

,quantity,max_abs_difference,mean_abs_difference,exact_matches,all_close_1e-10
0,ED_PRED_area_mm2,4.547474e-13,5.456968e-14,44,True
1,ES_PRED_area_mm2,4.547474e-13,6.821210e-14,38,True
2,ED_PRED_length_mm,1.421085e-14,2.842171e-16,49,True
3,ES_PRED_length_mm,7.105427e-15,1.421085e-16,49,True
4,ED_PRED_volume_ml,1.421085e-14,2.557954e-15,40,True
5,ES_PRED_volume_ml,7.105427e-15,9.237056e-16,42,True
6,PRED_SV_ml,7.105427e-15,1.634248e-15,35,True
7,PRED_EF_pct,7.105427e-15,7.105427e-16,45,True

Overall maximum absolute difference: 4.547473508864641e-13

All 8 quantities reproduced within atol=1e-10: True

✓ Frozen Phase 1 → Phase 2 pipeline reproduced successfully for all 50 patients.

In [ ]:
# ================================================================
# PHASE 5B — CELL 37
# SAVE PHASE 2 INTEGRATION VERIFICATION EVIDENCE
# ================================================================

assert all_quantities_reproduced, (
    "Phase 2 reproduction has not passed. "
    "Do not save a successful verification record."
)


PHASE2_REPRODUCED_PATH = (
    PHASE5B_DIR
    /
    "tables"
    /
    "phase5B_reproduced_phase2_measurements.csv"
)


PHASE2_VERIFICATION_SUMMARY_PATH = (
    PHASE5B_DIR
    /
    "verification"
    /
    "phase5B_phase2_reproduction_summary.csv"
)


phase2_reproduced_df.to_csv(
    PHASE2_REPRODUCED_PATH,
    index=False
)


phase2_verification_summary_df.to_csv(
    PHASE2_VERIFICATION_SUMMARY_PATH,
    index=False
)


phase2_verification_record = {

    "phase":
        "Phase 5B — Integrated Frozen Inference Pipeline",

    "verification_target":
        "Frozen Phase 1 segmentation to Phase 2 quantitative analysis",

    "partition":
        "50-patient historical evaluation partition",

    "purpose":
        (
            "Integration reproduction check only; "
            "not model or method selection."
        ),

    "n_patients":
        50,

    "n_frames":
        100,

    "quantities_verified":
        PHASE2_QUANTITATIVE_COLUMNS,

    "numerical_tolerance": {
        "rtol":
            0.0,
        "atol":
            1e-10
    },

    "overall_max_absolute_difference":
        float(
            overall_max_difference
        ),

    "all_quantities_reproduced":
        bool(
            all_quantities_reproduced
        ),

    "pipeline_changes_made":
        False,

    "test_driven_tuning_performed":
        False,

    "interpretation":
        (
            "The integrated implementation reproduces "
            "the previously frozen quantitative outputs. "
            "The historical evaluation partition was used "
            "only to verify software/integration equivalence."
        )
}


PHASE2_VERIFICATION_JSON_PATH = (
    PHASE5B_DIR
    /
    "verification"
    /
    "phase5B_phase2_reproduction_record.json"
)


with open(
    PHASE2_VERIFICATION_JSON_PATH,
    "w"
) as f:

    json.dump(
        phase2_verification_record,
        f,
        indent=2
    )


print("=" * 90)
print("PHASE 2 INTEGRATION VERIFICATION SAVED")
print("=" * 90)

print(
    "\nReproduced measurements:"
)

print(
    PHASE2_REPRODUCED_PATH
)


print(
    "\nVerification summary:"
)

print(
    PHASE2_VERIFICATION_SUMMARY_PATH
)


print(
    "\nVerification record:"
)

print(
    PHASE2_VERIFICATION_JSON_PATH
)


print(
    "\n✓ Phase 1 → Phase 2 integration "
    "verification evidence preserved."
)

==========================================================================================
PHASE 2 INTEGRATION VERIFICATION SAVED
==========================================================================================

Reproduced measurements:
/content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline/tables/phase5B_reproduced_phase2_measurements.csv

Verification summary:
/content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline/verification/phase5B_phase2_reproduction_summary.csv

Verification record:
/content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline/verification/phase5B_phase2_reproduction_record.json

✓ Phase 1 → Phase 2 integration verification evidence preserved.

In [ ]:
# ================================================================
# PHASE 5B — FIX FROZEN CLASSIFIER VARIABLE REFERENCE
# ================================================================

from sklearn.pipeline import Pipeline

assert isinstance(
    phase3_classifier_artifact,
    Pipeline
), "Frozen Phase 3 classifier is not loaded correctly."

frozen_phase3_classifier = phase3_classifier_artifact

assert list(frozen_phase3_classifier.classes_) == [
    "Higher_EF",
    "Intermediate_EF",
    "Lower_EF"
]

print("Frozen classifier connected successfully.")
print("Classes:", frozen_phase3_classifier.classes_)
print("Ready for complete Phase 5B inference.")

Frozen classifier connected successfully.
Classes: ['Higher_EF' 'Intermediate_EF' 'Lower_EF']
Ready for complete Phase 5B inference.

In [ ]:
# ================================================================
# PHASE 5B — CELL 38
# COMPLETE FROZEN PATIENT-LEVEL INFERENCE PIPELINE
# ================================================================

def analyze_a4c_pair(
    ed_image,
    es_image,
    ed_native_spacing,
    es_native_spacing
):
    """
    Complete frozen assistive A4C analysis pipeline.

    Required input
    --------------
    ed_image, es_image:
        Identified A4C ED and ES 2D frames.

    ed_native_spacing, es_native_spacing:
        Original physical pixel spacing from the source images.

    Returns
    -------
    Structured segmentation, quantitative, and EF-band outputs.

    Important
    ---------
    This is an assistive, non-diagnostic pipeline.
    The classifier confidence is an uncalibrated model
    confidence score and must not be interpreted as a
    patient-level reliability or safety guarantee.
    """

    # ============================================================
    # PHASE 1 + PHASE 2
    # ============================================================

    ed_result = analyze_lv_frame(
        ed_image,
        ed_native_spacing
    )

    es_result = analyze_lv_frame(
        es_image,
        es_native_spacing
    )


    # ------------------------------------------------------------
    # Quantitative patient-level measurements
    # ------------------------------------------------------------

    edv_ml = float(
        ed_result["volume_ml"]
    )

    esv_ml = float(
        es_result["volume_ml"]
    )


    if (
        not np.isfinite(edv_ml)
        or not np.isfinite(esv_ml)
        or edv_ml <= 0
    ):
        raise ValueError(
            "Valid EDV/ESV could not be derived "
            "from the predicted LV masks."
        )


    sv_ml = float(
        edv_ml
        -
        esv_ml
    )


    ef_pct = float(
        sv_ml
        /
        edv_ml
        *
        100.0
    )


    # ============================================================
    # PHASE 3 FEATURE VECTOR
    # Exact frozen feature order
    # ============================================================

    feature_values = np.array(
        [[
            ed_result["area_mm2"],
            es_result["area_mm2"],

            ed_result["length_mm"],
            es_result["length_mm"],

            edv_ml,
            esv_ml,

            sv_ml,
            ef_pct
        ]],
        dtype=float
    )


    assert (
        feature_values.shape
        ==
        (1, 8)
    )


    # ============================================================
    # PHASE 3 — FROZEN CLASSIFIER
    # ============================================================

    predicted_class = (
        frozen_phase3_classifier
        .predict(
            feature_values
        )[0]
    )


    class_probabilities = (
        frozen_phase3_classifier
        .predict_proba(
            feature_values
        )[0]
    )


    classifier_classes = (
        frozen_phase3_classifier
        .classes_
    )


    class_scores = {

        str(class_name):
            float(score)

        for class_name, score
        in zip(
            classifier_classes,
            class_probabilities
        )
    }


    model_confidence_score = float(
        np.max(
            class_probabilities
        )
    )


    # ============================================================
    # STRUCTURED APPLICATION OUTPUT
    # ============================================================

    return {

        "segmentation": {

            "ED": {
                "processed_image":
                    ed_result[
                        "processed_image"
                    ],

                "probability_mask":
                    ed_result[
                        "probability_mask"
                    ],

                "predicted_mask":
                    ed_result[
                        "predicted_mask"
                    ],

                "effective_spacing":
                    ed_result[
                        "effective_spacing"
                    ]
            },

            "ES": {
                "processed_image":
                    es_result[
                        "processed_image"
                    ],

                "probability_mask":
                    es_result[
                        "probability_mask"
                    ],

                "predicted_mask":
                    es_result[
                        "predicted_mask"
                    ],

                "effective_spacing":
                    es_result[
                        "effective_spacing"
                    ]
            }
        },


        "quantitative_measurements": {

            "ED_area_mm2":
                float(
                    ed_result[
                        "area_mm2"
                    ]
                ),

            "ES_area_mm2":
                float(
                    es_result[
                        "area_mm2"
                    ]
                ),

            "ED_length_mm":
                float(
                    ed_result[
                        "length_mm"
                    ]
                ),

            "ES_length_mm":
                float(
                    es_result[
                        "length_mm"
                    ]
                ),

            "EDV_ml":
                edv_ml,

            "ESV_ml":
                esv_ml,

            "SV_ml":
                sv_ml,

            "EF_pct":
                ef_pct
        },


        "classification": {

            "estimated_EF_band":
                str(
                    predicted_class
                ),

            "class_scores":
                class_scores,

            "model_confidence_score":
                model_confidence_score,

            "confidence_interpretation":
                (
                    "Uncalibrated model confidence score; "
                    "not a patient-level reliability or "
                    "safety guarantee."
                )
        },


        "system": {

            "view":
                "A4C",

            "input_requirement":
                (
                    "Paired identified ED and ES frames "
                    "with physical pixel-spacing metadata."
                ),

            "purpose":
                (
                    "Assistive LV analysis."
                ),

            "diagnostic_status":
                "Non-diagnostic"
        }
    }


print("=" * 85)
print("COMPLETE FROZEN A4C PIPELINE")
print("=" * 85)

print(
    "\nED/ES input"
    "\n   ↓"
    "\nFrozen LV segmentation"
    "\n   ↓"
    "\nPhysical LV geometry"
    "\n   ↓"
    "\nEDV / ESV / SV / EF"
    "\n   ↓"
    "\nFrozen EF-band classifier"
    "\n   ↓"
    "\nEF band + uncalibrated confidence"
)

print(
    "\n✓ analyze_a4c_pair() ready."
)

=====================================================================================
COMPLETE FROZEN A4C PIPELINE
=====================================================================================

ED/ES input
   ↓
Frozen LV segmentation
   ↓
Physical LV geometry
   ↓
EDV / ESV / SV / EF
   ↓
Frozen EF-band classifier
   ↓
EF band + uncalibrated confidence

✓ analyze_a4c_pair() ready.

In [ ]:
# ================================================================
# PHASE 5B — CELL 39
# COMPLETE END-TO-END SINGLE-PATIENT VERIFICATION
# ================================================================

verification_patient_id = "patient0173"

verification_patient_dir = (
    DATASET_PATH
    /
    verification_patient_id
)


ed_image, ed_spacing = load_nifti_2d(
    verification_patient_dir
    /
    f"{verification_patient_id}_4CH_ED.nii.gz"
)


es_image, es_spacing = load_nifti_2d(
    verification_patient_dir
    /
    f"{verification_patient_id}_4CH_ES.nii.gz"
)


integrated_result = analyze_a4c_pair(
    ed_image=ed_image,
    es_image=es_image,
    ed_native_spacing=ed_spacing,
    es_native_spacing=es_spacing
)


frozen_phase3_row = (
    phase3_frozen_predictions_df[
        phase3_frozen_predictions_df[
            "patient_id"
        ]
        ==
        verification_patient_id
    ]
    .iloc[0]
)


print("=" * 90)
print(
    "COMPLETE END-TO-END VERIFICATION —",
    verification_patient_id
)
print("=" * 90)


print("\nQUANTITATIVE OUTPUT")
print("-" * 90)

for name, value in (
    integrated_result[
        "quantitative_measurements"
    ].items()
):

    print(
        f"{name:20s}: "
        f"{value:.6f}"
    )


print("\nCLASSIFICATION")
print("-" * 90)

print(
    "Reproduced EF band :",
    integrated_result[
        "classification"
    ][
        "estimated_EF_band"
    ]
)

print(
    "Frozen EF band     :",
    frozen_phase3_row[
        "learned_prediction"
    ]
)


print(
    "\nModel confidence   :",
    f"{integrated_result['classification']['model_confidence_score']:.6f}"
)


print("\nCLASS SCORES")
print("-" * 90)

for class_name, score in (
    integrated_result[
        "classification"
    ][
        "class_scores"
    ].items()
):

    print(
        f"{class_name:18s}: "
        f"{score:.6f}"
    )


assert (
    integrated_result[
        "classification"
    ][
        "estimated_EF_band"
    ]
    ==
    frozen_phase3_row[
        "learned_prediction"
    ]
)


print(
    "\n✓ Complete raw-image → EF-band "
    "single-patient pipeline reproduced."
)

==========================================================================================
COMPLETE END-TO-END VERIFICATION — patient0173
==========================================================================================

QUANTITATIVE OUTPUT
------------------------------------------------------------------------------------------
ED_area_mm2         : 2714.265708
ES_area_mm2         : 1520.238767
ED_length_mm        : 78.143962
ES_length_mm        : 62.295982
EDV_ml              : 80.025456
ESV_ml              : 31.490708
SV_ml               : 48.534747
EF_pct              : 60.649136

CLASSIFICATION
------------------------------------------------------------------------------------------
Reproduced EF band : Higher_EF
Frozen EF band     : Higher_EF

Model confidence   : 0.695430

CLASS SCORES
------------------------------------------------------------------------------------------
Higher_EF         : 0.695430
Intermediate_EF   : 0.282757
Lower_EF          : 0.021814

✓ Complete raw-image → EF-band single-patient pipeline reproduced.

In [ ]:
# ================================================================
# PHASE 5B — CELL 40
# 50-PATIENT COMPLETE END-TO-END REPRODUCTION
# ================================================================

import gc
import time

end_to_end_records = []
start_time = time.time()

frozen_lookup = (
    phase3_frozen_predictions_df
    .set_index("patient_id")
)

assert len(frozen_lookup) == 50
assert frozen_lookup.index.is_unique

for index, patient_id in enumerate(
    frozen_lookup.index.tolist(), start=1
):
    patient_dir = DATASET_PATH / patient_id

    ed_image, ed_spacing = load_nifti_2d(
        patient_dir / f"{patient_id}_4CH_ED.nii.gz"
    )

    es_image, es_spacing = load_nifti_2d(
        patient_dir / f"{patient_id}_4CH_ES.nii.gz"
    )

    result = analyze_a4c_pair(
        ed_image,
        es_image,
        ed_spacing,
        es_spacing
    )

    predicted_band = result["classification"]["estimated_EF_band"]
    class_scores = result["classification"]["class_scores"]

    frozen_row = frozen_lookup.loc[patient_id]

    record = {
        "patient_id": patient_id,
        "frozen_prediction": frozen_row["learned_prediction"],
        "integrated_prediction": predicted_band,
        "prediction_match": (
            predicted_band == frozen_row["learned_prediction"]
        )
    }

    for class_name in frozen_phase3_classifier.classes_:
        record[f"frozen_prob_{class_name}"] = float(
            frozen_row[f"prob_{class_name}"]
        )
        record[f"integrated_prob_{class_name}"] = float(
            class_scores[class_name]
        )

    end_to_end_records.append(record)

    del result, ed_image, es_image

    if index % 10 == 0:
        gc.collect()
        print(f"Processed {index}/50 patients")

end_to_end_df = pd.DataFrame(end_to_end_records)

probability_difference_columns = []

for class_name in frozen_phase3_classifier.classes_:
    difference_column = f"abs_diff_{class_name}"

    end_to_end_df[difference_column] = (
        end_to_end_df[f"frozen_prob_{class_name}"]
        -
        end_to_end_df[f"integrated_prob_{class_name}"]
    ).abs()

    probability_difference_columns.append(difference_column)

prediction_matches = int(end_to_end_df["prediction_match"].sum())

maximum_probability_difference = float(
    end_to_end_df[probability_difference_columns]
    .to_numpy()
    .max()
)

probabilities_reproduced = bool(
    np.allclose(
        end_to_end_df[
            [f"frozen_prob_{c}" for c in frozen_phase3_classifier.classes_]
        ].to_numpy(),
        end_to_end_df[
            [f"integrated_prob_{c}" for c in frozen_phase3_classifier.classes_]
        ].to_numpy(),
        atol=1e-10,
        rtol=0
    )
)

print("\n" + "=" * 85)
print("PHASE 5B — COMPLETE 50-PATIENT VERIFICATION")
print("=" * 85)

print(f"Prediction matches: {prediction_matches}/50")
print(f"Maximum probability difference: {maximum_probability_difference:.12g}")
print(f"Probabilities reproduced within 1e-10: {probabilities_reproduced}")
print(f"Elapsed time: {time.time() - start_time:.1f} seconds")

display(
    end_to_end_df[
        ["patient_id", "frozen_prediction",
         "integrated_prediction", "prediction_match"]
    ].head(10)
)

if prediction_matches == 50 and probabilities_reproduced:
    print("\n✓ FULL END-TO-END REPRODUCTION PASSED")
else:
    print("\n⚠ Reproduction mismatch — investigate before freezing Phase 5B")
    display(end_to_end_df.loc[~end_to_end_df["prediction_match"]])

Processed 10/50 patients
Processed 20/50 patients
Processed 30/50 patients
Processed 40/50 patients
Processed 50/50 patients

=====================================================================================
PHASE 5B — COMPLETE 50-PATIENT VERIFICATION
=====================================================================================
Prediction matches: 50/50
Maximum probability difference: 4.4408920985e-16
Probabilities reproduced within 1e-10: True
Elapsed time: 10.4 seconds

    patient_id frozen_prediction integrated_prediction  prediction_match
0  patient0004         Higher_EF             Higher_EF              True
1  patient0013          Lower_EF              Lower_EF              True
2  patient0014         Higher_EF             Higher_EF              True
3  patient0016         Higher_EF             Higher_EF              True
4  patient0017         Higher_EF             Higher_EF              True
5  patient0045          Lower_EF              Lower_EF              True
6  patient0048         Higher_EF             Higher_EF              True
7  patient0053          Lower_EF              Lower_EF              True
8  patient0058          Lower_EF              Lower_EF              True
9  patient0072   Intermediate_EF       Intermediate_EF              True

✓ FULL END-TO-END REPRODUCTION PASSED

In [ ]:
# ================================================================
# PHASE 5B — CELL 41
# SAVE FINAL END-TO-END VERIFICATION
# ================================================================

from pathlib import Path
import json
from datetime import datetime, timezone

phase5b_root = (
    Path("/content/drive/MyDrive/CAMUS_FINAL")
    / "phase5_application"
    / "phase5B_integrated_pipeline"
)

verification_dir = phase5b_root / "verification"
tables_dir = phase5b_root / "tables"

verification_dir.mkdir(parents=True, exist_ok=True)
tables_dir.mkdir(parents=True, exist_ok=True)

assert len(end_to_end_df) == 50
assert prediction_matches == 50
assert probabilities_reproduced

predictions_path = (
    tables_dir / "phase5B_final_end_to_end_predictions.csv"
)

record_path = (
    verification_dir / "PHASE5B_COMPLETE.json"
)

end_to_end_df.to_csv(predictions_path, index=False)

verification_record = {
    "phase": "5B",
    "status": "completed",
    "verified_at_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "evaluation_patients": 50,
    "evaluation_frames": 100,
    "matching_frozen_predictions": int(prediction_matches),
    "maximum_probability_difference": float(
        maximum_probability_difference
    ),
    "probability_tolerance": 1e-10,
    "all_probabilities_reproduced": bool(
        probabilities_reproduced
    ),
    "segmentation_model_retrained": False,
    "classifier_retrained": False,
    "verification_type": (
        "Reproduction of historical frozen outputs; "
        "not independent clinical validation."
    ),
    "phase2_reproduction_passed": bool(
        all_quantities_reproduced
    ),
    "phase2_maximum_absolute_difference": float(
        overall_max_difference
    ),
}

with open(record_path, "w") as f:
    json.dump(verification_record, f, indent=2)

print("PHASE 5B COMPLETED AND RECORDED")
print("Predictions:", predictions_path)
print("Verification:", record_path)

PHASE 5B COMPLETED AND RECORDED
Predictions: /content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline/tables/phase5B_final_end_to_end_predictions.csv
Verification: /content/drive/MyDrive/CAMUS_FINAL/phase5_application/phase5B_integrated_pipeline/verification/PHASE5B_COMPLETE.json